### ISSUE TITLE
Add ability to specify whole folders

### ISSUE THREAD

**Issue by jeremy-smith-maco** [JeffreyWay/laravel-mix#1019]
- Laravel Mix Version: 1.2.0
- Node Version: 8.1.4
- NPM Version: 5.3.0
- OS: LMDE 2 Betsy

### Description:
Should be able to specify whole folders rather than having to specify every single file like you used to be able to do with Laravel Elixir. I don't think it is currently a feature (if it is, I can't work out how to do it).

Example:
```
mix.js('path/to/bunchOfJsFiles', 'app.js');
```

**Comment by nkostadinov** [comment]
The order of the files is important and this way you cannot control it.

**Comment by jeremy-smith-maco** [comment]
In my case it doesn't need to be controlled. I use some individual files but some directories I just need all the files in it mixed so I just want to include the whole thing.

**Comment by JeffreyWay** [comment]
Like @nkostadinov, the order is almost important. If all you need is concatenation, then use `mix.scripts()` instead.

**Comment by jeremy-smith-maco** [comment]
Can't use `mix.scripts()` in a directory.

```
fs.js:680
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:680:18)
    at tryReadSync (fs.js:542:20)
    at Object.fs.readFileSync (fs.js:584:19)
    at Function.concatenate.sync (/home/jeremy/project/node_modules/concatenate/lib/concatenate.js:122:17)
    at FileCollection.merge (/home/jeremy/project/node_modules/laravel-mix/src/FileCollection.js:31:36)
    at ConcatenateFilesTask.merge (/home/jeremy/project/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:20:24)
    at ConcatenateFilesTask.run (/home/jeremy/project/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:11:14)
    at CustomTasksPlugin.runTask (/home/jeremy/project/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:34:14)
    at Mix.tasks.forEach.task (/home/jeremy/project/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:44)
    at Array.forEach (native)
    at Compiler.compiler.plugin.stats (/home/jeremy/project/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:23)
    at Compiler.applyPlugins (/home/jeremy/project/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:262:11)
    at Compiler.emitRecords (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:369:38)
    at emitAssets.err (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:256:10)
    at applyPluginsAsyncSeries1.err (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:362:12)
    at next (/home/jeremy/project/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/home/jeremy/project/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/jeremy/project/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:359:9)
    at require.forEach.err (/home/jeremy/project/node_modules/webpack/lib/Compiler.js:354:15)
    at /home/jeremy/project/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/jeremy/project/node_modules/webpack/node_modules/async/dist/async.js:998:13)
    at /home/jeremy/project/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /home/jeremy/project/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by ankurk91** [comment]
This may work .
```js
const glob = require("glob");
mix.js(glob.sync('./resources/assets/js/**/*.js'), 'public/js/app.js')
```

**Comment by jeremy-smith-maco** [comment]
That may work but I shouldn't have to be using another package just to use a directory for `mix.js()`. I'd still be using Laravel Elixir if it worked with `for..of` JavaScript statements.

**Comment by JeffreyWay** [comment]
`mix.scripts()` can't handle ES6 files, but `mix.babel()` can. 

@jeremy-smith-maco I didn't realize that you can't pass a folder path. I just added support tonight. Will tag it tomorrow.

https://github.com/JeffreyWay/laravel-mix/commit/2dd10f5366346275070d6165cdb0552edf7a1008

**Comment by jeremy-smith-maco** [comment]
Thank you.

**Comment by lucassmacedo** [comment]
i have the same problem..
