### ISSUE TITLE
npm run production error on windows

### ISSUE THREAD

**Issue by sicsol** [JeffreyWay/laravel-mix#1021]
I just installed Laravel-mix i'm trying to use this for a non-Laravel project.

When i run `npm run dev` no issues or warnings. 

`I'm running windows 7`
`Node version 6.11.1`

However when i run `npm run production` I get the following error:

```
$ npm run prod

method-crm@0.1.0 prod C:\MethodDev\MethodNew\MethodPhoenix\MethodUI
npm run production


method-crm@0.1.0 production C:\MethodDev\MethodNew\MethodPhoenix\MethodUI
cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

10% building modules 5/6 modules 1 active ...ethodUI\public\styles\foundation.scssTypeError: error.setMessage is not a function
    at LazyResult.handleError (C:\MethodDev\MethodNew\MethodPhoenix\MethodUI\node_modules\postcss\lib\lazy-result.js:162:23)
    at C:\MethodDev\MethodNew\MethodPhoenix\MethodUI\node_modules\postcss\lib\lazy-result.js:196:27
(node:3116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'source' of undefined
```

Here is my webpack.mix.js configuration:
```javascript
mix
.sass('public/styles/foundation.scss', 'public/styles')
.options({
        processCssUrls: false,
        postCSS: [
            require('postcss-import'),
            require('postcss-css-variables'),
            require('postcss-conditionals'),
            require('postcss-custom-media'),
            require('autoprefixer')
        ]
    });
```

**Comment by JeffreyWay** [comment]
Can you include the npm + mix version info that was in the issue template?
