### ISSUE TITLE
Bootstrap 4 compile issue

### ISSUE THREAD

**Issue by xHeinrich** [JeffreyWay/laravel-mix#1034]
- Laravel Mix Version:
+-- axios@0.16.2
+-- bootstrap@4.0.0-alpha.6 extraneous
+-- bootstrap-sass@3.3.7
+-- cross-env@5.0.1
+-- jquery@3.2.1
+-- laravel-mix@1.3.0
+-- lodash@4.17.4
`-- vue@2.4.2

- Node Version (`node -v`): 
v6.10.2
- NPM Version (`npm -v`): 
3.10.10
- OS: 
Laravel Homestead on windows host

### Description:
Bootstrap 4.0.0-alpha.6 fails to compile on newest mix version, it works on laravel-mix@0.12.1

### Steps To Reproduce:
1) Create a new laravel project
2) Run npm install
3) Download bootstrap using npm install bootstrap@4.0.0-alpha.6
4) Remove variables from app.scss and modify the default bootstrap import to @import "node_modules/bootstrap/scss/bootstrap.scss"
5) Run npm run dev

### NPM LOG ###
`Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at eachParent (C:\Users\Nathan\Documents\Homestead\theme\node_modules\browserslist\index.js:65:18)
    at getStat (C:\Users\Nathan\Documents\Homestead\theme\node_modules\browserslist\index.js:79:12)
    at browserslist (C:\Users\Nathan\Documents\Homestead\theme\node_modules\browserslist\index.js:188:15)
    at Browsers.parse (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\browsers.js:52:30)
    at Supports.prefixer (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\supports.js:48:24)
    at Supports.prefixed (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\supports.js:93:29)
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\supports.js:316:39
    at Array.map (native)
    at Supports.add (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\supports.js:314:22)
    at Supports.process (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\supports.js:339:20)
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\processor.js:43:37
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\container.js:292:28
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\container.js:144:26
    at Root.each (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\container.js:110:22)
    at Root.walk (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\container.js:143:21)
    at Root.walkAtRules (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\container.js:290:25)
    at Processor.add (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\processor.js:32:13)
    at plugin (C:\Users\Nathan\Documents\Homestead\theme\node_modules\autoprefixer\lib\autoprefixer.js:87:32)
    at LazyResult.run (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\lazy-result.js:270:20)
    at LazyResult.asyncTick (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\lazy-result.js:185:32)
    at processing.Promise.then._this2.processed (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\lazy-result.js:224:20)
    at LazyResult.async (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\lazy-result.js:221:27)
    at LazyResult.then (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss\lib\lazy-result.js:127:21)
    at Promise.resolve.then.then (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss-loader\lib\index.js:139:8)
    at runLoaders (C:\Users\Nathan\Documents\Homestead\theme\node_modules\webpack\lib\NormalModule.js:194:19)
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\Nathan\Documents\Homestead\theme\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\Nathan\Documents\Homestead\theme\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (C:\Users\Nathan\Documents\Homestead\theme\node_modules\postcss-loader\lib\index.js:176:71)`

**Comment by dwightwatson** [comment]
Just ran into the same issue and have been digging into the cause.

Looks like this might actually be an issue with a new release of browserlist (v2.2.1). There's now an open PR to fix it:  ai/browserslist#161.

**Comment by xHeinrich** [comment]
Good to know i'm not the only one, spent 3 hours trying to debug the issue and was driving myself insane.

**Comment by juresrpcic** [comment]
You can fix the issue temporarily by either excluding loading the `/bootstrap/scss/_carousel.scss` file (imported from `/bootstrap/scss/bootstrap.scss`) or by uncommenting the following lines in the file:
```
// UNCOMMENTED BECAUSE OF WEBPACK BUG
  // Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
  
  // @include if-supports-3d-transforms() {
  //   @include transition($carousel-transition);
  //   backface-visibility: hidden;
  //   perspective: 1000px;
  // }
```
and 
```
// UNCOMMENTED BECAUSE OF WEBPACK BUG
// Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
  
// // CSS3 transforms when supported by the browser
// @include if-supports-3d-transforms() {
//   .carousel-item-next.carousel-item-left,
//   .carousel-item-prev.carousel-item-right {
//     transform: translate3d(0, 0, 0);
//   }

//   .carousel-item-next,
//   .active.carousel-item-right {
//     transform: translate3d(100%, 0, 0);
//   }

//   .carousel-item-prev,
//   .active.carousel-item-left {
//     transform: translate3d(-100%, 0, 0);
//   }
// }
```

**Comment by dwightwatson** [comment]
browserslist v2.2.2 has been released which fixes this issue.

**Comment by JeffreyWay** [comment]
Yeah just did a test on a fresh install, and everything compiled properly.
