### ISSUE TITLE
"Path must be a string" returned when try to compile js&scss file

### ISSUE THREAD

**Issue by gdhillon1** [JeffreyWay/laravel-mix#115]
Upgrading from laravel 5.3 with gulp to laravel 5.4 with laravel mix. 

> webpack.mix.js

```
let mix = require('laravel-mix').mix;
mix.sass('login.scss').js('login.js');
```

> Error: 

```
cross-env NODE_ENV=development webpack --watch --progress --hide-modules --con
fig=node_modules/laravel-mix/setup/webpack.config.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.parse (path.js:950:5)
```

**Comment by JeffreyWay** [comment]
Be explicit about your output paths.

```js
mix.sass('resources/assets/sass/login.scss', 'public/css')
    .js('resources/assets/js/login.js', 'public/js');
```
