### ISSUE TITLE
version() function trigger error. Version() alternative PHP script.

### ISSUE THREAD

**Issue by alan-zhang-** [JeffreyWay/laravel-mix#1161]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): v6.11.2
- NPM Version (`npm -v`): 3.10.10
- OS: 
Mac OS 10.12.5
### Description:

Works fine with version(), but as long as I added version() to the end, it trigger error:

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/public_folder/recycling.css'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at File.read (/path_web_root/node_modules/laravel-mix/src/File.js:180:19)
    at File.version (/path_web_root/node_modules/laravel-mix/src/File.js:190:25)
    at Manifest.hash (/path_web_root/node_modules/laravel-mix/src/Manifest.js:55:65)
    at manifest.forEach.file (/path_web_root/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:47)
    at Array.forEach (native)
    at CustomTasksPlugin.applyVersioning (/path_web_root/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:18)
    at Compiler.compiler.plugin.stats (/path_web_root/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:12:22)
    at Compiler.applyPlugins (/path_web_root/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/path_web_root/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/path_web_root/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/path_web_root/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/path_web_root/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/path_web_root/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/path_web_root/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/path_web_root/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/path_web_root/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/path_web_root/node_modules/webpack/lib/Compiler.js:354:15)
    at /path_web_root/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/path_web_root/node_modules/async/dist/async.js:998:13)
    at /path_web_root/node_modules/async/dist/async.js:906:16
    at /path_web_root/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by JeffreyWay** [comment]
I need more information here.

**Comment by alan-zhang-** [comment]
I make version() works by editing node_modules/laravel-mix/src/File.js: 179 lines, removing slash at the beginning
```
   read() {
        return fs.readFileSync(this.path(), {
            encoding: 'utf-8'
        });
    }

   # changed to

    read() {
        return fs.readFileSync(this.path().substring(1), {
            encoding: 'utf-8'
        });
    }
```

However, the version use query string, what I want is changing files name, so I created a php script to do the version task (run the script before you push code to online), I post it here in case any others need this. It will create a php array mix-manifest.php beside mix-manifest.json. You may need to tune it for your own use.
```
#!/usr/bin/env php
<?php

$mix_json = project_folder('mix-manifest.json');
$mix_php = project_folder('mix-manifest.php');

$arr = json_decode(file_get_contents($mix_json), true);

foreach ($arr as $filename => $filepath) {
    $md5 = substr(md5(file_get_contents(project_folder($filepath))), 0, 9);

    // already processed
    if (strpos($filepath, $md5) !== false) {
        echo "Already processed. Haltded.";die;
    }

    $pathinfo = pathinfo($filepath);

    $newfilepath = $pathinfo['dirname'] . '/' . $pathinfo['filename'] . '.' . $md5 . '.'. $pathinfo['extension'];

    $ret[$filename] = $newfilepath;

    rename(project_folder($filepath), project_folder($newfilepath));
}

file_put_contents($mix_json, json_encode($ret, JSON_PRETTY_PRINT));
file_put_contents($mix_php,  store_array($ret));

function project_folder($file = null)
{
    return dirname(__FILE__) . '/' . $file;
}

function store_array($arr)
{
    $str = "<?php\nreturn [\n";

    $tpl = "    'aa' => 'bb',\n";

    foreach ($arr as $key => $one) {
        $str .= str_replace(['aa', 'bb'], [$key, $one], $tpl);
    }

    $str .= '];';

    return $str;
}
```
