### ISSUE TITLE
Scotch Box Pro Nginx & Laravel

### ISSUE THREAD

**Issue by TWG-Matt** [JeffreyWay/laravel-mix#1181]
- Laravel Mix Version: 1.4.2
- Node Version (`node -v`): 6.10.3 
- NPM Version (`npm -v`): 3.10.10
- OS: Ubuntu 16.04

### Description:
When I try to run npm run watch or any others, it fails.

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v6.10.3/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v6.10.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 silly lifecycle @~prewatch: no script for prewatch, continuing
7 info lifecycle @~watch: @
8 verbose lifecycle @~watch: unsafe-perm in lifecycle true
9 verbose lifecycle @~watch: PATH: /home/vagrant/.nvm/versions/node/v6.10.3/lib/node_modules/npm/bin/node-gyp-bin:/var/www/node_modules/.bin:/home/vagrant/.rvm/gems/ruby-2.4.1/bin:/home/vagrant/.rvm/gems/ruby-2.4.1@global/bin:/home/vagrant/.rvm/rubies/ruby-2.4.1/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/home/vagrant/.nvm/versions/node/v6.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/.rvm/bin:/home/vagrant/.rvm/bin
10 verbose lifecycle @~watch: CWD: /var/www
11 silly lifecycle @~watch: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~watch: Returned: code: 126  signal: null
13 info lifecycle @~watch: Failed to exec watch script
14 verbose stack Error: @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 126
14 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /var/www
17 error Linux 4.4.0-75-generic
18 error argv "/home/vagrant/.nvm/versions/node/v6.10.3/bin/node" "/home/vagrant/.nvm/versions/node/v6.10.3/bin/npm" "run" "watch"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 126
23 error Failed at the @ watch script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Steps To Reproduce:
1. Install a fresh Scotch Box.  I'm using Nginx Pro version.
2. Install Laravel ``` composer create-project --prefer-dist laravel/laravel blog "5.4.*" ```
3. Run ``` npm install ```
4. Run ``` npm run watch ```

**Comment by ruchern** [comment]
Update your `npm`. That is seriously some ancient version.

**Comment by TWG-Matt** [comment]
Thanks @ruchern .  Now my error is completely different.
```
> @ watch /var/www
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

sh: 1: cross-env: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-09-10T05_12_25_750Z-debug.log
```

**Comment by ruchern** [comment]
Remove `cross-env` from `package.json`

Change whatever that is inside the `"scripts"` key.

```json
"scripts: {
  "watch": "NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```
