### ISSUE TITLE
npm run webpack error

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#12]
When this is defined:
```
mix.sass('resources/assets/sass/styles.scss', 'public/css');
```
But not this:
```
mix.js('resources/assets/js/app.js', 'public/js');
```

in `webpack.mix.js` the following error occurs.

```
npm run dev

> @ dev /foo/bar
> webpack --watch --progress --hide-modules

/foo/bar/node_modules/laravel-mix/src/Mix.js:45
            return [this.js.entry.path, this[this.cssPreprocessor].src.path];
                           ^

TypeError: Cannot read property 'entry' of undefined
    at Object.entry (/foo/bar/node_modules/laravel-mix/src/Mix.js:45:28)
    at Object.<anonymous> (/foo/bar/webpack.config.js:34:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (/foo/bar/node_modules/webpack/bin/convert-argv.js:98:18)
    at /foo/bar/node_modules/webpack/bin/convert-argv.js:111:17
    at Array.forEach (native)
    at module.exports (/foo/bar/node_modules/webpack/bin/convert-argv.js:109:15)
    at Object.<anonymous> (/foo/bar/node_modules/webpack/bin/webpack.js:141:40)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `webpack --watch --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'webpack --watch --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --watch --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /foo/bar/npm-debug.log
```

**Comment by JeffreyWay** [comment]
Because this uses Webpack, some form of JavaScript bundling is required.

**Comment by antoniopaisfernandes** [comment]
Starting to appreciate even more what Elixir could do :)

**Comment by JeffreyWay** [comment]
Webpack isn't Gulp. Different tools entirely.

**Comment by antoniopaisfernandes** [comment]
I know :) Also know I can stay with Elixir and gulp and that ecosystem. Just fallback...

It's just some sadness over something some great features like combining already minified and production files without any additional transpiler touching then.

Never mind... Plz continue going forward
