### ISSUE TITLE
Hot reloading fails then versioning enabled.

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [JeffreyWay/laravel-mix#1275]
- Laravel Mix Version: 1.5.0
- Node Version (`node -v`): 8.7.0
- NPM Version (`npm -v`): 5.4.2
- OS: MacOS 10.12.6

### Description:
Hot reloading crashes then versioning enabled.

### Steps To Reproduce:
> laravel new test
> cd test
> npm install

webpack.mix.js:
```
let mix = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .version(); // **** added this line! ****
```
> npm run hot

edit ExampleComponent.vue
I have just added style block
```
<template>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Example Component</div>

                    <div class="panel-body">
                        I'm an example component!
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

<style>
    body {
        background-color: blue;
    }
</style>
```
hit save and npm crashes with
```
 DONE  Compiled successfully in 171ms                                                                                         20:14:41

fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/info/_sites/tut/test/public/0.2c258ddd238157ae3d8e.hot-update.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at File.read (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/File.js:180:19)
    at File.version (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/File.js:190:25)
    at Manifest.hash (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/Manifest.js:55:65)
    at manifest.forEach.file (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:47)
    at Array.forEach (<anonymous>)
    at CustomTasksPlugin.applyVersioning (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:18)
    at Compiler.compiler.plugin.stats (/Users/info/_sites/tut/test/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:12:22)
    at Compiler.applyPlugins (/Users/info/_sites/tut/test/node_modules/tapable/lib/Tapable.js:61:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ hot: `cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/info/.npm/_logs/2017-10-16T13_14_41_405Z-debug.log
```

without versioning seems to work just fine.

**Comment by ankurk91** [comment]
This has been answered tons of time, please search before creating new issue.

**Comment by Vasiliy-Bondarenko** [comment]
i've tried setPublicPath:
```
let mix = require( 'laravel-mix' );

mix.setPublicPath( 'public' )
    .js( 'resources/assets/js/app.js', 'js' )
    .extract( ['vue', 'jquery', 'axios', /*'vue2-dragula', 'lodash', 'moment', 'vue-class-component'*/] )
    .sass( 'resources/assets/sass/app.scss', 'css' )
    .version()
;
```
result is the same.
i've seen the same issue fixed with this pr https://github.com/JeffreyWay/laravel-mix/pull/1236 but it's not merged yet.

**Comment by Vasiliy-Bondarenko** [comment]
fixed for now with
```
// run versioning on production only
if (mix.inProduction()) {
    mix.version();
}
```

**Comment by ntraykov** [comment]
Thank you so, so much! Helped me a lot!

**Comment by elambro** [comment]
Similar happened to me. Deleting `mix-manifest.js` fixed it
