### ISSUE TITLE
standaloneSass error

### ISSUE THREAD

**Issue by zacksmash** [JeffreyWay/laravel-mix#1302]
- Laravel Mix Version: 1.6.0
- Node Version (`node -v`):  v8.9.0
- NPM Version (`npm -v`): 5.5.1
- OS: 

### Description:
```
Sass Compilation Failed!

/Users/project/node_modules/node-sass/bin/node-sass:235
      if (watch.indexOf(file) === -1) {
                ^

TypeError: watch.indexOf is not a function
    at /Users/project/node_modules/node-sass/bin/node-sass:235:17
    at Array.forEach (<anonymous>)
    at handler (/Users/project/node_modules/node-sass/bin/node-sass:233:17)
    at Gaze.<anonymous> (/Users/project/node_modules/node-sass/bin/node-sass:258:5)
    at emitOne (events.js:116:13)
    at Gaze.emit (events.js:211:7)
    at Gaze.emit (/Users/project/node_modules/gaze/lib/gaze.js:128:32)
    at /Users/project/node_modules/gaze/lib/gaze.js:437:16
    at StatWatcher._pollers.(anonymous function) (/Users/project/node_modules/gaze/lib/gaze.js:345:7)
    at emitTwo (events.js:126:13)

undefined:1
/Users/project/node_modules/node-sass/bin/node-sass:235
^

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at StandaloneSass.onFail (/Users/project/node_modules/laravel-mix/src/StandaloneSass.js:149:31)
    at whenOutputIsAvailable (/Users/project/node_modules/laravel-mix/src/StandaloneSass.js:48:41)
    at Socket.command.stderr.on.output (/Users/project/node_modules/laravel-mix/src/StandaloneSass.js:108:13)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zack/.npm/_logs/2017-11-06T20_11_15_872Z-debug.log
```

### Steps To Reproduce:

Update to latest Laravel Mix
Run `npm run watch`
After it compiles and loads the browser, re-save a file to trigger the error *This is super important*

**Comment by JeffreyWay** [comment]
Looks like an issue with the latest node-sass release.

https://github.com/sass/node-sass/issues/2139

I've hardcoded a safe version and have tagged 1.6.1. Try upgrading to that version, and I think it should be fixed.

**Comment by zacksmash** [comment]
@JeffreyWay That did it. Thanks!
