### ISSUE TITLE
NPM run prod error

### ISSUE THREAD

**Issue by it-can** [JeffreyWay/laravel-mix#1304]
- Laravel Mix Version: 1.6.1
- Node Version (`node -v`): v8.9.0
- NPM Version (`npm -v`): 5.5.1
- OS: Mac os x high sierra

### Description:
When running ```npm run dev``` everything works, but when running ```npm run prod``` I get the following error:

```
npm run prod

> @ prod /websites/laravel
> npm run production


> @ production /websites/laravel
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/websites/laravel/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2017-11-07T10_09_46_232Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2017-11-07T10_09_46_249Z-debug.log
```

This is my package.json
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "cross-env": "^5.1",
    "laravel-echo": "^1.3.2",
    "laravel-mix": "^1.6.1",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "pusher-js": "^4.2.1"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

Here the NPM log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/websites/laravel/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/usr/local/sbin:~/.composer/vendor/bin
9 verbose lifecycle @~prod: CWD: /websites/laravel/
10 silly lifecycle @~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle @~prod: Returned: code: 1  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `npm run production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /websites/laravel
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/Cellar/node/8.9.0/bin/node" "/usr/local/bin/npm" "run" "prod"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ prod: `npm run production`
22 error Exit status 1
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by it-can** [comment]
mmm found the issue I think...

I have this is my webpack.mix.js file

```
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.options({
    processCssUrls: false,
    purifyCss: false,
    postCss: [
        require('postcss-discard-comments')({
            removeAll: true
        })
    ],
    uglify: {
        comments: false
    }
});
```

When I comment out the ```uglify``` block then it works again...

**Comment by spaceemotion** [comment]
Had the exact same issue, removing my custom uglify settings did the trick. How would one go about this with 1.6.0 now though?

**Comment by RodrigoAngeloValentini** [comment]
The same thing is happening to me.

**Comment by craigpaul** [comment]
Also having this happen when running `npm run production`

**Comment by NBAH1990** [comment]
+1

**Comment by spaceemotion** [comment]
Update: looking at the release notes Uglify seems to require the previous settings to be wrapped in a "uglifyOptions" object now: https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyoptions (as seen by https://github.com/JeffreyWay/laravel-mix/pull/1301/files).

This still doesn't change the fact that I'm getting an exception originating from vendor.js on page load.

**Comment by craigpaul** [comment]
Confirmed @spaceemotion's suggestion does indeed fix this.

**Comment by ankurk91** [comment]
uglify options was changed in version 1.6

https://github.com/JeffreyWay/laravel-mix/pull/1301/files#diff-9d9a6cd82f41984872a66a3ab0d440c4R256

New syntax should be
```js
mix.options({
uglify: {
    uglifyOptions:{
        compress:{
        }
    }
}
});
```

**Comment by it-can** [comment]
then this page needs changing:
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/options.md

**Comment by devcircus** [comment]
seems like that page is just showing which options are available and the data type of the option, but a pull request may be accepted to make things a little more clear.

**Comment by ricardovigatti** [comment]
I had this issue recently, maybe you are running out of memory. Check it out. In my case, was a problem with swap on Ubuntu, so I just restarted my server to get it working.

**Comment by marghoobsuleman** [comment]
@ricardovigatti  You are right.

**Comment by hasanhasanzadeh** [comment]
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install

**Comment by aehenao** [comment]
Hello, resolve the error as follows.
1. Deleted the node_modules folder 
3. Delete the package-lock.json 
4. 3. Edit the package.json file and change the version of "sass-loader" to version "^7.0.0" 
5. 4. Run "npm run prod".

 and that's it. ;)
