### ISSUE TITLE
Cannot use postcss-each, postcss-conditionals, postcss-for with laravel mix

### ISSUE THREAD

**Issue by 7immer** [JeffreyWay/laravel-mix#1319]
- Laravel Mix Version: 1.6.1
- Node Version (`node -v`): v8.9.0
- NPM Version (`npm -v`): v5.5.1
- OS: mac

### Description:

Cannot use `postcss-each`, `postcss-conditionals`, `postcss-for` etc with laravel mix. There appears to be a conflict with the character `$` due to the fact that SASS seems to be running before PostCSS?

### Steps To Reproduce:
```
let mix = require('laravel-mix');
mix.sass('resources/assets/pcss/app.pcss', 'public/css')
	.options({
		postCss: [
			require('postcss-at-rules-variables')(),
			require('postcss-each')(),
			require('postcss-conditionals')(),
			require('postcss-for')(),
			require('postcss-custom-properties')(),
		]
	});
```

#### Example usage
```
:root {
	--primary: #c9d410;
	--secondary: #f49522;
	--tertiary: #79c9d2;

	--space-1: 0.5rem;
	--space-2: 1rem;
	--space-3: 1.5rem;
	--space-4: 2rem;

	--space-array: var(--space-1), var(--space-2), var(--space-3), var(--space-4);
	--colors-array: (primary, secondary, tertiary),
					(var(--primary), var(--secondary), var(--quaternary));

	--from: 1;
	--to: 3;
	--icon-exclude: 2;
}



@each $name, $color in var(--colors-array) {
	.$(name) { color: $(color); }
	.bg-$(name) { background-color: $(color); }
}

@each $val, $i in var(--space-array) {
	.pt$(i) { padding-top: $(val); }
	.pr$(i) { padding-right: $(val); }
	.pb$(i) { padding-bottom: $(val); }
	.pl$(i) { padding-left: $(val); }
	.py$(i) { padding-left: $(val); padding-right: $(val); }
	.px$(i) { padding-left: $(val); padding-right: $(val); }
	.p$(i) { padding: $(val); }
}

.some-class {
	color: #fff;

	@for $val from var(--from) to var(--to) {
		@if $val != var(--icon-exclude) {
			.icon-$val {
				background-position: 0 $(val)px;
			}
		}
	}
}
```

#### should output:
```
.primary { color: #c9d410; }
.bg-primary { background-color: #c9d410; }
.secondary { color: #f49522; }
.bg-secondary { background-color: #f49522; }
.tertiary { color: #e61a6b; }
.bg-tertiary { background-color: #e61a6b; }

.pt0 { padding-top: 0.5rem; }
.pr0 { padding-right: 0.5rem; }
.pb0 { padding-bottom: 0.5rem; }
.pl0 { padding-left: 0.5rem; }
.py0 { padding-left: 0.5rem; padding-right: 0.5rem; }
.px0 { padding-left: 0.5rem; padding-right: 0.5rem; }
.p0 { padding: 0.5rem; }
.pt1 { padding-top: 1rem; }
.pr1 { padding-right: 1rem; }
.pb1 { padding-bottom: 1rem; }
.pl1 { padding-left: 1rem; }
.py1 { padding-left: 1rem; padding-right: 1rem; }
.px1 { padding-left: 1rem; padding-right: 1rem; }
.p1 { padding: 1rem; }
.pt2 { padding-top: 1.5rem; }
.pr2 { padding-right: 1.5rem; }
.pb2 { padding-bottom: 1.5rem; }
.pl2 { padding-left: 1.5rem; }
.py2 { padding-left: 1.5rem; padding-right: 1.5rem; }
.px2 { padding-left: 1.5rem; padding-right: 1.5rem; }
.p2 { padding: 1.5rem; }
.pt3 { padding-top: 2rem; }
.pr3 { padding-right: 2rem; }
.pb3 { padding-bottom: 2rem; }
.pl3 { padding-left: 2rem; }
.py3 { padding-left: 2rem; padding-right: 2rem; }
.px3 { padding-left: 2rem; padding-right: 2rem; }
.p3 { padding: 2rem; }
.some-class {
        color: #fff;
                        .icon-1 {
                                background-position: 0 1px;
                        }
                        .icon-3 {
                                background-position: 0 3px;
                        }
}
```

#### resulting error:
```
ERROR in ./resources/assets/pcss/app.pcss
Module build failed: ModuleBuildError: Module build failed: 
@each $name, $color in var(--colors-array) {
                                           ^
      Invalid CSS after "...colors-array) {": expected 1 selector or at-rule, was ".$(name) { color: $"
      in /Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/resources/assets/pcss/app.pcss (line 19, column 45)
    at runLoaders (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/async/dist/async.js:958:16)
    at options.error (/Users/jamesisbell/Documents/Worthers/Worthers.com/6.Application/node_modules/node-sass/lib/index.js:294:32)
 @ multi ./resources/assets/js/app.js ./resources/assets/pcss/app.pcss
```

**Comment by 7immer** [comment]
See here: https://github.com/gitscrum/postcss-at-rules-variables for @ rule usage which doesn't required laravel-mix if you would like a control / base reference.

**Comment by JeffreyWay** [comment]
Not sure, honestly. Sass should run before PostCSS. So I'm not sure what the typical solution is here. 

Anyone want to chime in?

**Comment by 7immer** [comment]
Could there perhaps be two options called `postCssBefore` and `postCssAfter`?

I get that for Sass users you mostly always want Sass to run first but keeping PostCss after kind of cripples its usefulness in this case.

**Comment by thecrypticace** [comment]
It appears that it is possible to run SASS as a postCSS plugin.

I found this: https://github.com/jonathantneal/postcss-sass

Not sure how well it works but that might be an option for you.
