### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by Germey** [JeffreyWay/laravel-mix#132]
➜  laravel-mix-example git:(master) ✗ npm run dev

```
> @ dev /private/var/www/laravel-mix-example
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/private/var/www/laravel-mix-example/node_modules/.npminstall/laravel-mix/0.4.0/laravel-mix/setup/webpack.config.js:125
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/private/var/www/laravel-mix-example/node_modules/.npminstall/webpack/2.2.0/webpack/bin/convert-argv.js:96:18)
    at /private/var/www/laravel-mix-example/node_modules/.npminstall/webpack/2.2.0/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/www/laravel-mix-example/npm-debug.log
```

➜  laravel-mix-example git:(master) ✗ node -v
v5.10.1
➜  laravel-mix-example git:(master) ✗ npm -v
3.8.3
➜  laravel-mix-example git:(master) ✗ cat package.json 

```
{
  "private": true,
  "scripts": {
    "webpack": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "dev": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.2",
    "babel": "^6.5.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.1.4",
    "jquery": "^3.1.0",
    "laravel-mix": "^0.4.0",
    "lodash": "^4.16.2",
    "vue": "^2.0.1",
    "webpack": "^2.2.0"
  }
}%   
npm ERR!     /private/var/www/laravel-mix-example/npm-debug.log
```

➜  laravel-mix-example git:(master) ✗ webpack -v
2.2.0
.babelrc
```
{
    "presets": [
        "es2015"
    ]
}
```

I have tried all methods but it still go wrong? Can you help me ?

**Comment by QWp6t** [comment]
Update node

**Comment by Germey** [comment]
@QWp6t Thanks a lot, I've update node to v7.3.0 and I works!
