### ISSUE TITLE
gifsicle failed to process GIF image.

### ISSUE THREAD

**Issue by the94air** [JeffreyWay/laravel-mix#1321]
- Laravel Mix Version: v1.6.1
- Node Version: v9.1.0
- NPM Version: v5.5.1
- OS: Ubuntu 16.04

### Description:
@ankurk91 laravel mix is showing this error while compiling a gif image:
```bash
ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at runLoaders (/var/www/html/laravel-mix/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/laravel-mix/node_modules/img-loader/index.js:45:31
    at <anonymous>
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at runLoaders (/var/www/html/laravel-mix/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/laravel-mix/node_modules/img-loader/index.js:45:31
    at <anonymous>
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

### Steps To Reproduce:

1. Install new laravel project `laravel new` & `npm install`
2. install photoswipe package `npm install photoswipe --save`
3. go to `resources/assets/sass/app.scss` and import these files
```scss
@import "~photoswipe/src/css/main";
@import "~photoswipe/src/css/default-skin/default-skin";
```
and then you should run mix `npm run watch` and you should see the error.

**Comment by ankurk91** [comment]
Disable image optimisations:

```js
mix.options({
  imgLoaderOptions: {
    enable: false
  }
});
```

**Comment by the94air** [comment]
I got the same error. I think its a Linux issue?
```bash
 error  in ./node_modules/photoswipe/src/css/default-skin/preloader.gif

Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/var/www/html/laravel-mix/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 6:168429-168507
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at runLoaders (/var/www/html/laravel-mix/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/laravel-mix/node_modules/img-loader/index.js:45:31
    at <anonymous>

                                                                                                    Asset       Size  Chunks                    Chunk Names
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1    20.1 kB          [emitted]         
fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb      18 kB          [emitted]         
 fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158    23.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512    45.4 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760     109 kB          [emitted]         
          images/vendor/photoswipe/src/css/default-skin/default-skin.png?e3f799c6dec9af194c86decdf7392405  547 bytes          [emitted]         
           fonts/vendor/photoswipe/src/css/default-skin/default-skin.svg?b257fa9c5ac8c515ac4d77a667ce2943    1.55 kB          [emitted]         
                                                                                               /js/app.js    1.23 MB       0  [emitted]  [big]  /js/app

ERROR in ./node_modules/photoswipe/src/css/default-skin/preloader.gif
Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/var/www/html/laravel-mix/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss 6:168429-168507
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed: Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/var/www/html/laravel-mix/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at runLoaders (/var/www/html/laravel-mix/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/laravel-mix/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/laravel-mix/node_modules/img-loader/index.js:45:31
    at <anonymous>
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

**Comment by carbontwelve** [comment]
I get a similar error on windows 7:

```console
ERROR in ./resources/assets/images/landing-dog.gif
Module build failed: Error: Command failed: F:\****\****\node_modules\gifsicle\vendor\gifsicle.exe --no-warnings --no-app-extensions --output C:\Users\SIMON~1.DAN\AppData\Local\Temp\45457b02-048c-4b3b-ac9d-69e2053ada21 C:\Users\SIMON~1.DAN\AppData\Lo
cal\Temp\974453b3-6150-47f2-ad2d-c85e8f75f4a0
    at Promise.all.then.arr (F:\****\****\node_modules\execa\index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":false,"ident":"postcss","plugins":[null,null]}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./resources/assets/less/fronte
nd.less 7:34597-34633
 @ ./resources/assets/less/frontend.less
 @ multi ./resources/assets/js/backend.js ./resources/assets/less/frontend.less ./resources/assets/less/backend.less

ERROR in ./resources/assets/less/frontend.less
Module build failed: ModuleBuildError: Module build failed: Error: Command failed: F:\****\****\node_modules\gifsicle\vendor\gifsicle.exe --no-warnings --no-app-extensions --output C:\Users\SIMON~1.DAN\AppData\Local\Temp\42034ee0-c4a3-4867-a765-67bb7
f96b369 C:\Users\SIMON~1.DAN\AppData\Local\Temp\49c7ca88-ae90-4fb9-8a79-92b46b32ec44
    at Promise.all.then.arr (F:\****\****\node_modules\execa\index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at runLoaders (F:\****\****\node_modules\webpack\lib\NormalModule.js:195:19)
    at F:\****\****\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\****\****\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (F:\****\****\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at F:\****\****\node_modules\img-loader\index.js:45:31
    at <anonymous>
 @ ./resources/assets/less/frontend.less
 @ multi ./resources/assets/js/backend.js ./resources/assets/less/frontend.less ./resources/assets/less/backend.less
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Simon.Dann\AppData\Roaming\npm-cache\_logs\2018-01-19T15_25_30_153Z-debug.log
error Command failed with exit code 2.
```

**Comment by carbontwelve** [comment]
Ok looks like running `npm rebuild --no-bin-links` fixed things when I then run via `npm run dev`.

I think the problem in my case was using `yarn` as even now running `yarn run dev` gives errors while `npm run dev` will complete fine (yarn version 1.3.2, npm version 5.5.1)
