### ISSUE TITLE
Unable to find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by ellisio** [JeffreyWay/laravel-mix#1442]
- Laravel Mix Version: 2.0.0
- Node Version (`node -v`): 9.4.0 
- NPM Version (`npm -v`): 5.6.0
- OS: macOS 10.12.6

### Description:

When running `npm run dev` I receive the following error:

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/anellis/Developer/TextLoop/node_modules/laravel-mix/src/builder/webpack-plugins.js:9:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

### Steps To Reproduce:

Using the following `webpack.mix.js` running the latest version of Laravel Mix results in this error.

```
let mix = require('laravel-mix');

mix
    .js('resources/assets/js/admin/app.js', 'public/js/admin')
    .js('resources/assets/js/agent/app.js', 'public/js/agent')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sass('resources/assets/sass/collector.scss', 'public/css');
```

I tried running the following to ensure a clean working slate:

```
rm -rf node_modules
npm cache clear --force
npm install
```

No luck.

Installed packages:

```
├── @fortawesome/fontawesome@1.1.3
├── @fortawesome/fontawesome-free-brands@5.0.6
├── @fortawesome/fontawesome-free-regular@5.0.6
├── @fortawesome/fontawesome-free-solid@5.0.6
├── @fortawesome/fontawesome-pro-light@5.0.6
├── @fortawesome/fontawesome-pro-regular@5.0.6
├── @fortawesome/fontawesome-pro-solid@5.0.6
├── @fortawesome/vue-fontawesome@0.0.22
├── avoriaz@6.3.0
├── axios@0.17.1
├── babel-polyfill@6.26.0
├── babel-preset-env@1.6.1
├── babel-preset-stage-2@6.24.1
├── bootstrap@4.0.0
├── choices.js@3.0.3
├── cross-env@5.1.3
├── es6-promise@4.2.4
├── eslint@4.16.0
├── eslint-plugin-vue@4.2.2
├── flag-icon-css@2.9.0
├── izitoast@1.2.0
├── jest@22.1.4
├── jquery@3.3.1
├── laravel-mix@2.0.0
├── lodash@4.17.4
├── moment-timezone@0.5.14
├── popper.js@1.13.0
├── pusher-js@4.2.2
├── vue@2.5.13
├── vue-echo@1.0.1
├── vue-jest@2.0.0
├── vue-progressbar@0.7.3
├── vue-router@3.0.1
├── vue-template-compiler@2.5.13
└── vuex@3.0.1
```

**Comment by Nekura** [comment]
There seems to be a problem with the uglifyjs-webpack-plugin 
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/217

**Comment by ellisio** [comment]
Thank you @Nekura. I would say leave this open until the dependency is fixed so others experiencing this issue see this for the temporary work around.

**Comment by v1ncen** [comment]
Upgrading to 1.1.8 fixed it too for me.

npm i --save-dev uglifyjs-webpack-plugin@1.1.8
