### ISSUE TITLE
browserSync produces errors

### ISSUE THREAD

**Issue by DrewNeon** [JeffreyWay/laravel-mix#1541]
- Laravel Mix Version: 2.1.8
- Node Version: v9.8.0
- NPM Version: 5.6.0
- OS: macOS High Sierra 10.13.3

### Description:
There was no problem with the default configuration. When browserSync is added to webpack.mix.js, the following error occurs for both `npm run dev` and `npm run watch`.

`> npm run development

> @ development /Users/user/Sites/blog
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Additional dependencies must be installed. This will only take a moment.
/bin/sh: yarn: command not found
child_process.js:615
    throw err;
    ^

Error: Command failed: yarn add browser-sync --dev
/bin/sh: yarn: command not found

    at checkExecSyncError (child_process.js:575:11)
    at execSync (child_process.js:612:13)
    at installDependencies (/Users/user/Sites/blog/node_modules/laravel-mix/src/Verify.js:164:5)
    at list.forEach.dependency (/Users/user/Sites/blog/node_modules/laravel-mix/src/Verify.js:104:17)
    at Array.forEach (<anonymous>)
    at Function.dependencies (/Users/user/Sites/blog/node_modules/laravel-mix/src/Verify.js:91:14)
    at concat.filter.tap.dependencies (/Users/user/Sites/blog/node_modules/laravel-mix/src/components/ComponentFactory.js:131:24)
    at Array.tap (/Users/user/Sites/blog/node_modules/laravel-mix/src/helpers.js:22:5)
    at ComponentFactory.installDependencies (/Users/user/Sites/blog/node_modules/laravel-mix/src/components/ComponentFactory.js:130:14)
    at Mix.listen (/Users/user/Sites/blog/node_modules/laravel-mix/src/components/ComponentFactory.js:55:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-03-19T00_21_10_965Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-03-19T00_21_10_990Z-debug.log`

### Steps To Reproduce:

1. `laravel new blog`
2. `cd blog`
3. `npm install`
4. open webpack.mix.js and add the following code:
`mix.browserSync({proxy: 'laravel.test', browser:'Google Chrome'});`
5. `npm run dev` or `npm run watch`

**Comment by DrewNeon** [comment]
This issue was fixed by manually install "yarn" via `npm install yarn`.
