### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by monoland** [JeffreyWay/laravel-mix#1549]
After update to version 2.1.9, I found this error while compile stylus file

```
ERROR in ./resources/styles/index.styl
Module build failed: ModuleBuildError: Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:1183:5)
    at normalizePaths (...../node_modules/stylus-loader/lib/pathcache.js:301:21)
```

**Comment by jijoel** [comment]
I'm seeing the same thing. It is broken in version 2.1.8 (2.1.7 works fine).

**Comment by cworreschk** [comment]
Same as #1543 .

**Comment by JeffreyWay** [comment]
Closing in favor of the other issues. Tagging a fix today.
