### ISSUE TITLE
Vue SPCs can't be compiled with Laravel Mix 2.1.8 and 2.1.9

### ISSUE THREAD

**Issue by cworreschk** [JeffreyWay/laravel-mix#1550]
- Laravel Mix Version: `2.1.8`, `2.1.9`
- Node Version: `9.2`
- NPM Version: `5.6.0`
- Yarn Version: `1.5.1`
- OS: `Windows 7 SP1`

### Description:

Considering Issue #1543 it's still not possible to compile _Vue Single File Components_ with imported Stylus files.

With _Laravel Mix_ `2.1.7` everything is fine.

### Steps To Reproduce:

- Create these three files (`index.js`, `HelloWord.vue`,  `colors.styl`) in the same folder.

```stylus
// colors.styl

color_red  = #ff0000
color_blue = #0000ff
```
```vue
<!-- HelloWorld.vue -->

<template>
  <div id="app">
    <h1>Hello world</h1>
  </div>
</template>

<script>
  export default {
    name: 'hello-world'
  }
</script>

<style lang="stylus">
  @import './colors.styl';

  h1
    color color_blue
</style>
```

```js
// index.js

import Vue from 'vue'
import App from './HelloWorld'

new Vue({
  el: '#app',
  template: '<App/>',
  components: { App }
})
```

- Try to compile the `index.js` file with the `mix.js()` method.

### Result:

```
ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-ca3f0fb8","scoped":false,"hasInlineConfig":true}!./node_modules/stylus-loader!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./HelloWorld
.vue
Module build failed: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:346:5)
    at normalizePaths (C:\test\node_modules\stylus-loader\lib\pathcache.js:301:21)
    at stylusFile (C:\test\node_modules\stylus-loader\lib\pathcache.js:102:14)
    at C:\test\node_modules\stylus-loader\lib\pathcache.js:159:32
    at tryCatchResolve (C:\test\node_modules\when\lib\apply.js:46:23)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:30:12)
    at callAndResolveNext (C:\test\node_modules\when\lib\apply.js:40:4)
    at tryCatchReject3 (C:\test\node_modules\when\lib\makePromise.js:851:7)
    at runContinuation3 (C:\test\node_modules\when\lib\makePromise.js:809:4)
    at Fulfilled.fold (C:\test\node_modules\when\lib\makePromise.js:586:4)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:34:12)
    at callAndResolveNext (C:\test\node_modules\when\lib\apply.js:40:4)
    at tryCatchReject3 (C:\test\node_modules\when\lib\makePromise.js:851:7)
    at runContinuation3 (C:\test\node_modules\when\lib\makePromise.js:809:4)
    at Fulfilled.fold (C:\test\node_modules\when\lib\makePromise.js:586:4)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:34:12)
    at callAndResolveNext (C:\test\node_modules\when\lib\apply.js:40:4)
    at tryCatchReject3 (C:\test\node_modules\when\lib\makePromise.js:851:7)
    at runContinuation3 (C:\test\node_modules\when\lib\makePromise.js:809:4)
    at Fulfilled.fold (C:\test\node_modules\when\lib\makePromise.js:586:4)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:34:12)
    at apply (C:\test\node_modules\when\lib\apply.js:23:4)
    at C:\test\node_modules\when\lib\decorators\array.js:279:12
    at Array.reduce (<anonymous>)
    at Function.reduce (C:\test\node_modules\when\lib\decorators\array.js:258:37)
    at tryCatchResolve (C:\test\node_modules\when\lib\apply.js:46:23)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:30:12)
    at callAndResolveNext (C:\test\node_modules\when\lib\apply.js:40:4)
    at tryCatchReject3 (C:\test\node_modules\when\lib\makePromise.js:851:7)
    at runContinuation3 (C:\test\node_modules\when\lib\makePromise.js:809:4)
    at Fulfilled.fold (C:\test\node_modules\when\lib\makePromise.js:586:4)
    at callAndResolve (C:\test\node_modules\when\lib\apply.js:34:12)
    at callAndResolveNext (C:\test\node_modules\when\lib\apply.js:40:4)
    at tryCatchReject3 (C:\test\node_modules\when\lib\makePromise.js:851:7)
    at runContinuation3 (C:\test\node_modules\when\lib\makePromise.js:809:4)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-ca3f0fb8","scoped":false,"hasInlineConfig":true}!./node_modules/stylus-loader!./node_modules/vue-loader/lib/selector.js?type=style
s&index=0!./HelloWorld.vue 4:14-320
 @ ./HelloWorld.vue
 @ ./index.js
 @ multi ./index.js
```

**Comment by JeffreyWay** [comment]
Fixed in 2.1.10.
