### ISSUE TITLE
gulp-util deprecated

### ISSUE THREAD

**Issue by alexandre1985** [JeffreyWay/laravel-mix#1559]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0`)
- Node Version (`node -v`): 8.10.0
- NPM Version (`npm -v`): 5.6.0
- OS: Manjaro Linux Deepin

### Description:
gulp-util deprecated.
Please remove gulp-util using the following API replacements:

    gutil.File => https://www.npmjs.com/package/vinyl
    gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
    gutil.colors => https://www.npmjs.com/package/ansi-colors
    gutil.date => https://www.npmjs.com/package/date-format
    gutil.log => https://www.npmjs.com/package/fancy-log
    gutil.template => https://www.npmjs.com/package/lodash.template
    gutil.env => https://www.npmjs.com/package/minimist
    gutil.beep => https://www.npmjs.com/package/beeper
    gutil.noop => https://www.npmjs.com/package/through2
    gutil.isStream => Use the .isStream() method on Vinyl objects
    gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
    gutil.isNull => Use the .isNull() method on Vinyl objects
    gutil.linefeed => Use the string '\n' in your code
    gutil.combine => https://www.npmjs.com/package/multipipe
    gutil.buffer => https://www.npmjs.com/package/list-stream
    gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by JeffreyWay** [comment]
This has to be addressed many levels down from Mix.

**Comment by alexandre1985** [comment]
But when I do:
```
laravel new app
cd app
npm i webpack webpack-cli laravel-mix cross-env --save-dev
npm run dev
```
I get a error that I believe is from laravel-mix. You should test this to see. Im using the latest node lts on linux.

**Comment by JeffreyWay** [comment]
I don't get an error when I run those commands. Only a warning. 

gulp-util is a dependency of a dependency of a dependency. We don't specifically use gulp-util anywhere in the laravel-mix codebase.

**Comment by alexandre1985** [comment]
My `package.json` is:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1.4",
        "jquery": "^3.2",
        "laravel-mix": "^2.1.11",
        "lodash": "^4.17.4",
        "popper.js": "^1.12",
        "vue": "^2.5.7",
        "webpack": "^4.2.0",
        "webpack-cli": "^2.0.13"
    }
}
```
and when I run `npm run dev` I get this error:
```
> @ dev /home/daniel/dev/vuejs/laracasts/vue2/24
> npm run development


> @ development /home/daniel/dev/vuejs/laracasts/vue2/24
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 77% module and chunk tree optimization unnamed compat plugin/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Chunk.js:460
		throw new Error(
		^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Chunk.js:460:9)
    at /home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Compiler.js:480:17)
    at _err0 (eval at create (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/home/daniel/dev/vuejs/laracasts/vue2/24/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-03-22T19_21_46_753Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-03-22T19_21_46_808Z-debug.log
```

**Comment by devcircus** [comment]
Those errors seem to be unrelated to a deprecated gulp-util package.

**Comment by devcircus** [comment]
You're using webpack 4. See [this issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701).

**Comment by JeffreyWay** [comment]
Yeah, you don't need to manually install webpack or webpack-cli. Just do `npm install` for your Laravel app, and it'll work.

**Comment by alexandre1985** [comment]
Thank you @JeffreyWay and @devcircus .
I did `rm -Rf node_modules` copied the `laravel` default new project package.json and did `npm install`.
After a `npm run dev` I get this error:
```
> @ dev /home/daniel/dev/vuejs/laracasts/vue2/24
> npm run development


> @ development /home/daniel/dev/vuejs/laracasts/vue2/24
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-03-22T21_32_06_653Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-03-22T21_32_06_697Z-debug.log

```

**Comment by devcircus** [comment]
Did you remove your package.lock first (yarn.lock if using yarn)?
Google "npm events.js "183" unhandled error event bootstrap_node" and there's a lot of information. Look through some of those issues.

**Comment by alexandre1985** [comment]
Thank you @devcircus , didn't know I also had to remove package-lock.json. Solved
