### ISSUE TITLE
.autoload works only after .js

### ISSUE THREAD

**Issue by cjmaxik** [JeffreyWay/laravel-mix#156]
Hello!
I have this code:
```javascript
mix.less('resources/assets/less/app.less', 'public/css')
    .js('resources/assets/js/app.js', 'public/js')
    .autoload({
        moment: ['moment'],
        tz: ['moment-timezone']
    })
    .extract([
        'jquery',  'bootstrap', 'moment', 'moment-timezone', 'js-cookie', 'icheck'
    ])
    .version();
```

First of all, `.autoload` works only if I have libraries in arrays.
```javascript
.autoload({
    moment: 'moment',
    tz: 'moment-timezone'
})
```

```javascript
g:\OpenServer\domains\help.bigmp.local\node_modules\laravel-mix\src\index.js:66
        libs[library].forEach(alias => {
                      ^
TypeError: libs[library].forEach is not a function
    at Object.keys.forEach.library (g:\OpenServer\domains\help.bigmp.local\node_modules\laravel-mix\src\index.js:66:23)
    at Array.forEach (native)
    at Object.module.exports.autoload (g:\OpenServer\domains\help.bigmp.local\node_modules\laravel-mix\src\index.js:65:23)
[...]
```

Secondly, .autoload works only AFTER .js, but it doesn't matter after.
```javascript
g:\OpenServer\domains\help.bigmp.local\node_modules\laravel-mix\src\index.js:71
    Mix.js.autoload = aliases;
                    ^

TypeError: Cannot set property 'autoload' of undefined
    at Object.module.exports.autoload (g:\OpenServer\domains\help.bigmp.local\node_modules\laravel-mix\src\index.js:71:21)
```

```javascript
app.51a6870….js:12 Uncaught ReferenceError: moment is not defined
    at HTMLDocument.<anonymous> (app.51a6870….js:12)
    at fire (vendor.f267569….js:7499)
    at Object.fireWith [as resolveWith] (vendor.f267569….js:7629)
    at Function.ready (vendor.f267569….js:7848)
    at HTMLDocument.completed (vendor.f267569….js:7864)
```

**Comment by JeffreyWay** [comment]
Yeah the format to the autoload method is different than what Webpack expects. I'll think on this today.

**Comment by JeffreyWay** [comment]
Okay this is fixed in master now. When you call mix.autoload, pass an object, like so:

```js
mix.autoload({
   jquery: ['$', 'window.jQuery', 'etc']
});
```
