### ISSUE TITLE
copyDirectory()  unable to handle existing folders

### ISSUE THREAD

**Issue by Konafets** [JeffreyWay/laravel-mix#1561]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): 9.9
- NPM Version (`npm -v`): 5.6
- OS: OSX 10.13.3

### Description:
When using `copyDirectory()` the directory is copied at the first run of `yarn run dev` or `yarn run watch`. At every subsequent run I got this error message:

```
fs.js:1054
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink '../blueimp-tmpl/js/compile.js' -> '/Users/$user/Sites/siom/local/htdocs/public/js/blueimp-file-upload/node_modules/.bin/tmpl.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1054:18)
    at copySync (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:58:8)
    at contents.forEach.content (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at contents.forEach.content (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at copySync (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at contents.forEach.content (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:54:7)
    at Array.forEach (native)
    at Object.copySync (/Users/$user/Sites/siom/local/htdocs/node_modules/fs-extra/lib/copy-sync/copy-sync.js:51:14)
    at File.copyTo (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/File.js:210:12)
    at FileCollection.copyTo (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/FileCollection.js:88:24)
    at src.forEach.file (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/FileCollection.js:82:38)
    at Array.forEach (native)
    at FileCollection.copyTo (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/FileCollection.js:82:17)
    at CopyFilesTask.run (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/tasks/CopyFilesTask.js:14:20)
    at CustomTasksPlugin.runTask (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:34:14)
    at Mix.tasks.forEach.task (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:44)
    at Array.forEach (native)
    at Compiler.compiler.plugin.stats (/Users/$user/Sites/siom/local/htdocs/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:23)
    at Compiler.applyPlugins (/Users/$user/Sites/siom/local/htdocs/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/$user/Sites/siom/local/htdocs/node_modules/webpack/lib/Compiler.js:264:11)
    at Compiler.emitRecords (/Users/$user/Sites/siom/local/htdocs/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/Users/$user/Sites/siom/local/htdocs/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/Users/$user/Sites/siom/local/htdocs/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Users/$user/Sites/siom/local/htdocs/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/$user/Sites/siom/local/htdocs/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/$user/Sites/siom/local/htdocs/node_modules/tapable/lib/Tapable.js:222:13)
```

### Steps To Reproduce:
```
mix.copyDirectory('node_modules/blueimp-file-upload', 'public/js/blueimp-file-upload');
```

**Comment by Konafets** [comment]
LOL. The inactivity came not from my side.

**Comment by Konafets** [comment]
@JeffreyWay Would you mind to look into this?
