### ISSUE TITLE
windows 10 npm run dev problem

### ISSUE THREAD

**Issue by hayreddintuzel** [JeffreyWay/laravel-mix#1563]
laravel-mi

- Laravel Mix Version: 2.1.11
- Node Version : 8.10.0
- NPM Version: 5.6.0
- OS: Windows 10

### Description:
I tried to run command:
 `npm run dev`
 I encountered that error:
`> @ dev C:\xampp\htdocs\turacoondev
> npm run development
> @ development C:\xampp\htdocs\turacoondev
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
 11% building modules 14/16 modules 2 active ...ndev\resources\assets\js\bootstrap.jsTypeError: dep.getResourceIdentifier is not a function
    at addDependency (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:387:30)
    at iterationOfArrayCallback (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:78:3)
    at addDependenciesBlock (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:407:5)
    at Compilation.processModuleDependencies (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:418:4)
    at afterBuild (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:545:16)
    at _this.buildModule.err (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:591:11)
    at callback (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:342:35)
    at module.build.error (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\Compilation.js:378:12)
    at handleParseResult (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\NormalModule.js:363:12)
    at doBuild.err (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\NormalModule.js:385:6)
    at runLoaders (C:\xampp\htdocs\turacoondev\node_modules\webpack\lib\NormalModule.js:264:12)
    at C:\xampp\htdocs\turacoondev\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\xampp\htdocs\turacoondev\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at Array.<anonymous> (C:\xampp\htdocs\turacoondev\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\xampp\htdocs\turacoondev\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\xampp\htdocs\turacoondev\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\xampp\htdocs\turacoondev\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hayre\AppData\Roaming\npm-cache\_logs\2018-03-24T12_44_00_337Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hayre\AppData\Roaming\npm-cache\_logs\2018-03-24T12_44_00_369Z-debug.log
`

### Steps To Reproduce:

I moved my project from another windows machine, I tried npm run dev and I encountered cross-env problem. I try npm rebuild --no-bin-links and install cros-env globally.

After I encountered that error. ı can not handle this.

**Comment by MohannadNaj** [comment]
For ref https://github.com/webpack/webpack/issues/6675

it's not a cross-env issue.

Just for clarification, you tried removing node_modules and `npm install` again, right? also, if you can show us your `webpack.mix.js`,  `package.json`, and maybe `bootstrap.js` file also since it's broke there.

I'm working on the same environment as yours, except it's node v8.9.4, and there is no issues.

**Comment by geoff-maddock** [comment]
Trying to figure out why I can't get mix to work on my windows 10 setup and came to this page.  
Is it still the case that mix is not compatible with 4.5 (how can we tell?)

my package.json specifies a devDependency of 4.5:
        "webpack": "^4.5.0",

**Comment by devcircus** [comment]
Support for 4 is still a work in progress. https://github.com/JeffreyWay/laravel-mix/pull/1495

**Comment by hayreddintuzel** [comment]
I solved this problem, but I dont  remember how :) you can try run as a adminstrator your command prompt. I guess this solve my problem.
