### ISSUE TITLE
mozjpeg failed to build from source - command failed: autoreconf -fiv

### ISSUE THREAD

**Issue by kickthemooon** [JeffreyWay/laravel-mix#1585]
- Laravel Mix Version: 1.7.2
- Node Version: 6.13.0
- NPM Version: 3.10.10
- OS: Centos 6.9

### Description:
I can't get my `npm install` to install mozjpeg.
I get the following error:
```
Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="/home/forgeit/forgeit.qa/node_modules/mozjpeg/vendor" --bindir="/home/forgeit/forgeit.qa/node_modules/mozjpeg/vendor" --libdir="/home/forgeit/forgeit.qa/node_modules/mozjpeg/vendor" && make -j2 && make install -j2
Command failed: autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
```

I installed all the packages that I found to be helpful with this issue but the issue remains.

Packages I installed:

 - make-3.81-23.el6.x86_64
 - automake-1.11.1-4.el6.noarch
 - autoconf-2.63-5.1.el6.noarch
 - libtool-2.2.6-15.5.el6.x86_64
 - libpng-1.2.49-2.el6_7.x86_64
 - libjpeg-turbo-1.2.1-3.el6_5.x86_64
 - nasm-2.07-7.el6.x86_64
 - gcc-4.4.7-18.el6_9.2.x86_64
 - gcc-c++-4.4.7-18.el6_9.2.x86_64
 - dpkg-1.16.18-2.el6.x86_64
 - pkgconfig-0.23-9.1.el6.x86_64

Here i read something about pkg-config macros:
https://github.com/mozilla/mozjpeg/issues/99#issuecomment-52628719

When I run `dpkg -L pkg-config | grep m4` i get:
```
dpkg-query: package 'pkg-config' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
```
even though the macros are present at:
/usr/share/aclocal/pkg.m4

### Steps To Reproduce:

i guess trying to run `npm install` on the same environment as i described

**Comment by vs0uz4** [comment]
fixing the errors related to the libraries:
* gifsicle@3.0.4 -> Command failed: autoreconf -ivf (/ bin / sh: autoreconf: not found)
* mozjpeg@5.0.0 -> Command failed: autoreconf -fiv (/ bin / sh: autoreconf: not found)
* optipng-bin@3.1.4 -> Command failed: ./configure --with-system-zlib

I installed the packages `autoconf` and the errors were fixed. However, there is still a single error, regarding the "pngquant-bin".

```
> pngquant-bin@4.0.0 postinstall /var/www/app/node_modules/pngquant-bin
> node lib/install.js
 
  ⚠ spawn /var/www/app/node_modules/pngquant-bin/vendor/pngquant ENOENT
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/var/www/app/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ambientum/.npm/_logs/2018-04-08T12_21_28_740Z-debug.log
```

**Comment by b1alpha** [comment]
I am having the same issue with Centos 6

**Comment by yccheok** [comment]
Anyone has found a solution?

**Comment by nufaylr** [comment]
I had the same issue in Centos 6.9, manage to get away by run `npm install -f` with -force key..
