### ISSUE TITLE
TypeError: mix.extract / mix.js  is not a function

### ISSUE THREAD

**Issue by getchu** [JeffreyWay/laravel-mix#1592]
>npm run production

> @ production d:\PHP\pandora-front
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules

D:\PHP\pandora-front\webpack.mix.js:5
mix.extract(['vue-moment','babel-polyfill'])
    ^

TypeError: mix.extract is not a function
    at Object.<anonymous> (D:\PHP\pandora-front\webpack.mix.js:5:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (d:\PHP\pandora-front\webpack.config.js:9:1)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zdb\AppData\Roaming\npm-cache\_logs\2018-04-12T03_46_07_168Z-debug.log

**Comment by getchu** [comment]
npm version
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.11.1',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.50',
  zlib: '1.2.11' }

**Comment by getchu** [comment]
let mix = require('laravel-mix')
const CleanWebpackPlugin = require('clean-webpack-plugin') // 清除文件

// 公用库分离
mix.extract(['vue-moment','babel-polyfill'])

**Comment by getchu** [comment]
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules ",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules ",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot ",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules ",
    "prod-watch": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --watch --no-progress --hide-modules",
    "lint": "eslint --ext .js --ext .vue resources/assets/js/",
    "lint-fix": "eslint --fix --ext .js --ext .vue resources/assets/js/",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "axios": "^0.18",
    "babel-eslint": "^8.2.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-stage-2": "^6.24.1",
    "bootstrap": "^4.0.0",
    "bootstrap-sass": "^3.3.7",
    "clean-webpack-plugin": "^0.1.19",
    "cross-env": "^5.1",
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1",
    "eslint-friendly-formatter": "^4.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.2",
    "eslint-plugin-standard": "^3.0.1",
    "husky": "^0.14.3",
    "jquery": "^3.2",
    "laravel-mix": "^2.0.0",
    "less": "^3.0.1",
    "less-loader": "^4.0.6",
    "lodash": "^4.17.4",
    "node-sass": "^4.7.2",
    "popper.js": "^1.12",
    "sass-loader": "^6.0.7",
    "scss-loader": "^0.0.1",
    "vue": "^2.5.7",
    "vue-datetime-picker": "^0.2.1",
    "vue-moment": "^3.2.0",
    "vuejs-datepicker": "^0.9.26",
    "vuex": "^3.0.1",
    "webpack-bundle-analyzer": "^2.11.1",
    "xlsx": "^0.12.2"
  }
}

**Comment by getchu** [comment]
laravel 5.4

**Comment by getchu** [comment]
npm cache clean
