### ISSUE TITLE
Laravel Mix error start on Webpack v4

### ISSUE THREAD

**Issue by gusdecool** [JeffreyWay/laravel-mix#1601]
- Laravel Mix Version: 2.1.11 (`npm list --depth=0 | grep laravel-mix`)
- Node Version (`node -v`): v9.11.1
- Yarn Version (`yarn -v`): 1.6.0
- OS: OSX v10.13.4 (17E199)

### Description:
Starting from webpack version 4.0.0, laravel-mix started not working
If i using webpack version 3.11.0, it still working correctly

### Steps To Reproduce:

Here is command that i run on my local computer including the output
note: file project absolute directory have changed to `./` for privacy purpose 🙏 

```shell
$ yarn cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
yarn run v1.6.0
$ ./node_modules/.bin/cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
./node_modules/webpack-chunk-hash/index.js:22
      var source = chunk.modules.map(getModuleSource).sort(sortById).reduce(concatenateSource, '')
                                 ^

TypeError: Cannot read property 'map' of undefined
    at ./node_modules/webpack-chunk-hash/index.js:22:34
    at SyncHook.eval [as call] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.createHash (./node_modules/webpack/lib/Compilation.js:1701:25)
    at hooks.optimizeTree.callAsync.err (./node_modules/webpack/lib/Compilation.js:939:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (./node_modules/webpack/lib/Compilation.js:896:27)
    at hooks.make.callAsync.err (./node_modules/webpack/lib/Compiler.js:479:17)
    at _err0 (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (./node_modules/webpack/lib/Compilation.js:764:12)
    at processModuleDependencies.err (./node_modules/webpack/lib/Compilation.js:703:9)
    at process._tickCallback (internal/process/next_tick.js:176:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by ruchern** [comment]
Laravel Mix is not compatible with Webpack 4 yet. See #1495
