### ISSUE TITLE
Laravel Mix npm run dev error 

### ISSUE THREAD

**Issue by hosamalzagh** [JeffreyWay/laravel-mix#1623]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
----------------------
 npm list --depth=0
/home/nozom/public_html
├── autoprefixer@7.2.6 extraneous
├── axios@0.18.0
├── babel-core@6.26.3 extraneous
├── babel-loader@7.1.4 extraneous
├── babel-plugin-transform-object-rest-spread@6.26.0 extraneous
├── babel-plugin-transform-runtime@6.23.0 extraneous
├── babel-preset-env@1.6.1 extraneous
├── bootstrap@4.1.0
├── concatenate@0.0.2 extraneous
├── cross-env@5.1.4
├── css-loader@0.28.11 extraneous
├── dotenv@4.0.0 extraneous
├── dotenv-expand@4.2.0 extraneous
├── extract-text-webpack-plugin@3.0.2 extraneous
├── file-loader@0.11.2 extraneous
├── friendly-errors-webpack-plugin@1.7.0 extraneous
├── fs-extra@3.0.1 extraneous
├── html-loader@0.4.5 extraneous
├── imagemin@5.3.1 extraneous
├── imagemin-gifsicle@5.2.0 extraneous
├── imagemin-mozjpeg@7.0.0 extraneous
├── imagemin-optipng@5.2.1 extraneous
├── imagemin-svgo@6.0.0 extraneous
├── jquery@3.3.1
├── lodash@4.17.10
├── md5@2.2.1 extraneous
├── nice-try@1.0.4 extraneous
├── node-sass@4.9.0 extraneous
├── popper.js@1.14.3
├── postcss-loader@2.1.4 extraneous
├── resolve-url-loader@2.3.0 extraneous
├── sass-loader@6.0.7 extraneous
├── style-loader@0.18.2 extraneous
├── uglifyjs-webpack-plugin@1.2.5 extraneous
├── vue@2.5.16
├── vue-loader@13.7.1 extraneous
├── vue-template-compiler@2.5.16 extraneous
├── webpack@3.11.0 extraneous
├── webpack-chunk-hash@0.4.0 extraneous
├── webpack-dev-server@2.11.2 extraneous
├── webpack-merge@4.1.2 extraneous
└── webpack-notifier@1.6.0 extraneous

npm ERR! extraneous: autoprefixer@7.2.6 /home/nozom/public_html/node_modules/autoprefixer
npm ERR! extraneous: babel-core@6.26.3 /home/nozom/public_html/node_modules/babel-core
npm ERR! extraneous: babel-loader@7.1.4 /home/nozom/public_html/node_modules/babel-loader
npm ERR! extraneous: babel-plugin-transform-object-rest-spread@6.26.0 /home/nozom/public_html/node_modules/babel-plugin-transform-object-rest-spread
npm ERR! extraneous: babel-plugin-transform-runtime@6.23.0 /home/nozom/public_html/node_modules/babel-plugin-transform-runtime
npm ERR! extraneous: babel-preset-env@1.6.1 /home/nozom/public_html/node_modules/babel-preset-env
npm ERR! extraneous: concatenate@0.0.2 /home/nozom/public_html/node_modules/concatenate
npm ERR! extraneous: css-loader@0.28.11 /home/nozom/public_html/node_modules/css-loader
npm ERR! extraneous: dotenv@4.0.0 /home/nozom/public_html/node_modules/dotenv
npm ERR! extraneous: dotenv-expand@4.2.0 /home/nozom/public_html/node_modules/dotenv-expand
npm ERR! extraneous: extract-text-webpack-plugin@3.0.2 /home/nozom/public_html/node_modules/extract-text-webpack-plugin
npm ERR! extraneous: file-loader@0.11.2 /home/nozom/public_html/node_modules/file-loader
npm ERR! extraneous: friendly-errors-webpack-plugin@1.7.0 /home/nozom/public_html/node_modules/friendly-errors-webpack-plugin
npm ERR! extraneous: fs-extra@3.0.1 /home/nozom/public_html/node_modules/fs-extra
npm ERR! extraneous: html-loader@0.4.5 /home/nozom/public_html/node_modules/html-loader
npm ERR! extraneous: imagemin@5.3.1 /home/nozom/public_html/node_modules/imagemin
npm ERR! extraneous: imagemin-gifsicle@5.2.0 /home/nozom/public_html/node_modules/imagemin-gifsicle
npm ERR! extraneous: imagemin-mozjpeg@7.0.0 /home/nozom/public_html/node_modules/imagemin-mozjpeg
npm ERR! extraneous: imagemin-optipng@5.2.1 /home/nozom/public_html/node_modules/imagemin-optipng
npm ERR! extraneous: imagemin-svgo@6.0.0 /home/nozom/public_html/node_modules/imagemin-svgo
npm ERR! extraneous: md5@2.2.1 /home/nozom/public_html/node_modules/md5
npm ERR! extraneous: nice-try@1.0.4 /home/nozom/public_html/node_modules/nice-try
npm ERR! extraneous: node-sass@4.9.0 /home/nozom/public_html/node_modules/node-sass
npm ERR! extraneous: postcss-loader@2.1.4 /home/nozom/public_html/node_modules/postcss-loader
npm ERR! extraneous: resolve-url-loader@2.3.0 /home/nozom/public_html/node_modules/resolve-url-loader
npm ERR! extraneous: sass-loader@6.0.7 /home/nozom/public_html/node_modules/sass-loader
npm ERR! extraneous: style-loader@0.18.2 /home/nozom/public_html/node_modules/style-loader
npm ERR! extraneous: uglifyjs-webpack-plugin@1.2.5 /home/nozom/public_html/node_modules/uglifyjs-webpack-plugin
npm ERR! extraneous: vue-loader@13.7.1 /home/nozom/public_html/node_modules/vue-loader
npm ERR! extraneous: vue-template-compiler@2.5.16 /home/nozom/public_html/node_modules/vue-template-compiler
npm ERR! extraneous: webpack@3.11.0 /home/nozom/public_html/node_modules/webpack
npm ERR! extraneous: webpack-chunk-hash@0.4.0 /home/nozom/public_html/node_modules/webpack-chunk-hash
npm ERR! extraneous: webpack-dev-server@2.11.2 /home/nozom/public_html/node_modules/webpack-dev-server
npm ERR! extraneous: webpack-merge@4.1.2 /home/nozom/public_html/node_modules/webpack-merge
npm ERR! extraneous: webpack-notifier@1.6.0 /home/nozom/public_html/node_modules/webpack-notifier

---------------------
- Node Version (`node -v`): v8.11.1

- NPM Version (`npm -v`): 5.6.0

- OS: CENTOS 6.9

### Description:
> @ dev /home/nozom/public_html
> npm run development

> @ development /home/nozom/public_html
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/nozom/public_html/node_modules/laravel-mix/setup/webpack.config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/nozom/public_html/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/nozom/public_html/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/nozom/public_html/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/nozom/public_html/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/nozom/public_html/node_modules/yargs/yargs.js:533:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nozom/.npm/_logs/2018-04-30T09_06_40_505Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nozom/.npm/_logs/2018-04-30T09_06_40_515Z-debug.log

### Steps To Reproduce:

https://github.com/JeffreyWay/laravel-mix/issues/1072

Clean Laravel Installation (
composer create-project laravel/laravel webinterface)

run: composer install
run: npm install
run: npm run dev

or
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install

**Comment by hosamalzagh** [comment]
npm bugs pngquant-bin
npm ERR! path xdg-open
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn xdg-open
npm ERR! enoent spawn xdg-open ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nozom/.npm/_logs/2018-04-30T09_16_25_454Z-debug.log

**Comment by hosamalzagh** [comment]
i fixed by this answer 
https://forum.newhob.com/showthread.php?t=255058
