### ISSUE TITLE
Mix replaces ts-loader 3.1 with incompatible 4.3.0 version?

### ISSUE THREAD

**Issue by roddypratt** [JeffreyWay/laravel-mix#1637]
- Laravel Mix Version: 2.1.11
- WebPack 3.12.0
- Node 10.1.0
- Yarn 1.6.0
- OS: Windows 10 X64

### Description:

Mix updates ts-loader to an incompatible version.

### Details

My package.json contains a devDependency for ts-loader ^3.1.1.  I can't use the 4.x version of [ts-loader ](https://github.com/TypeStrong/ts-loader) because that requires Webpack 4 -  [which isn't supported by Mix yet.](https://github.com/JeffreyWay/laravel-mix/pull/1495)

When I build using Mix, I see the message:-

> Additional dependencies must be installed. This will only take a moment.

My package.json gets changed to "ts-loader": "^4.3.0", and of course, the build fails 

> Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
>     at successfulTypeScriptInstance (C:\entre2\node_modules\ts-loader\dist\instances.js:167:28)
>     at Object.getTypeScriptInstance (C:\entre2\node_modules\ts-loader\dist\instances.js:51:12)

TBH, I have no idea if this is a problem in Mix, WebPack, Node or ts-loader. I'm posting it here initially because I can't see why Mix should be trying to upgrade a module that's already present.

**Comment by roddypratt** [comment]
Resolved. Somehow NODE-ENV had stopped being 'development' which meant that ts-loader  - while in  dev-dependencies was actually missing from node_modules. until Webpack ran.
