### ISSUE TITLE
npm run production always fails

### ISSUE THREAD

**Issue by Jatapiaro** [JeffreyWay/laravel-mix#1648]
I got the following error

```
ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/lib/loader.js??ref--8-5!./resources/assets/sass/app.scss
Module build failed:
    },
    ^
      Invalid CSS after "    }": expected selector, was ","
      in /Users/jacobotapia/Desktop/goal-site/resources/assets/sass/layout/_navbar.scss (line 70, column 6)
 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed:
    },
    ^
      Invalid CSS after "    }": expected selector, was ","
      in /Users/jacobotapia/Desktop/goal-site/resources/assets/sass/layout/_navbar.scss (line 70, column 6)
    at runLoaders (/Users/jacobotapia/Desktop/goal-site/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/jacobotapia/Desktop/goal-site/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/jacobotapia/Desktop/goal-site/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/jacobotapia/Desktop/goal-site/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/jacobotapia/Desktop/goal-site/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/jacobotapia/Desktop/goal-site/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/jacobotapia/Desktop/goal-site/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

Does someone knows what is hppening?

**Comment by BrekiTomasson** [comment]
Could you show me lines 60 to 80 in your `resources/assets/sass/layout/_navbar.scss` ? Looks like there's a problem around there.
