### ISSUE TITLE
webpack-notifier: After first `watch` run TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by haithamAth** [JeffreyWay/laravel-mix#1654]
- Laravel Mix Version: 2.1.11
- Node Version: 10.1.0
- NPM Version: 5.6.0
- OS: Linux (Ubuntu 18.04)

### Description:
When I run `npm run dev` or `npm run prod` everything works fine.
But when I do `npm run watch` it compiles normally first time, but after any of watched files changed and the wepack start compiling again, at the moment it reaches **95% emitting** I get this error

![image](https://user-images.githubusercontent.com/6568494/40576786-c2472ec8-6104-11e8-9346-7731689bee61.png)

The project is using large amount of javascript libraries and dependencies, this is the output of `npm list --depth=0`

> /var/www/kangaroo_laravel
> ├── @ fortawesome/fontawesome@1.1.8
> ├── @ fortawesome/fontawesome-free-brands@5.0.13
> ├── @ fortawesome/fontawesome-free-regular@5.0.13
> ├── @ fortawesome/fontawesome-free-solid@5.0.13
> ├── animate.css@3.6.1
> ├── axios@0.18.0
> ├── bootstrap@4.1.1
> ├── bootstrap-confirmation2@4.0.0
> ├── bootstrap-select@1.13.1
> ├── bootstrap-v4-rtl@4.0.0-0
> ├── cross-env@5.1.6
> ├── datatables.net-bs4@1.10.16
> ├── datatables.net-buttons-bs4@1.5.1
> ├── datatables.net-responsive-bs4@2.2.1
> ├── datatables.net-select-bs4@1.2.5
> ├── daterangepicker@3.0.3
> ├── icheck@1.0.2
> ├── jquery@3.3.1
> ├── jquery-ui@1.12.1
> ├── jquery.cookie@1.4.1
> ├── ladda@2.0.1
> ├── laravel-mix@2.1.11
> ├── linearicons@1.0.1
> ├── lodash@4.17.10
> ├── malihu-custom-scrollbar-plugin@3.1.5
> ├── mkdirp@0.5.1
> ├── modernizr@3.6.0
> ├── node-pre-gyp@0.10.0
> ├── noty@3.2.0-beta
> ├── octicons@7.3.0
> ├── popper.js@1.14.3
> ├── simple-line-icons@2.4.1
> ├── slick-carousel@1.8.1
> ├── vue@2.5.16
> └── weather-icons@1.3.2
> 
> npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
> npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
> npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
> npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
> npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
> npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
> npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
> npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
> npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
> npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
> npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
> npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
> npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
> npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
> npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
> npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
> npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
> npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
> npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
> npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
> npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
> npm ERR! missing: once@1.4.0, required by glob@7.1.2
> npm ERR! missing: once@1.4.0, required by inflight@1.0.6
> npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
> npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
> npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
> npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
> npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
> npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
> npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
> npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
> npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
> npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
> npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
> npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
> npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
> 

### The Error:
> /var/www/kangaroo_laravel/node_modules/webpack-notifier/index.js:42
>     if (error.module && error.module.rawRequest)
>               ^
> 
> TypeError: Cannot read property 'module' of undefined
>     at module.exports.WebpackNotifierPlugin.compileMessage (/var/www/kangaroo_laravel/node_modules/webpack-notifier/index.js:42:15)
>     at module.exports.WebpackNotifierPlugin.compilationDone (/var/www/kangaroo_laravel/node_modules/webpack-notifier/index.js:57:20)
>     at Compiler.applyPlugins (/var/www/kangaroo_laravel/node_modules/tapable/lib/Tapable.js:61:14)
>     at Watching._done (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:105:17)
>     at compiler.emitRecords.err (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:79:19)
>     at Compiler.emitRecords (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:371:38)
>     at compiler.emitAssets.err (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:62:20)
>     at applyPluginsAsyncSeries1.err (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:364:12)
>     at next (/var/www/kangaroo_laravel/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/var/www/kangaroo_laravel/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/var/www/kangaroo_laravel/node_modules/tapable/lib/Tapable.js:222:13)
>     at Compiler.afterEmit (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:361:9)
>     at require.forEach.err (/var/www/kangaroo_laravel/node_modules/webpack/lib/Compiler.js:350:15)
>     at /var/www/kangaroo_laravel/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/var/www/kangaroo_laravel/node_modules/async/dist/async.js:1064:13)
>     at /var/www/kangaroo_laravel/node_modules/async/dist/async.js:969:16
>     at /var/www/kangaroo_laravel/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:152:20)

### nodejs log:
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'development',
> 1 verbose cli   '--',
> 1 verbose cli   '--watch' ]
> 2 info using npm@5.6.0
> 3 info using node@v10.1.0
> 4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
> 5 info lifecycle @~predevelopment: @
> 6 info lifecycle @~development: @
> 7 verbose lifecycle @~development: unsafe-perm in lifecycle true
> 8 verbose lifecycle @~development: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/kangaroo_laravel/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/kangaroo_laravel/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle @~development: CWD: /var/www/kangaroo_laravel
> 10 silly lifecycle @~development: Args: [ '-c',
> 10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"' ]
> 11 silly lifecycle @~development: Returned: code: 1  signal: null
> 12 info lifecycle @~development: Failed to exec development script
> 13 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
> 13 verbose stack     at EventEmitter.emit (events.js:182:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:182:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:957:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
> 14 verbose pkgid @
> 15 verbose cwd /var/www/kangaroo_laravel
> 16 verbose Linux 4.15.0-20-generic
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "development" "--" "--watch"
> 18 verbose node v10.1.0
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
> 22 error Exit status 1
> 23 error Failed at the @ development script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by alexisgahon** [comment]
J'utilise la dernière version de Node (10.4) et de npm (6.1.0) et j'ai le même problème.

**Comment by alexisgahon** [comment]
OS: MacOS
Node: 10.4.0
Npm: 6.1.0
Webpack: 3.12
LaravelMix: 2.1.11

Le problème semble arriver uniquement pour la recompilation des fichiers sass (pas de soucis pour les modifications sur le js)

```shell
 95% emitting

 WARNING  Compiled with 0 warnings                                                                                                                                                                                                                                    1:32:28 PM

/Users/xxx/Projects/xxx/website/node_modules/webpack-notifier/index.js:42
    if (error.module && error.module.rawRequest)
              ^

TypeError: Cannot read property 'module' of undefined
    at module.exports.WebpackNotifierPlugin.compileMessage (/Users/xxx/Projects/xxx/website/node_modules/webpack-notifier/index.js:42:15)
```

**Comment by wvdongen** [comment]
I've got the same issue:
windows 10
npm 6.2.0
node v10.8.0
LaravelMix: 2.1.11

**Comment by wvdongen** [comment]
Temporary fix that works for me is to add the following to `node_modules\webpack-notifier\index.js` on line 41,

```
   if (error == null) {
        return;
    }
```

**Comment by maroparo** [comment]
Same here ... any news on this ?

**Comment by tetshi** [comment]
Same issue here.

**Comment by asologor** [comment]
So a lot of people have this issue and it's closed?

My case:
```
 WAIT  Compiling...                                                                                                              1:27:01 PM

 95% emitting                                                
                      
 WARNING  Compiled with 0 warnings

/.../node_modules/webpack-notifier/index.js:42
    if (error.module && error.module.rawRequest)
              ^
```

`WARNING  Compiled with 0 warnings` - well done

**Comment by goper-leo** [comment]
In my case I've added `width: -webkit-fill-available` on my scss. After I remove it I remove it work back.

**Comment by jaguerra2017** [comment]
hi guys, i want to share that in my case (DON'T UNDERSTAND WHY) was caused by this property
```
justify-content: end;
```
and curiously by the ``end`` value, removing the property or changing the value let's say to ``space-between`` or ``flex-end`` then all good
i hope that can help somebody, just sharing recent experience with this error
