### ISSUE TITLE
import image error

### ISSUE THREAD

**Issue by zhou0818** [JeffreyWay/laravel-mix#1690]
Error Occurs When I Import an Image File in a vue File
`import avatar from '../images/avatar.png'`

ERROR in ./resources/assets/images/error-page/default_avatar.png
Module build failed: Error: ϵͳ�Ҳ���ָ����·����

    at notFoundError (C:\Users\zhou\Code\landuiCMS\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\zhou\Code\landuiCMS\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\zhou\Code\landuiCMS\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
 @ ./resources/assets/js/app.js 10:0-47
 @ multi ./resources/assets/js/app.js ./resources/assets/less/app.less

Only svg is error free, png and jpg are wrong.
I have not modified webpackconfig。

**Comment by ankurk91** [comment]
Disable image optimization
```js
mix.options({
  imgLoaderOptions: {
    enabled: false
  },
});

```
