### ISSUE TITLE
Run production error in Ubuntu 17.10, Node 8.11.3 and NPM 5.6.0

### ISSUE THREAD

**Issue by xarasbir** [JeffreyWay/laravel-mix#1697]
- Laravel Mix Version: 2.1.11
- Node Version: 8.11.3 
- NPM Version: 5.6.0 
- OS: Ubuntu 17.10 x64

### Description:
Everytime I run `npm run production` it throws an error. `npm run development` and `npm run watch` is fine.
Can't figure out what's causing the error.

I've tried nuking the `node_modules`, updating laravel-mix, and installing everything again but no luck.

The webpack.mix.js looks pretty straight forward : 
```
let mix = require('laravel-mix'); 
mix.js('resources/assets/js/app.js', 'public/js').sass('resources/assets/sass/app.scss', 'public/css') 
    .webpackConfig({
        node: {
            fs: 'empty'
        }
    }); 
```

package.json : 

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "gulp": "^4.0.0",
        "gulp-file-include": "^2.0.1",
        "gulp-watch": "^5.0.0",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.10",
        "popper.js": "^1.12",
        "vue": "^2.5.7"
    },
    "dependencies": {
        "clipboard": "^2.0.1",
        "instascan": "^1.0.0",
        "laravel-echo": "^1.4.0",
        "moment": "^2.22.1",
        "socket.io-client": "^2.1.1",
        "vue-infinite-scroll": "^2.0.2",
        "vue-router": "^3.0.1",
        "vuex": "^3.0.1"
    }
}
```

I've checked the log and it is not helpful :  
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'production' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle @~preproduction: @
6 info lifecycle @~production: @
7 verbose lifecycle @~production: unsafe-perm in lifecycle true
8 verbose lifecycle @~production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/site1/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/l$
9 verbose lifecycle @~production: CWD: /var/www/site1
10 silly lifecycle @~production: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~production: Returned: code: 1  signal: null
12 info lifecycle @~production: Failed to exec production script
13 verbose stack Error: @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /var/www/site1
16 verbose Linux 4.13.0-45-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "production"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by xarasbir** [comment]
Run through my code and double checked everything and found out that [Instascan](https://github.com/schmich/instascan). I don't know what's in it that's causing the error but I've decided to place it in a different external javascript.
