### ISSUE TITLE
Error: not found: git

### ISSUE THREAD

**Issue by ForzaSFerrari** [JeffreyWay/laravel-mix#171]
With Laravel 5.4 I installed a new Laravel and copied the files of my biggest application (Laravel 5.3) to the new one.

Now I try to install Laravel Mix, but I can't do it because of an error.

```
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:112:15)
npm WARN addRemoteGit  git://github.com/stephenmathieson/node-globs.git#master resetting remote C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-stephenmathieson-node-globs-git-master-8a28a49b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
npm WARN addRemoteGit     at F (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
npm WARN addRemoteGit     at E (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/stephenmathieson/node-globs.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-stephenmathieson-node-globs-git-
master-8a28a49b: undefined
npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/stephenmathieson/node-globs.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-stephenmathieson-node-globs-git-
master-8a28a49b: undefined
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\domains\application\www\npm-debug.log
```

Everything what I can say I installed Laravel with Git Bash.

Where's the error or what I doing wrong?

**Comment by JeffreyWay** [comment]
You have to install Git on your machine.

**Comment by ForzaSFerrari** [comment]
Are you kidding me? Git is on Version 2.11.0 and I get this error.

**Comment by JeffreyWay** [comment]
Sorry - it says "Git not found." Of course that's going to be my first instinct.

You're going to need to give me a lot more information and specifics then. I don't see anything in that output that looks like Laravel Mix files.

**Comment by ForzaSFerrari** [comment]
Which kind of information do you need? This is the first time that I have an issue with Laravel Elixir/Mix. Because it was changed I use the Installation workflow and get the error after ```npm install```

**Comment by adriaanzon** [comment]
Are you sure git is in your PATH?

Anyway, I see in the log that it fails to clone `git://github.com/stephenmathieson/node-globs.git`. Bumping the `concatenate` dependency to 0.0.2 should fix this, as it contains this commit: https://github.com/stephenmathieson/node-concatenate/commit/da2cba5a43992c5d19d51b36c557437a9839c7c7. I'll send out a pull request for that.

**Comment by ForzaSFerrari** [comment]
Yes, I'm sure because now node_modules will be shown in the file system but it will be not shown in phpStorm. 

If I want to run Mix with ```npm run dev``` or ```npm run changes``` now. I'm getting 'The command "node_modules" is either misspelled or could not be found.'
