### ISSUE TITLE
Additional dependencies aren’t installed when running `npm run production`

### ISSUE THREAD

**Issue by bradlc** [JeffreyWay/laravel-mix#1728]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): v9.11.1
- NPM Version (`npm -v`): 5.6.0
- OS: macOS 10.13.5 (High Sierra)

### Description:
When using extensions that require additional dependencies (e.g. `mix.react()`) these are not installed when running `npm run production` or `npm run prod`. It works fine when running `npm run development`.

### Steps To Reproduce:
1. Run `npm install` on a fresh Laravel install
1. Update mix config to use `mix.react()`
1. Run `npm run production`

#### Output:

```
> @ production /Users/brad/Code/mix-test
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Additional dependencies must be installed. This will only take a moment.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.



 ERROR  Failed to compile with 1 errors                                                                                                                                        19:19:15

 error  in ./resources/assets/js/app.js

Module build failed: Error: Couldn't find preset "react" relative to directory "/Users/brad/Code/mix-test/resources/assets/js"
    at /Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/brad/Code/mix-test/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/brad/Code/mix-test/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/brad/Code/mix-test/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)

 @ multi ./resources/assets/js/app.js

     Asset     Size  Chunks             Chunk Names
/js/app.js  2.07 kB       0  [emitted]  /js/app

ERROR in ./resources/assets/js/app.js
Module build failed: Error: Couldn't find preset "react" relative to directory "/Users/brad/Code/mix-test/resources/assets/js"
    at /Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/brad/Code/mix-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/brad/Code/mix-test/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/brad/Code/mix-test/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/brad/Code/mix-test/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:434:13)
 @ multi ./resources/assets/js/app.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brad/.npm/_logs/2018-08-04T18_19_15_747Z-debug.log
```

**Comment by bradlc** [comment]
This is because npm won’t install dev dependencies if `NODE_ENV` is `production`. I have submitted a [PR which fixes this](https://github.com/JeffreyWay/laravel-mix/pull/1729).
