### ISSUE TITLE
Production build. TypeError: Cannot read property 'replace' of undefined.

### ISSUE THREAD

**Issue by Sogl** [JeffreyWay/laravel-mix#1733]
- Laravel Mix Version: 2.1.11
- Node Version (`node -v`): 10.8.0
- NPM Version (`npm -v`): 6.2.0
- OS: Linux 4.9.93-linuxkit-aufs x86_64 (Alpine 6.4.0 Docker container)

### Description:

Command `yarn run watch` works fine.

After `yarn run production`:
```js
laradock@eb3941736846:/var/www/sogl$ yarn run production
yarn run v1.9.4
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
/var/www/sogl/node_modules/laravel-mix/src/components/Combine.js:34
            output = src.replace(/\.([a-z]{2,})$/i, '.min.$1');
                         ^

TypeError: Cannot read property 'replace' of undefined
    at Combine.register (/var/www/sogl/node_modules/laravel-mix/src/components/Combine.js:34:26)
    at Api.mix.(anonymous function).args [as minify] (/var/www/sogl/node_modules/laravel-mix/src/components/ComponentFactory.js:98:53)
    at Object.<anonymous> (/var/www/sogl/webpack.mix.js:21:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How to fix?

**Comment by ankurk91** [comment]
To clarify

```js
mix.minify('path/file.js')
```
method requires file path as first parameter

https://github.com/JeffreyWay/laravel-mix/blob/master/docs/concatenation-and-minification.md
