### ISSUE TITLE
Compiler error: `ERROR in ./node_modules/vue-loader/lib/template-compiler`

### ISSUE THREAD

**Issue by tom-coward** [JeffreyWay/laravel-mix#1740]
- Laravel Mix Version: 2.1.11
- Node Version: 10.8.0
- NPM Version: 6.2.0
- OS: MacOS Mojave Beta

### Description:
Fails to compile assets using `npm run dev` command, with the following npm error:
```
ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-3b04a227","hasScoped":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./resources/assets/js/components/manager/AccountSettings.vue
Module build failed: SyntaxError: Unexpected token (1:2889)
    at Parser.pp$4.raise (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2610:13)
    at Parser.pp.unexpected (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:637:8)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2154:49)
    at Parser.pp$3.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2061:41)
    at Parser.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parsePropertyValue (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2310:87)
    at Parser.parseObj (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:4472:14)
    at Parser.pp$3.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2077:17)
    at Parser.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parsePropertyValue (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2310:87)
    at Parser.parseObj (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:4472:14)
    at Parser.pp$3.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2077:17)
    at Parser.parseExprAtom (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
    at Parser.pp$3.parseExprList (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:2528:20)
    at Parser.pp$3.parseSubscripts (/Users/tomcoward/VB/versobit/node_modules/vue-template-es2015-compiler/buble.js:1983:29)
 @ ./resources/assets/js/components/manager/AccountSettings.vue 6:23-277
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
```

### Steps To Reproduce:
Run `npm run dev`

**Comment by kmark** [comment]
Hey @tom-coward,

If you do the following do you still get the same error?

1. composer self-update
2. composer global upgrade
3. laravel new testmix
4. cd testmix
5. npm install
6. npm run dev

**Comment by pzoechner** [comment]
I repeatedly get the same error message when I leave a PHP arrow in a `v-bind:`.

**Comment by gbrits** [comment]
I had an empty `v-model=""` that caused this issue. Just double-check all your syntax is accurate if you run into this sort of issue.
