### ISSUE TITLE
Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by syclone** [JeffreyWay/laravel-mix#1750]
- Laravel Mix Version: 2.1.14 (`npm list --depth=0`)
- Node Version (`node -v`): v8.11.4
- NPM Version (`npm -v`):  5.6.0
- OS: Windows 10

### Description:

With a fresh project of Laravel 5.6 run : `npm install`

package.json
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.18.0",
        "bootstrap": "^4.1.3",
        "popper.js": "^1.14.4",
        "cross-env": "^5.2",
        "jquery": "^3.3",
        "laravel-mix": "2.1.14",
        "lodash": "^4.17.10",
        "vue": "^2.5.17"
    }
}
```

I get the following error message.

> 
> node-sass@4.9.3 install 
> node scripts/install.js
> 
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'object-assign'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> 
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
> npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN img-loader@3.0.0 requires a peer of imagemin@^5.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.9.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!    Roaming\npm-cache\_logs\2018-08-26T04_06_56_868Z-debug.log
> 
> Process finished with exit code 1
>

**Comment by syclone** [comment]
This seems to be an issue with **node-sass** that affect laravel-mix
