### ISSUE TITLE
Help: mocha-webpack is creating weird `bundle.js` in `mix-manifest.json` which it then doesn't find?

### ISSUE THREAD

**Issue by JoeSchr** [JeffreyWay/laravel-mix#1779]
- Laravel Mix Version: 2.1.14
- Node Version (`node -v`): 10.2.1
- NPM Version (`npm -v`):  5.6.0
- YARN Version (which I use mostly): 1.10.1 
- OS: Windows 10

### Description:
Hello, I need help with setting up vue unittests via mocha & except (according to the laracast episode). 
I did the prerequisites above, didn't help.

My issue is, all package.json script e.g. `watch, build, dev` work as expected, but when I'm using mocha-webpack, something goes wrong. 
I narrowed it done, that it tries to create a `bundle.js` file in the `mix-manifest.json` but then doesn't find it. Usually my `mix-manifest.json` looks like this:
(run with ` "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
`)
```
{
    "/js/clearing-app.js": "/js/clearing-app.js?id=d70e7f37fb7e71160773",
    "/css/boilerplate.css": "/css/boilerplate.css?id=aa56e9c1733970c53d93",
    "/css/clearing-app.css": "/css/clearing-app.css?id=ae468bfa9ccb8eececc2"
}
```
after running it with `    "test-js": "cross-env NODE_ENV=testing mocha-webpack --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require tests/Vue/setup.js tests/Vue/**/*.spec.js"`

it looks like this:
```
{
    "/bundle.js": "/bundle.js"
}
```

and `yarn test-js` gives this error:
```

  [===                      ] 10% (building modules)

 DONE  Compiled successfully in 49ms                                                                            13:44:28

fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\__Work\development\apps\ambulanz-timetracker\public\bundle.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at File.read (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\File.js:166:19)
    at File.version (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\File.js:175:25)
    at Manifest.hash (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\Manifest.js:52:65)
    at manifest.forEach.file (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\webpackPlugin
s\CustomTasksPlugin.js:76:47)
    at Array.forEach (<anonymous>)
    at CustomTasksPlugin.applyVersioning (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\w
ebpackPlugins\CustomTasksPlugin.js:76:18)
    at Compiler.compiler.plugin.stats (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\webp
ackPlugins\CustomTasksPlugin.js:12:22)
    at Compiler.applyPlugins (C:\__Work\development\apps\ambulanz-timetracker\node_modules\tapable\lib\Tapable.js:61:14)
    at emitRecords.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:264:11)
    at Compiler.emitRecords (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:371:38
)
    at emitAssets.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.j
s:364:12)
    at next (C:\__Work\development\apps\ambulanz-timetracker\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\performance\Si
zeLimitsPlugin.js:99:4)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
^ This was run without any *.spec.js, with *.spec.js it says this, maybe this hints to a different problem source?
```
 WEBPACK  Compiling...

  [===                      ] 11% (building modules)

 ERROR  Failed to compile with 1 errors                                                                         13:46:57

 error  in ./resources/assets/js/frontend/components/HelloWorld.vue

Module build failed: TypeError: Super expression must either be null or a function
    at _inherits (C:\__Work\development\apps\ambulanz-timetracker\node_modules\prettier\index.js:1945:11)
    at C:\__Work\development\apps\ambulanz-timetracker\node_modules\prettier\index.js:32893:5
    at C:\__Work\development\apps\ambulanz-timetracker\node_modules\prettier\index.js:32913:4
    at createCommonjsModule (C:\__Work\development\apps\ambulanz-timetracker\node_modules\prettier\index.js:181:35)
    at Object.<anonymous> (C:\__Work\development\apps\ambulanz-timetracker\node_modules\prettier\index.js:32885:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object._module2.default._extensions.(anonymous function) [as .js] (C:\__Work\development\apps\ambulanz-timetracke
r\node_modules\mocha-webpack\lib\util\registerRequireHook.js:140:62)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\__Work\development\apps\ambulanz-timetracker\node_modules\vue-loader\lib\template-compiler
\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)

 @ ./resources/assets/js/frontend/components/HelloWorld.vue 10:23-271
 @ ./tests/Vue/HelloWorld.spec.js
 @ ./node_modules/mocha-webpack/lib/entry.js

fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\__Work\development\apps\ambulanz-timetracker\public\bundle.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at File.read (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\File.js:166:19)
    at File.version (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\File.js:175:25)
    at Manifest.hash (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\Manifest.js:52:65)
    at manifest.forEach.file (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\webpackPlugin
s\CustomTasksPlugin.js:76:47)
    at Array.forEach (<anonymous>)
    at CustomTasksPlugin.applyVersioning (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\w
ebpackPlugins\CustomTasksPlugin.js:76:18)
    at Compiler.compiler.plugin.stats (C:\__Work\development\apps\ambulanz-timetracker\node_modules\laravel-mix\src\webp
ackPlugins\CustomTasksPlugin.js:12:22)
    at Compiler.applyPlugins (C:\__Work\development\apps\ambulanz-timetracker\node_modules\tapable\lib\Tapable.js:61:14)
    at emitRecords.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:264:11)
    at Compiler.emitRecords (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:371:38
)
    at emitAssets.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\Compiler.j
s:364:12)
    at next (C:\__Work\development\apps\ambulanz-timetracker\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\__Work\development\apps\ambulanz-timetracker\node_modules\webpack\lib\performance\Si
zeLimitsPlugin.js:99:4)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
How can I fix this or rightly configure it? I'm out of my depth and would be very grateful for any pointers in the right directions?

**Comment by JeffreyWay** [comment]
Sorry guys, I don’t have any familiarity with mocha-webpack. Might be worth checking with them instead. Otherwise, I need a minimal number of steps to reproduce the problem in a fresh app.

**Comment by ridaamirini** [comment]
#1404
