### ISSUE TITLE
sourceMaps() generate error when running npm run prod

### ISSUE THREAD

**Issue by AngyNoT** [JeffreyWay/laravel-mix#1787]
- Laravel Mix Version: 2.1.14 (`npm list --depth=0`)
- Node Version (`node -v`): v10.10.0
- NPM Version (`npm -v`): v6.4.1
- OS: Ubuntu 18.04

### Description:

Hello everyone, opening this issue because I can't fix an error which bothers me 

Whenever I try to run `npm run production` on my server (which works perfectly on my mac) I get the following error : 
```
> @ production /var/www/mywebsite.com/html
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-10-12T22_44_00_615Z-debug.log
```

Here's the debug file content : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'production' ]
2 info using npm@6.4.1
3 info using node@v10.10.0
4 verbose run-script [ 'preproduction', 'production', 'postproduction' ]
5 info lifecycle @~preproduction: @
6 info lifecycle @~production: @
7 verbose lifecycle @~production: unsafe-perm in lifecycle true
8 verbose lifecycle @~production: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/mywebsite.com/html/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~production: CWD: /var/www/mywebsite.com/html
10 silly lifecycle @~production: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~production: Returned: code: 1  signal: null
12 info lifecycle @~production: Failed to exec production script
13 verbose stack Error: @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @
15 verbose cwd /var/www/mywebsite.com/html
16 verbose Linux 4.15.0-36-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "production"
18 verbose node v10.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Here's my package.json : 
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "lint-fix": "./node_modules/eslint/bin/eslint.js  --ext .vue ./resources/assets/js --cache --fix",
        "lint": "./node_modules/eslint/bin/eslint.js --ext .vue ./resources/assets/js --cache"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-free": "^5.3.1",
        "axios": "^0.18",
        "cross-env": "^5.1",
        "eslint": "^5.6.0",
        "eslint-config-standard": "^12.0.0",
        "eslint-loader": "^2.1.1",
        "eslint-plugin-import": "^2.14.0",
        "eslint-plugin-node": "^7.0.1",
        "eslint-plugin-promise": "^4.0.1",
        "eslint-plugin-standard": "^4.0.0",
        "eslint-plugin-vue": "^5.0.0-beta.3",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "lodash": "^4.17.5",
        "materialize-css": "^1.0.0",
        "popper.js": "^1.12",
        "vue": "^2.5.7",
        "vue-template-compiler": "^2.5.17"
    },
  "dependencies": {
    "ajv": "^6.5.4",
    "cors": "^2.8.4",
    "imagemin": "^5.3.1"
  }
}
```

After trying many things, I finally found out that the problem was with .sourceMaps() in webpack.mix.js : 
```
let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
    .sourceMaps();


mix.webpackConfig({
    module: {
        rules: [
            {
                enforce: 'pre',
                test: /\.(vue)$/,
                loader: 'eslint-loader',
                exclude: /node_modules/
            }
        ]
    }
});
```

If I remove .sourceMaps(); npm run production works.

I remember reading that sourceMaps were disabled when running npm run production, am I doing something wrong?

**Comment by ankurk91** [comment]
```
mix.sourceMaps(false);
```
You can disable source maps for production

**Comment by AngyNoT** [comment]
Thank you for the answer!

Is that in any documentation?

**Comment by AngyNoT** [comment]
It seems that the source of documentation does not have any mention of .sourceMaps() 

I could find something about it in Laravel's documentation but the false parameter is never mentionned : 

```
Source Maps
Though disabled by default, source maps may be activated by calling the mix.sourceMaps() method in your webpack.mix.js file. Though it comes with a compile/performance cost, this will provide extra debugging information to your browser's developer tools when using compiled assets.

mix.js('resources/js/app.js', 'public/js')
   .sourceMaps();
```

Is that a recent feature?
