### ISSUE TITLE
Got Error when run "npm run dev"

### ISSUE THREAD

**Issue by SamXiao** [JeffreyWay/laravel-mix#180]
Got 
`
> @ dev /usr/local/apache2/htdocs/bright-tech/seed-projects
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
/usr/local/apache2/htdocs/bright-tech/seed-projects/node_modules/laravel-mix/setup/webpack.config.js:120
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/usr/local/apache2/htdocs/bright-tech/seed-projects/node_modules/webpack/bin/convert-argv.js:96:18)
    at /usr/local/apache2/htdocs/bright-tech/seed-projects/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
`
when I run "npm run dev"

I installed laravel5.4 by "composer create-project --prefer-dist laravel/laravel ..."
and all composer, node library.

**Comment by QWp6t** [comment]
Update node
