### ISSUE TITLE
NPM Run Dev error Chunk.endpoint

### ISSUE THREAD

**Issue by codolloR** [JeffreyWay/laravel-mix#1822]
Hi

I have been getting the issue below for a while. I have followed the steps in installation and reinstalled.

I have ran these: 

`rm -rf node_modules` 
`npm cache clear`
`npm install`

- Node Version : 11.2.0 
- NPM Version: 6.4.1 
- OS: Mac OS 10.13.6

`├── @babel/core@7.1.6 `
`├── ajv@6.5.5 `
`├── @babel/preset-env@7.1.6 `
`├── axios@0.15.3 `
`├── babel-core@6.26.3`
`├── babel-loader@8.0.4 `
`├── babel-preset-env@1.7.0`
`├── bootstrap-sass@3.3.7`
`├── browser-sync@2.26.3`
`├── browser-sync-webpack-plugin@2.2.2` 
`├──cross-env@5.2.0`
`├── extract-text-webpack-plugin@4.0.0-beta.0`
`├── imagemin@6.0.0`
`├── img-loader@3.0.1`
`├── jquery@3.3.1`
`├── laravel-mix@2.1.14`
`├── lodash@4.17.11`
`├── sass-loader@7.1.0`
`├── vue@2.5.17`
`├── webpack@4.26.0`
`├── webpack-cli@3.1.2`
`├── webpack-dev-server@3.1.10`

```
 "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },

```

### Description:

```
78% module and chunk tree optimization unnamed compat plugin/Users/me/repos/duty/node_modules/webpack/lib/Chunk.js:846
                throw new Error(
                ^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/Users/me/repos/duty/node_modules/webpack/lib/Chunk.js:846:9)
    at /Users/me/repos/duty/node_modules/laravel-mix/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /Users/me/repos/duty/node_modules/laravel-mix/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/me/repos/duty/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/me/repos/duty/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/me/repos/duty/node_modules/webpack/lib/Compilation.js:1242:27)
    at hooks.make.callAsync.err (/Users/me/repos/duty/node_modules/webpack/lib/Compiler.js:546:17)
    at _done (eval at create (/Users/me/repos/duty/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err0 (eval at create (/Users/me/repos/duty/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:22)
    at _addModuleChain (/Users/me/repos/duty/node_modules/webpack/lib/Compilation.js:1093:12)
    at processModuleDependencies.err (/Users/me/repos/duty/node_modules/webpack/lib/Compilation.js:1005:9)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! duty@1.0.0 dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
```

### Steps To Reproduce:

Not sure how to recommend recreating steps, but I have reinstalled node, updated everything related to laravel and laravel-mix. 

### Update

Since getting the issue I completely removed node_module globally. Still got same issue.
fresh install of node_module and `npn install` on dev
Changed the package.json to Laravel Github version ran `npn install`, all worked!

**Comment by ankurk91** [comment]
Why you are using webpack v4?
Mix does not support v4.

**Comment by codolloR** [comment]
I didn't see that anywhere on the installation info, but thank you for letting me know. I was using Webpack 4 for another project.
