### ISSUE TITLE
Laravel Mix v4.0.0 Compile Issue

### ISSUE THREAD

**Issue by HDVinnie** [JeffreyWay/laravel-mix#1846]
-   Laravel Mix Version: laravel-mix@4.0.0
-   Node Version: v8.14.0
-   NPM Version: 6.4.1
-   OS: Ubuntu 18.04

### Description:
Upgrading to Laravel Mix breaks compiling.

### Steps To Reproduce:
Upgrade to Laravel Mix v4.0.0
Try Running `npm run prod`

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                    17:36:07

 error  in ./resources/sass/app.scss

Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }
    at <anonymous>


 error  in ./resources/sass/app.scss

Syntax Error: SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }



 @ ./resources/sass/app.scss 2:14-254

         Asset      Size  Chunks             Chunk Names
/js/twostep.js  3.03 KiB          [emitted]  
 /js/unit3d.js   7.2 KiB          [emitted]  
 + 11 hidden assets

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }

    at runLoaders (/var/www/html/node_modules/webpack/lib/NormalModule.js:301:20)
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/var/www/html/node_modules/postcss-loader/src/index.js:207:9)
    at <anonymous>
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(55:2) Missed semicolon

  53 | input[type="checkbox"] {
  54 |   margin: 4px 0 0;
> 55 |   margin-top: 1px \9; // IE8-9
     |  ^
  56 |   line-height: normal;
  57 | }

 @ ./resources/sass/app.scss 2:14-254
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-11T17_36_08_886Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-11T17_36_08_900Z-debug.log
```

**Comment by JeffreyWay** [comment]
It says you missed a semicolon somewhere.

Check the Mix 4.0 release notes. If you need to, you can switch back to the node-sass implementation.

```
npm install node-sass
```

```
mix.sass(‘src’, ‘output’, { implementation: require(‘node-sass’) });
```

**Comment by HDVinnie** [comment]
I guess Ill do that for now thanks. I just cannot see where Im missing a semicolon anywhere. Ill keep hunting though.

**Comment by fitztrev** [comment]
I have the same issue. It's from a bootstrap-sass stylesheet.

```shell
$ npm install bootstrap-sass@3.3.7 # latest version
```

```js
// webpack.mix.js
mix.sass('test.scss');
```

```sass
// test.scss
@import 'node_modules/bootstrap-sass/assets/stylesheets/bootstrap';
```

**Comment by HDVinnie** [comment]
@fitztrev is correct.....strange that the error didn't happen before updating Mix to v4.0.0. Im guessing one of the mix depencies is more strict now? Any idea on how to resolve this? Guessing will have to open issue on bootstraps GitHub repo.

**Comment by carestad** [comment]
Did you open a bug at Bootstrap? Seeing the same issue here when trying out mix 4.0.4

**Comment by irmantask** [comment]
I've same issue :/

**Comment by fitztrev** [comment]
@carestad @HDVinnie It's not a bug with `bootstrap-sass`. Their syntax is OK. My previous comment was meant to just point out where that line comes from and how to reproduce.

**Comment by HDVinnie** [comment]
@fitztrev so then as I originally thought it is a issue with Mix when it compiles the bootstrap SASS?

**Comment by HDVinnie** [comment]
@JeffreyWay anyway you can add support to ignore there Intentional CSS Hack?
https://github.com/twbs/bootstrap/issues/27822#issuecomment-446630893

**Comment by JeffreyWay** [comment]
It's a Dart Sass issue. 

https://github.com/sass/sass/issues/2590

Until they fix it, use the `node-sass` implementation instead.

```js
npm remove sass
npm install node-sass
```

```js
mix.sass(‘src’, ‘output’, { implementation: require(‘node-sass’) });
``

**Comment by idhowardgj94** [comment]
work for me, 
just implementation: require(‘node-sass’) need to change to implementation: require('node-sass')
                                                  ↑ quote mark                                                                     ↑ single quotation marks 
I'm using windows 7

**Comment by carestad** [comment]
@JeffreyWay possible to update sass to v1.15.3?

**Comment by matthewjumpsoffbuildings** [comment]
Im getting these dart sass errors too `Semicolons aren't allowed in the indented syntax`, is this going to be updated?

**Comment by karborator** [comment]
`ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /var/www/html/resources/sass/app.scss: import can only be used in import() or import.meta (2:1)

  1 | // Fonts
> 2 | @import url('https://fonts.googleapis.com/css?family=Nunito');
`

```

mix.react('resources/js/app.js', 'public/js')
     .sass('resources/sass/app.scss', 'public/css',{ implementation: require('node-sass') });

mix.webpackConfig({
    module: {
        rules: [
            {
                "loader": "babel-loader",
                "options": {
                    "presets": [
                        "@babel/preset-env",
                        "@babel/preset-react"
                    ],
                    "plugins": [
                        ["@babel/plugin-proposal-decorators", { "legacy": true }],
                        "@babel/plugin-proposal-class-properties"
                    ]
                }
            }
        ],
    },

});
```
