### ISSUE TITLE
[Laravel Mix - 4.0.4] - Stylus compilation fails if compiling JS files

### ISSUE THREAD

**Issue by silvioiannone** [JeffreyWay/laravel-mix#1854]
-   Laravel Mix Version: 4.0.4
-   Node Version: 10.6.0
-   NPM Version: 6.4.1
-   OS: macOS Mojave - 10.14.1

### Description:

I'm trying to build the stylus fils shipped with my application using

    mix.stylus('resources/stylus/app.styl', 'public/css');

but the building process stops with the following error:

    ERROR in ./resources/stylus/app.styl (./node_modules/css-loader/dist/cjs.js??ref--6-2!./node_modules/postcss-loader/src??postcss!./node_modules/stylus-loader??ref--6-4!./node_modules/style-loader!./node_modules/css-loader/dist/cjs.js!./node_modules/stylus-loader!./resources/stylus/app.styl)
    Module build failed (from ./node_modules/stylus-loader/index.js):
    ParseError: /Users/silvioiannone/Programming/Projects/Boptimera/resources/stylus/app.styl:2:123
    1|
    2| var content = require("!!../../node_modules/css-loader/dist/cjs.js!../../node_modules/stylus-loader/index.js!./app.styl");
    --------------------------------------------------------------------------------------------------------------------------------^
    3|
    4| if(typeof content === 'string') content = [[module.id, content, '']];
    5|
    
    expected "indent", got ";"
    
    at Parser.error (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.ident (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:1446:25)
    at Parser.stmt (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:685:21)
    at Parser.parse (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/parser.js:236:25)
    at Renderer.render (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus/lib/renderer.js:80:22)
    at /Users/silvioiannone/Programming/Projects/Boptimera/node_modules/stylus-loader/index.js:167:12
    at tryCatchReject (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/silvioiannone/Programming/Projects/Boptimera/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    @ ./resources/stylus/app.styl 2:14-322

I tried compiling it using the `stylus` CLI compiler and it works without problems.

It's was working with `laravel-mix` 2.x.

Additionally I can't find the above mentioned line (`var content = require("!!../../node_modules/css-loader/dist/cjs.js!../../node_modules/stylus-loader/index.js!./app.styl");`) in any of the stylus files.

Edit:

I noticed that the error shows itself only if I'm also compiling JS files. [This is where I'm making `laravel-mix` compile and process all the needed assets](https://github.com/silvioiannone/spa-skeleton/blob/master/webpack.mix.js#L46).

    mix.buildLocales();
    // this.buildJS(); <-- Stylus compilation works if I uncomment this line.
    this.buildStyles();

**Comment by silvioiannone** [comment]
@JeffreyWay The error is gone but now the compiled css files outputted to `public` are empty.

If I skip JS compilation the style files are compiled and outputted correctly (not empty).

This is probably related: #1856
