### ISSUE TITLE
V4 Can't compile Bootstrap sass ^3.4.0.

### ISSUE THREAD

**Issue by percymamedy** [JeffreyWay/laravel-mix#1886]
-   Laravel Mix Version: 4.0.12
-   Node Version:  v10.4.0
-   NPM Version: 6.1.0
-   OS: Ubuntu 18.04

### Description:

When using Boostrap-sass 3.4 am getting the following error :
```
 ERROR  Failed to compile with 2 errors                                                                              1:15:13 PM

 error  in ./resources/sass/app.scss

Syntax Error: ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(64:2) Missed semicolon

  62 | input[type="checkbox"] {
  63 |   margin: 4px 0 0;
> 64 |   margin-top: 1px \9; // IE8-9
     |  ^
  65 |   line-height: normal;
  66 | 


 error  in ./resources/sass/app.scss

Syntax Error: SyntaxError

(64:2) Missed semicolon

  62 | input[type="checkbox"] {
  63 |   margin: 4px 0 0;
> 64 |   margin-top: 1px \9; // IE8-9
     |  ^
  65 |   line-height: normal;
  66 | 



 @ ./resources/sass/app.scss 2:14-254

 
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(64:2) Missed semicolon

  62 | input[type="checkbox"] {
  63 |   margin: 4px 0 0;
> 64 |   margin-top: 1px \9; // IE8-9
     |  ^
  65 |   line-height: normal;
  66 | 

    at runLoaders (/var/www/node_modules/webpack/lib/NormalModule.js:301:20)
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/var/www/node_modules/postcss-loader/src/index.js:207:9)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/lib/loader.js??ref--8-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(64:2) Missed semicolon

  62 | input[type="checkbox"] {
  63 |   margin: 4px 0 0;
> 64 |   margin-top: 1px \9; // IE8-9
     |  ^
  65 |   line-height: normal;
  66 | 
```

### Steps To Reproduce:

1) Install boostrap-sass
```
$ yarn add bootstrap-sass@^3.4.0
```

2) Import it in resources/sass/app.scss
```
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

3) Run npm run dev
```
$npm run dev
```

**Comment by JeffreyWay** [comment]
That’s invalid CSS and isn’t recognized by Dart Sass. You’ll need to switch back to node-sass. I’m on my phone, so please see the Mix 4 release notes for instructions.
