### ISSUE TITLE
Build fails with dart-sass when path contains '#' symbol

### ISSUE THREAD

**Issue by cgodo** [JeffreyWay/laravel-mix#1915]
-   Laravel Mix Version: 4.0.13
-   Node Version: 10.15.0
-   NPM Version: 6.4.1
-   OS: Ubuntu 18.04 **|** Windows 10 Powershell **|** Windows 10 WSL with Ubuntu 18.04

### Description:

Build fails whenever an app is located in a path starting with '#' symbol. Seems to be related to `dart-sass` since switching back to `node-sass` fixes the issue. Sorry, I am not sure if the problem is in `dart-sass` itself, in `webpack` or in `laravel-mix`.

### Steps To Reproduce:

(Upgrading laravel-mix to --latest, deleting node_modules and clearing cache also reproduces the issue.)

1. Create a folder starting with '#' symbol and change dir.
`mkdir '#foo' && cd '#foo'`
2. Create a new Laravel app and change dir.
`laravel new bar && cd bar`
3. Install packages and try to build either dev, prod or watch
`yarn install && yarn dev`

--> Build fails.

### Output of `yarn dev`:

```
yarn run v1.12.3
$ npm run development
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1546718812619-0.2734050384892799/node but npm is using /home/carlos/.nvm/versions/node/v10.15.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @ development /home/carlos/#foo/bar
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

        Additional dependencies must be installed. This will only take a moment.

        Running: yarn add vue-template-compiler --dev --production=false

warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
        Okay, done. The following packages have been installed and saved to your package.json dependencies list:

        - vue-template-compiler

 98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 2 errors                                                                                                                                9:07:00 PM

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'variables';
       ^
      Join(null, "variables"): part 0 was null, but part 1 was not.
@import 'variables';
        ^^^^^^^^^^^
  stdin 6:9  root stylesheet
      in /home/carlos/#foo/bar/resources/sass/app.scss (line 6, column 9)
    at runLoaders (/home/carlos/#foo/bar/node_modules/webpack/lib/NormalModule.js:301:20)
    at /home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/home/carlos/#foo/bar/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:24226:48)
    at vC.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:15402:16)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)
    at iu.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8215:25)
    at iu.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8202:6)
    at oy.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:7992:35)
    at Object.m (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1406:19)
    at /home/carlos/#foo/bar/node_modules/sass/sass.dart.js:5043:51
    at w1.a (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1417:71)
    at w1.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8007:23)
    at uC.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8002:25)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)
    at iu.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8215:25)
    at iu.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8202:6)
    at Object.eval (eval at Bj (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:651:15), <anonymous>:3:37)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: Cannot extract a file path from a URI with a fragment component

 @ ./resources/sass/app.scss 2:14-254

     Asset      Size   Chunks             Chunk Names
/js/app.js  1.34 MiB  /js/app  [emitted]  /js/app

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'variables';
       ^
      Join(null, "variables"): part 0 was null, but part 1 was not.
@import 'variables';
        ^^^^^^^^^^^
  stdin 6:9  root stylesheet
      in /home/carlos/#foo/bar/resources/sass/app.scss (line 6, column 9)
    at runLoaders (/home/carlos/#foo/bar/node_modules/webpack/lib/NormalModule.js:301:20)
    at /home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/carlos/#foo/bar/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at render (/home/carlos/#foo/bar/node_modules/sass-loader/lib/loader.js:52:13)
    at Function.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:24226:48)
    at vC.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:15402:16)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)
    at iu.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8215:25)
    at iu.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8202:6)
    at oy.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:7992:35)
    at Object.m (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1406:19)
    at /home/carlos/#foo/bar/node_modules/sass/sass.dart.js:5043:51
    at w1.a (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1417:71)
    at w1.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8007:23)
    at uC.$2 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8002:25)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)
    at iu.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8215:25)
    at iu.cC (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8202:6)
    at Object.eval (eval at Bj (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:651:15), <anonymous>:3:37)
    at tz.vc (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8914:42)
    at tz.vb (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8916:32)
    at ie.ul (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8222:46)
    at t6.$0 (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8367:7)
    at Object.ex (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:1533:80)
    at ah.ba (/home/carlos/#foo/bar/node_modules/sass/sass.dart.js:8285:3)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: Cannot extract a file path from a URI with a fragment component
 @ ./resources/sass/app.scss 2:14-254
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlos/.npm/_logs/2019-01-05T20_07_00_157Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JeffreyWay** [comment]
If it's a Dart Sass issue, the issue should be filed with them.
