### ISSUE TITLE
Can't disable Terser in production mode

### ISSUE THREAD

**Issue by mike-grinspan** [JeffreyWay/laravel-mix#1935]
-   Laravel Mix Version: 4.0.13
-   Node Version: 11.6.0
-   Yarn Version: 1.13.0
-   OS: Ubuntu 18.04 Vagrant box on a Windows 7 host

### Description:
While running in production mode, if `terser` is set to false an error is thrown.

### Simplest Reproducible `webpack.mix.js`:
```
require('laravel-mix')
	.options({ terser: false })
	.js('resources/assets/js/app.js', 'public/js');
```

### Steps To Reproduce:
* Use the above `webpack.mix.js` file
* `yarn build -p`

### Error:
```
ubuntu@ubuntu-bionic:/var/www/xxxx$ yarn build -p
yarn run v1.13.0
$ node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js -p
Terser Plugin Invalid Options

options should be object

ValidationError: Terser Plugin Invalid Options
    at validateOptions (/vagrant/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new TerserPlugin (/vagrant/node_modules/terser-webpack-plugin/dist/index.js:40:30)
    at module.exports (/vagrant/node_modules/laravel-mix/src/builder/webpack-default.js:41:23)
    at new WebpackConfig (/vagrant/node_modules/laravel-mix/src/builder/WebpackConfig.js:14:30)
    at Object.<anonymous> (/vagrant/node_modules/laravel-mix/setup/webpack.config.js:29:18)
    at Module._compile (/vagrant/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (/vagrant/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mike-grinspan** [comment]
Also worth noting that you can't disable it in development mode either.

**Comment by ankurk91** [comment]
Why would someone wants to disable to js minification in production?

**Comment by NBAH1990** [comment]
Did you try this?
```
terser: {
            terserOptions: {
                compress: false
            }
        }
```

also, maybe mix.sourceMaps() will help you?

**Comment by arukompas** [comment]
You can disable minification in Laravel Mix like so:
```js
mix.webpackConfig({
    optimization: {
        minimize: false,
    }
});
```
