### ISSUE TITLE
TypeError: mix.js is not a function

### ISSUE THREAD

**Issue by oisceo** [JeffreyWay/laravel-mix#1983]
-   Laravel Mix Version: laravel-mix@4.0.14
-   Node Version (`node -v`): v11.9.0
-   NPM Version (`npm -v`): 6.5.0
-   OS: Ubuntu 18.04.1 LTS

### Description:
Whe I follow the instructions on https://laravel-mix.com/docs/4.0/installation#stand-alone-project I get the following error:

```
TypeError: mix.js is not a function
```

### Steps To Reproduce:

```sh
mkdir my-app && cd my-app
npm init -y
npm install laravel-mix --save-dev
cp node_modules/laravel-mix/setup/webpack.mix.js ./
node_modules/.bin/webpack --config webpack.mix.js
```

```
/home/vagrant/my-app/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

TypeError: mix.js is not a function
    at Object.<anonymous> (/home/vagrant/my-app/webpack.mix.js:14:5)
    at Module._compile (/home/vagrant/my-app/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (/home/vagrant/my-app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/home/vagrant/my-app/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/home/vagrant/my-app/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /home/vagrant/my-app/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/vagrant/my-app/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/home/vagrant/my-app/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (/home/vagrant/my-app/node_modules/yargs/yargs.js:567:18)
    at /home/vagrant/my-app/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/home/vagrant/my-app/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/vagrant/my-app/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
```

**Comment by jakedowns** [comment]
same here +1

**Comment by Hussam92** [comment]
I'm still running into this problem. All my laravel projects suffer from this problem. Is it a (machine)global npm problem?

**Comment by thinkverse** [comment]
Have ya'll tried changing the `package.json` script to `--config=node_modules/laravel-mix/setup/webpack.config.js` instead of `webpack.mix.js` ? Had the same problem and changed `webpack.mix.js` to `webpack.config.js` and that fixed it for me.

**Comment by Rj-Aman** [comment]
> I'm still running into this problem. All my laravel projects suffer from this problem. Is it a (machine)global npm problem?

Can you please tell me any solution for this if you found any??

**Comment by Rj-Aman** [comment]
> Have ya'll tried changing the `package.json` script to `--config=node_modules/laravel-mix/setup/webpack.config.js` instead of `webpack.mix.js` ? Had the same problem and changed `webpack.mix.js` to `webpack.config.js` and that fixed it for me.

unable to get you. Can you please explain? Really need help. Thanks in advance

**Comment by Vedantaz** [comment]
I am also stuck in Laravel , old one 5.0.4. is running but error is coming .
And on new one it is not running properly even generally.
