### ISSUE TITLE
React can't compile with Laravel Mix 4+

### ISSUE THREAD

**Issue by ionut2497** [JeffreyWay/laravel-mix#2037]
-   Laravel Mix Version: 4.0.7 
-   Node Version (`node -v`):v10.15.3
-   NPM Version (`npm -v`):6.9.0
-   OS: Windows 10

### Description:
When upgrading to laravel-mix 4+, if there is any mix.react() in the webpack.mix, i get the error from the bottom of the page with the stack-trace

### Steps To Reproduce:
1.Insert Mix.react() in the webpack file
2.Upgrade to laravel mix 4+ to correct vulnerabilities

Stack trace and error : 
C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\cli.js:231
                                throw err;
                                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeObject (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\deepmerge\dist\umd.js:55:9)
    at deepmerge (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\deepmerge\dist\umd.js:79:10)
    at reduce (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\babel-merge\dist\index.js:30:44)
    at Array.reduce (<anonymous>)
    at mergeArray (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\babel-merge\dist\index.js:20:36)
    at babelMerge (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\babel-merge\dist\index.js:40:19)
    at values.reduce (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\babel-merge\dist\index.js:60:26)
    at Array.reduce (<anonymous>)
    at Function.value (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\babel-merge\dist\index.js:58:49)
    at Function.generate (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\BabelConfig.js:11:22)
    at Object.babel (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\config.js:121:45)
    at React.webpackRules (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\components\JavaScript.js:76:41)
    at ComponentFactory.applyRules (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\components\ComponentFactory.js:155:23)
    at Mix.listen.rules (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\components\ComponentFactory.js:66:48)
    at events.(anonymous function).forEach.handler (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\Dispatcher.js:34:47)
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\Dispatcher.js:34:28)
    at Mix.dispatch (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\Mix.js:119:25)
    at WebpackConfig.buildRules (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\builder\WebpackConfig.js:83:13)
    at WebpackConfig.build (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\src\builder\WebpackConfig.js:23:14)
    at Object.<anonymous> (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\laravel-mix\setup\webpack.config.js:29:38)
    at Module._compile (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\webpack-cli\bin\cli.js:228:39)
    at Object.parse (C:\WinNMP\WWW\MyCC\Portalv2\node_modules\yargs\yargs.js:567:18)

**Comment by zhernosekim** [comment]
I hadn't problems with Ubuntu + Laravel-mix 4 + React

**Comment by ionut2497** [comment]
> I hadn't problems with Ubuntu + Laravel-mix 4 + React

Our Production server is a CentOS 7 and we had the same issue...

**Comment by jandominik** [comment]
I have totally same issue, Mac OS.

**Comment by zhernosekim** [comment]
Did you rename webpackConfig module loaders to rules?

**Comment by jakedowns** [comment]
https://github.com/JeffreyWay/laravel-mix/issues/1951#issuecomment-456524222 helped me

**Comment by ionut2497** [comment]
@jakedowns  thanks , it solved it indeed

**Comment by Achala03** [comment]
What's the solution.Plz help.
