### ISSUE TITLE
npm run dev / npm run watch Error on fresh Laravel installation

### ISSUE THREAD

**Issue by connecteev** [JeffreyWay/laravel-mix#2125]
### Description:
First off, thanks for creating Laravel Mix, it's a godsend. That said, we're [still having this issue](https://github.com/JeffreyWay/laravel-mix/issues/523) with ```npm run watch``` or ```npm run dev``` with a fresh installation of Laravel (no code changes at all). I know there is a workaround (see below), but not sure why we'd have to go through so many steps?

$ laravel new testmix
$ npm run dev

The following error is seen:
```
OneStepAtATime:testmix kunalpunjabi$ npm run dev

> @ dev /Users/kunalpunjabi/Code/testmix
> npm run development


> @ development /Users/Code/testmix
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-06-08T00_58_49_951Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kunalpunjabi/.npm/_logs/2019-06-08T00_58_49_988Z-debug.log
```

### Steps To Reproduce:
See above.

### Environment:
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
/Users/Code/test-mix
└── (empty)
-   Node Version (`node -v`): v10.13.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Mac OS High Sierra 10.13.4 (17E199)
- Laravel Framework: 5.8.21

### Workaround: 
Run the following commands, but again, why are these necessary? Can't we fix this and avoid the pain for many a developer?
```
composer update
rm -rf node_modules
npm cache clean --force
npm install
npm run dev
```

**Comment by torressam333** [comment]
Your work around steps worked for me.

**Comment by ibnshehu** [comment]
Thanks for this update.

**Comment by UgwuObed** [comment]
This did not work for me, i still get errors

**Comment by torressam333** [comment]
@UgwuObed  can you post the exact errors you are getting? Along with the errors can you gives is steps to reproduce your specific situation?
