### ISSUE TITLE
ModuleNotFoundError: No module named 'cliapp' after fresh install

### ISSUE THREAD

**Issue by Victoor** [JeffreyWay/laravel-mix#2167]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`): 4.1.2
-   Node Version (`node -v`): v12.6.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Ubuntu 18-04

### Description:
I can't run `npm run watch` after a fresh install. It returns this:

```Traceback (most recent call last):
  File "/usr/bin/yarn", line 20, in <module>
    import cliapp
ModuleNotFoundError: No module named 'cliapp'
/home/victor/Documents/fffp/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Command failed: yarn add vue-template-compiler --dev --production=false
Traceback (most recent call last):
  File "/usr/bin/yarn", line 20, in <module>
    import cliapp
ModuleNotFoundError: No module named 'cliapp'

    at checkExecSyncError (child_process.js:623:11)
    at Object.execSync (child_process.js:659:15)
    at Dependencies.execute (/home/victor/Documents/fffp/node_modules/laravel-mix/src/Dependencies.js:53:22)
    at /home/victor/Documents/fffp/node_modules/laravel-mix/src/Dependencies.js:32:22
    at Array.value (/home/victor/Documents/fffp/node_modules/laravel-mix/src/helpers.js:24:13)
    at Dependencies.install (/home/victor/Documents/fffp/node_modules/laravel-mix/src/Dependencies.js:31:14)
    at Function.dependencies (/home/victor/Documents/fffp/node_modules/laravel-mix/src/Assert.js:77:40)
    at /home/victor/Documents/fffp/node_modules/laravel-mix/src/components/ComponentFactory.js:131:24
    at Array.value (/home/victor/Documents/fffp/node_modules/laravel-mix/src/helpers.js:24:13)
    at ComponentFactory.installDependencies (/home/victor/Documents/fffp/node_modules/laravel-mix/src/components/ComponentFactory.js:130:14)
    at /home/victor/Documents/fffp/node_modules/laravel-mix/src/components/ComponentFactory.js:55:44
    at /home/victor/Documents/fffp/node_modules/laravel-mix/src/Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/home/victor/Documents/fffp/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/home/victor/Documents/fffp/node_modules/laravel-mix/src/Mix.js:119:25)
    at Object.<anonymous> (/home/victor/Documents/fffp/node_modules/laravel-mix/setup/webpack.config.js:19:5)
    at Module._compile (/home/victor/Documents/fffp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (/home/victor/Documents/fffp/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/victor/Documents/fffp/node_modules/webpack-cli/bin/utils/convert-argv.js:116:13)
    at requireConfig (/home/victor/Documents/fffp/node_modules/webpack-cli/bin/utils/convert-argv.js:118:6)
    at /home/victor/Documents/fffp/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/victor/Documents/fffp/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at /home/victor/Documents/fffp/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/victor/Documents/fffp/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/victor/Documents/fffp/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/victor/Documents/fffp/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 75 73 72 2f 62 69 ... 94 more bytes>
  ],
  pid: 29390,
  stdout: <Buffer >,
  stderr: <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 2f 75 73 72 2f 62 69 ... 94 more bytes>
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/victor/.npm/_logs/2019-07-21T08_42_30_274Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/victor/.npm/_logs/2019-07-21T08_42_30_282Z-debug.log
```

### Steps To Reproduce:
Just create a new Laravel app from scratch and do `npm install` and `npm run watch`.

**Comment by susanka068** [comment]
I've encountered this error

**Comment by zarater** [comment]
I've received same issue

**Comment by tab1tha** [comment]
I have encountered this same error while running `yarn install`

**Comment by s1awek** [comment]
Need to upgrade `yarn` to the latest version:

For macOS users, if you installed yarn via brew, you can upgrade it using the below command:

`brew upgrade yarn`

On Linux, just run the below command at the terminal:

`$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash`

On Windows, upgrade with Chocolatey

`choco upgrade yarn`

More: https://stackoverflow.com/questions/49689174/yarn-how-to-upgrade-yarn-version-using-terminal

**Comment by sammiearchie77** [comment]
I upgraded my yarn on ubuntu and I'm still having the same problem

**Comment by hlorofos** [comment]
I've the same problem on digital ocean droplet after `sudo apt-get install yarn` command
