### ISSUE TITLE
vue.webpackConfig is called even when Vue is not used (npm scripts do not run)

### ISSUE THREAD

**Issue by kode-ninja** [JeffreyWay/laravel-mix#2171]
-   Laravel Mix Version: 4.1.2
-   Node Version: 8.10.0
-   NPM Version: 6.9.0
-   OS: Ubuntu 18.04

### Description:
On my Laravel installation, I use only ReactJS, without Vue.js.
Trying to run ```npm run prod``` or ```npm run watch``` fail with the following error:
```
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch" "--watch-poll"

/path/laravel/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

TypeError: Cannot read property 'find' of undefined
    at updateCssLoader.rule (/path/laravel/node_modules/laravel-mix/src/components/Vue.js:48:26)
    at Vue.updateCssLoader (/path/laravel/node_modules/laravel-mix/src/components/Vue.js:96:21)
    at Vue.updateCssLoaders (/path/laravel/node_modules/laravel-mix/src/components/Vue.js:47:14)
    at Vue.webpackConfig (/path/laravel/node_modules/laravel-mix/src/components/Vue.js:37:14)
    at JavaScript.webpackConfig (/path/laravel/node_modules/laravel-mix/src/components/JavaScript.js:90:22)
    at Mix.listen.config (/path/laravel/node_modules/laravel-mix/src/components/ComponentFactory.js:75:54)
    at events.(anonymous function).forEach.handler (/path/laravel/node_modules/laravel-mix/src/Dispatcher.js:34:47)
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (/path/laravel/node_modules/laravel-mix/src/Dispatcher.js:34:28)
    at Mix.dispatch (/path/laravel/node_modules/laravel-mix/src/Mix.js:119:25)
    at WebpackConfig.build (/path/laravel/node_modules/laravel-mix/src/builder/WebpackConfig.js:31:13)
    at Object.<anonymous> (/path/laravel/node_modules/laravel-mix/setup/webpack.config.js:29:38)
    at Module._compile (/path/laravel/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/path/laravel/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/path/laravel/node_modules/webpack-cli/bin/utils/convert-argv.js:116:13)
    at requireConfig (/path/laravel/node_modules/webpack-cli/bin/utils/convert-argv.js:118:6)
    at /path/laravel/node_modules/webpack-cli/bin/utils/convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (/path/laravel/node_modules/webpack-cli/bin/utils/convert-argv.js:123:15)
    at yargs.parse (/path/laravel/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/path/laravel/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /path/laravel/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/path/laravel/node_modules/webpack-cli/bin/cli.js:365:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/laravel/node_modules/webpack/bin/webpack.js:156:2)
```

The only way I was able to continue was to edit and comment line 90 inside node_modules/laravel-mix/src/components/JavaScript.js

I originally posted this on [laracasts](https://laracasts.com/discuss/channels/elixir/exception-when-running-npm-run-watch-poll?page=1) where you can find my package.json and webpack.mix.js files.

**Comment by kode-ninja** [comment]
Anyone had a chance to review this?

**Comment by kode-ninja** [comment]
Reproduced in Laravel 6.2 too

**Comment by kode-ninja** [comment]
Still relevant. Waiting for a resolution.

**Comment by kode-ninja** [comment]
Still waiting for a fix for this issue

**Comment by kode-ninja** [comment]
Still waiting for a fix for this issue

**Comment by kode-ninja** [comment]
yes, still waiting a resolution
