### ISSUE TITLE
npm run hot not working in laravel

### ISSUE THREAD

**Issue by zhernosekim** [JeffreyWay/laravel-mix#2186]
-   Laravel Mix Version: 4.1.2
-   Node Version (`node -v`): 8.10.0
-   NPM Version (`npm -v`): 6.9.0
-   OS: Ubuntu 18.04.1 LTS

### Description:
I run 'npm run hot' and get error:

```events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
```

### Steps To Reproduce:
1. composer create-project --prefer-dist laravel/laravel blog
2. cd blog && npm i
3. npm run hot

**Comment by ankurk91** [comment]
The error message indicates that your port 8080 is busy, try to restart your machine and try again.
