### ISSUE TITLE
Unable to excecute `npm run dev` on Centos 7 

### ISSUE THREAD

**Issue by ssmusoke** [JeffreyWay/laravel-mix#2278]
-   Laravel Mix Version: 5.0.0 and  4.1.4 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.13.0
-   NPM Version (`npm -v`): 6.13.0
-   OS: CentOS Linux 7 (Core) 

### Description: 

package.json

`
{
	"private": true,
	"scripts": {
		"dev": "npm run development",
		"development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch": "npm run development -- --watch",
		"watch-poll": "npm run watch -- --watch-poll",
		"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
		"prod": "npm run production",
		"production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
	},
	"devDependencies": {
		"axios": "^0.19",
		"bootstrap": "^4.0.0",
		"cross-env": "^5.1",
		"jquery": "^3.2",
		"laravel-mix": "^4.0.7",
		"lodash": "^4.17.13",
		"popper.js": "^1.16.0",
		"resolve-url-loader": "^2.3.1",
		"sass": "^1.23.3",
		"sass-loader": "7.*",
		"vue": "^2.5.17",
		"vue-template-compiler": "^2.6.10"
	},
	"dependencies": {
		"element-ui": "^2.12.0",
		"laravel-vue-pagination": "^2.3.1",
		"node-sass": "^4.13.0",
		"sweetalert2": "^8.19.0",
		"vee-validate": "^2.1.7",
		"vue-moment": "^4.0.0",
		"vue-router": "^3.1.3",
		"vue-snotify": "^3.2.1",
		"vue-spinner": "^1.0.3",
		"vue-sweetalert2": "^2.1.5",
		"vue-timeago": "^5.1.2",
		"vue2-transitions": "^0.3.0",
		"vuelidate": "^0.7.4"
	}
}
`

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'dev' ]
2 info using npm@6.13.0
3 info using node@v12.13.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/growdev/envoyer/releases/20191113043330/node_modules/.bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/growdev/.local/bin:/home/growdev/bin
9 verbose lifecycle @~dev: CWD: /home/growdev/envoyer/releases/20191113043330
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @
15 verbose cwd /home/growdev/envoyer/releases/20191113043330
16 verbose Linux 3.10.0-1062.4.1.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "dev"
18 verbose node v12.13.0
19 verbose npm  v6.13.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

### Steps To Reproduce:
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install
npm run dev 

This bring the error, there are no issues on Windows or MacOS Catalina

**Comment by ssmusoke** [comment]
Looks like 

```sudo npm run dev``` 

solves this issue - strange but true
