### ISSUE TITLE
Bug report?: Sass import is working on develop mode but not in production build

### ISSUE THREAD

**Issue by alexvandervegt** [JeffreyWay/laravel-mix#2292]
Hi,

I am working with laravel-mix 5.0.0.

My main entry js file looks like:

```
$( document ).ready( () => {
	/**
	 * Bootstrap the components
	 */
	$( '[data-component]' ).each( async ( index, dataComponent ) => {
		let componentName = $( dataComponent ).data( 'component' );

		try {
			let component = await import(
				/* webpackInclude: /\.js/ */
				/* webpackMode: "lazy-once" */
				/* webpackPrefetch: true */
				/* webpackPreload: true */
				`../../components/${componentName}/${componentName}`
				);

			component.default();
		} catch ( error ) {
			console.log( 'Loading error: ', error );
		}
	} );
} );
```

Then my slider component has something like this:

```
import './slider.scss'

export default () => {
	console.log( 'SLIDER INIT' );
}
```

When i run the develop watch mode it generates this bug at first in the console:

```
app.js:21 Loading error:  TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap:77)
    at Object../node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/dist/cjs.js?!./node_modules/import-glob-loader/index.js!./wp-content/themes/themename/components/slider/slider.scss (slider.scss:1)
    at __webpack_require__ (bootstrap:77)
    at Object../wp-content/themes/themename/components/slider/slider.scss (slider.scss?897a:1)
    at __webpack_require__ (bootstrap:77)
    at Module../wp-content/themes/themename/components/slider/slider.js (slider.js:1)
    at __webpack_require__ (bootstrap:77)
app.js:21 Loading error:  TypeError: __webpack_require__(...) is not a function
    at Object../node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src/index.js?!./node_modules/sass-loader/dist/cjs.js?!./node_modules/import-glob-loader/index.js!./wp-content/themes/themename/components/carousel/carousel.scss (carousel.scss:1)
    at __webpack_require__ (bootstrap:77)
    at Object../wp-content/themes/themename/components/carousel/carousel.scss (carousel.scss?886e:1)
    at __webpack_require__ (bootstrap:77)
    at Module../wp-content/themes/themename/components/carousel/carousel.js (carousel.js:1)
    at __webpack_require__ (bootstrap:77)
```

And as soon as i edit the slider.js everything is working as expected all sass is compiling to css and is loading fine in the browser.

When I do a production build I have the same error.

Does someone know what is going wrong? Or is this a bug?

webpack.mix.js

```
const mix = require( 'laravel-mix' );
require( 'laravel-mix-copy-watched' );

const packageJson = require( './package.json' );
let config = packageJson.config;

mix.disableNotifications();

mix.setPublicPath( config.themePath + '/dist' )
   .browserSync( {
	   proxy: config.devUrl,
	   files: [
		   config.themePath + '/assets/**/*.js',
		   config.themePath + '/assets/**/*.scss',
		   config.themePath + '/components/**/*.js',
		   config.themePath + '/components/**/*.scss',
		   config.themePath + '/**/*.php',
		   config.themePath + '/**/*.twig'
	   ]
   } );

mix.webpackConfig( {
	module: {
		rules: [
			{
				test: /\.scss$/,
				enforce: 'pre',
				loader: 'import-glob-loader'
			}
		]
	},
	output: {
		publicPath: config.themePath + '/dist/',
		chunkFilename: '[name].[hash:5].js'
	},
	devServer: {
		contentBase: config.themePath + '/dist',
	}
} );

mix.sass( config.themePath + '/assets/styles/app.scss', 'styles' )
   .sass( config.themePath + '/assets/styles/editor.scss', 'styles' );

mix.js( config.themePath + '/assets/scripts/app.js', 'scripts' );

mix.copyWatched( config.themePath + '/assets/images', 'dist/images' )
   .copyWatched( config.themePath + '/assets/fonts', 'dist/fonts' );

mix.autoload( {
	jquery: [ '$', 'window.jQuery' ],
} );

mix.options( {
	processCssUrls: false,
} );

mix.sourceMaps( false, 'source-map' )
   .version();
```

package.json

```
{
	"name": "themename",
	"config": {
		"production": false,
		"devUrl": "themename.dev.com",
		"themePath": "wp-content/themes/themename"
	},
	"dependencies": {
		"@fortawesome/fontawesome-free": "^5.11.2",
		"aos": "^2.3.4",
		"bootstrap": "^4.4.1",
		"jquery": "^3.4.1",
		"jquery-validation": "^1.19.1",
		"jquery.heapbox": "^0.9.5",
		"magnific-popup": "^1.1.0",
		"normalize-scss": "^7.0.1",
		"slick-carousel": "^1.8.1"
	},
	"engines": {
		"node": ">=8.5.0"
	},
	"private": true,
	"browserslist": [
		"extends @wordpress/browserslist-config"
	],
	"scripts": {
		"build": "cross-env NODE_ENV=development run-s mix",
		"build:production": "cross-env NODE_ENV=production run-s clean mix",
		"start": "cross-env NODE_ENV=development run-s \"mix -- --watch\"",
		"mix": "webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"clean": "run-p clean:*",
		"clean:dist": "rimraf wp-content/themes/themename/dist",
		"lint": "run-s -c lint:*",
		"lint:scripts": "eslint wp-content/themes/themename/assets/scripts && eslint wp-content/themes/themename/components",
		"lint:styles": "stylelint \"wp-content/themes/themename/assets/**/*.{css,sass,scss,less}\" && stylelint \"wp-content/themes/themename/components/**/*.{css,sass,scss,less}\""
	},
	"devDependencies": {
		"@babel/plugin-syntax-dynamic-import": "^7.2",
		"@wordpress/babel-preset-default": "^4.7.0",
		"@wordpress/browserslist-config": "^2.6.0",
		"@wordpress/dependency-extraction-webpack-plugin": "^2.1.0",
		"babel-eslint": "^10.0.3",
		"browser-sync": "^2.26.7",
		"browser-sync-webpack-plugin": "^2.0.1",
		"cross-env": "^6.0.3",
		"css-loader": "^3.2.1",
		"eslint": "^6.7.2",
		"eslint-plugin-import": "^2.18.2",
		"import-glob-loader": "^1.1.0",
		"laravel-mix": "^5.0.0",
		"laravel-mix-copy-watched": "^2.2.1",
		"npm-run-all": "^4.1",
		"rimraf": "^3.0",
		"sass": "^1.23.7",
		"sass-loader": "^8.0.0",
		"style-loader": "^1.0.1",
		"stylelint": "^11.1.1",
		"stylelint-config-standard": "^19.0.0",
		"vue-template-compiler": "^2.6.10"
	},
	"babel": {
		"plugins": [
			"@babel/plugin-syntax-dynamic-import"
		]
	},
	"eslintConfig": {
		"root": true,
		"extends": "eslint:recommended",
		"parser": "babel-eslint",
		"globals": {
			"wp": true
		},
		"env": {
			"node": true,
			"es6": true,
			"amd": true,
			"browser": true,
			"jquery": true
		},
		"parserOptions": {
			"ecmaFeatures": {
				"globalReturn": true,
				"generators": false,
				"objectLiteralDuplicateProperties": false
			},
			"ecmaVersion": 2017,
			"sourceType": "module"
		},
		"plugins": [
			"import"
		],
		"settings": {
			"import/core-modules": [],
			"import/ignore": [
				"node_modules",
				"\\.(coffee|scss|css|less|hbs|svg|json)$"
			]
		},
		"rules": {
			"no-console": 0,
			"comma-dangle": [
				"error",
				{
					"arrays": "always-multiline",
					"objects": "always-multiline",
					"imports": "always-multiline",
					"exports": "always-multiline",
					"functions": "ignore"
				}
			]
		}
	},
	"stylelint": {
		"extends": "stylelint-config-standard",
		"rules": {
			"string-quotes": "single",
			"indentation": "tab",
			"at-rule-empty-line-before": null,
			"selector-pseudo-element-colon-notation": "single",
			"declaration-colon-newline-after": null,
			"value-list-comma-newline-after": null,
			"no-empty-source": null,
			"no-descending-specificity": null,
			"at-rule-no-unknown": [
				true,
				{
					"ignoreAtRules": [
						"extend",
						"at-root",
						"debug",
						"warn",
						"error",
						"if",
						"else",
						"for",
						"each",
						"while",
						"mixin",
						"include",
						"content",
						"return",
						"tailwind",
						"apply",
						"responsive",
						"variants",
						"screen",
						"function"
					]
				}
			]
		}
	}
}
```

**Comment by yusufdemir** [comment]
How it fix ?

**Comment by W17LXM** [comment]
A temporary fix for us was to stop using laravel-mix "^5.0.0". 
Bumped back down to Laravel-mix "^4.0.7" and no npm run prod errors

**Comment by alexvandervegt** [comment]
Can you share your code samples? Because when I downgrade I get a whole lot of other errors...

**Comment by W17LXM** [comment]
@alexvandervegt  What code samples do you need ? (sorry, i'm still learning Laravel)

On the package.json file we've bumped Laravel-mix to "^4.0.7". Did "npm install" which installed the version 4.1.4 of Laravel-mix.

Could you share your errors messages ?

**Comment by alexvandervegt** [comment]
Here you go:

```
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/assets/styles/app.scss

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/assets/styles/editor.scss

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/assets/styles/visualComposer.scss

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/assets/styles/backwards.scss

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss

Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)
    at runLoaders (/Users/**/node_modules/webpack/lib/NormalModule.js:316:20)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/**/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/**/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/**/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)

 error  in ./wp-content/themes/themename/components/breadcrumbs/breadcrumbs.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)

 @ ./wp-content/themes/themename/components/breadcrumbs/breadcrumbs.scss 1:14-282
 @ ./wp-content/themes/themename/components/breadcrumbs/breadcrumbs.js
 @ ./wp-content/themes/themename/components lazy-once ^\.\/.*$ include: \.js prefetchOrder: 0 preloadOrder: 0 namespace object
 @ ./wp-content/themes/themename/assets/scripts/app.js
 @ multi ./wp-content/themes/themename/assets/scripts/app.js ./wp-content/themes/themename/assets/styles/app.scss ./wp-content/themes/themename/assets/styles/editor.scss ./wp-content/themes/themename/assets/styles/visualComposer.scss ./wp-content/themes/themename/assets/styles/backwards.scss ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss ./wp-content/themes/themename/assets/styles/backwards-js_composer.scss

 error  in ./wp-content/themes/themename/components/brandIntro/brandIntro.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)

 @ ./wp-content/themes/themename/components/brandIntro/brandIntro.scss 1:14-281
 @ ./wp-content/themes/themename/components/brandIntro/brandIntro.js
 @ ./wp-content/themes/themename/components lazy-once ^\.\/.*$ include: \.js prefetchOrder: 0 preloadOrder: 0 namespace object
 @ ./wp-content/themes/themename/assets/scripts/app.js
 @ multi ./wp-content/themes/themename/assets/scripts/app.js ./wp-content/themes/themename/assets/styles/app.scss ./wp-content/themes/themename/assets/styles/editor.scss ./wp-content/themes/themename/assets/styles/visualComposer.scss ./wp-content/themes/themename/assets/styles/backwards.scss ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss ./wp-content/themes/themename/assets/styles/backwards-js_composer.scss

 error  in ./wp-content/themes/themename/components/carousel/carousel.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)

 @ ./wp-content/themes/themename/components/carousel/carousel.scss 1:14-279
 @ ./wp-content/themes/themename/components/carousel/carousel.js
 @ ./wp-content/themes/themename/components lazy-once ^\.\/.*$ include: \.js prefetchOrder: 0 preloadOrder: 0 namespace object
 @ ./wp-content/themes/themename/assets/scripts/app.js
 @ multi ./wp-content/themes/themename/assets/scripts/app.js ./wp-content/themes/themename/assets/styles/app.scss ./wp-content/themes/themename/assets/styles/editor.scss ./wp-content/themes/themename/assets/styles/visualComposer.scss ./wp-content/themes/themename/assets/styles/backwards.scss ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss ./wp-content/themes/themename/assets/styles/backwards-js_composer.scss

 error  in ./wp-content/themes/themename/components/image/image.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)

 @ ./wp-content/themes/themename/components/image/image.scss 1:14-276
 @ ./wp-content/themes/themename/components/image/image.js
 @ ./wp-content/themes/themename/components lazy-once ^\.\/.*$ include: \.js prefetchOrder: 0 preloadOrder: 0 namespace object
 @ ./wp-content/themes/themename/assets/scripts/app.js
 @ multi ./wp-content/themes/themename/assets/scripts/app.js ./wp-content/themes/themename/assets/styles/app.scss ./wp-content/themes/themename/assets/styles/editor.scss ./wp-content/themes/themename/assets/styles/visualComposer.scss ./wp-content/themes/themename/assets/styles/backwards.scss ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss ./wp-content/themes/themename/assets/styles/backwards-js_composer.scss

 error  in ./wp-content/themes/themename/components/footer/footer.scss

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'outputStyle'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/Users/**/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/Users/**/node_modules/sass-loader/dist/index.js:36:28)

 @ ./wp-content/themes/themename/components/footer/footer.scss 1:14-277
 @ ./wp-content/themes/themename/components/footer/footer.js
 @ ./wp-content/themes/themename/components lazy-once ^\.\/.*$ include: \.js prefetchOrder: 0 preloadOrder: 0 namespace object
 @ ./wp-content/themes/themename/assets/scripts/app.js
 @ multi ./wp-content/themes/themename/assets/scripts/app.js ./wp-content/themes/themename/assets/styles/app.scss ./wp-content/themes/themename/assets/styles/editor.scss ./wp-content/themes/themename/assets/styles/visualComposer.scss ./wp-content/themes/themename/assets/styles/backwards.scss ./wp-content/themes/themename/assets/styles/backwards-carousel-anything.scss ./wp-content/themes/themename/assets/styles/backwards-js_composer.scss
```
