### ISSUE TITLE
How to avoid PostCSS bug by minimally disabling optimizations

### ISSUE THREAD

**Issue by themightychris** [JeffreyWay/laravel-mix#2298]
This bug in postcss is blocking my builds when production optimizations are enabled: https://github.com/postcss/postcss-calc/issues/77

Setting `production: false` on overall options works around the issue:

```js
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .setPublicPath('./public')
    .options({
        production: false
    });
```

But I end up with enormous unminified CSS and JS files. Is there a tighter way to disable the postcss processing while keeping all JS processing in place? And maybe some CSS minification too? I tried tons of combinations of plugin-level options and webpack options but above is the only way I could get a working build

## Test case

Here's a minimal reproduction of the issue, it happens on `yarn production` once you have `bootstrap-vue`'s SCSS included and then declare a SASS variable with a space: https://github.com/themightychris/laravel-postcsscalc77-test/commit/4ce2a026fa345657182040f179b70dffbddd6274

The output in this case is:

```console
$ yarn production
yarn run v1.19.1
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
JisonParserError: Parse error on line 1: 
0.5rem 0.75rem / ...
-------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "REMS"
    at /css/app.css:12769:3
    at Parser.parseError (/src/laravel-postcss-test/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Parser.parse (/src/laravel-postcss-test/node_modules/postcss-calc/dist/parser.js:1680:30)
    at /src/laravel-postcss-test/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/src/laravel-postcss-test/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/src/laravel-postcss-test/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/src/laravel-postcss-test/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/src/laravel-postcss-test/node_modules/postcss-calc/dist/lib/transform.js:59:100)
    at /src/laravel-postcss-test/node_modules/postcss-calc/dist/index.js:25:51
    at /src/laravel-postcss-test/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/src/laravel-postcss-test/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/src/laravel-postcss-test/node_modules/postcss/lib/container.js:131:17)
    at /src/laravel-postcss-test/node_modules/postcss/lib/container.js:148:24
    at Root.each (/src/laravel-postcss-test/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/src/laravel-postcss-test/node_modules/postcss/lib/container.js:131:17)
    at /src/laravel-postcss-test/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/src/laravel-postcss-test/node_modules/cssnano/dist/index.js:31:51)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by frederick** [comment]
Not sure if this helps but, I "solved" a similar problem by changing the contents of a variable in my SCSS so it only contained one value.
Passing in multiple values like `1rem 2rem` was throwing the error, but changing it to `1.5rem`; worked. 

I recognize this doesn't actually fix the problem but in my case I was able to work around it in this way.

**Comment by khaledelmahdi** [comment]
Any update on this issue?
