### ISSUE TITLE
CssSyntaxError - Missed semicolon Possible Solution!

### ISSUE THREAD

**Issue by Sidirgot** [JeffreyWay/laravel-mix#2375]
Hey everyone,

I have a Laravel - Tailwindcss - Vuejs - Vue Router - Vuex project that heavily uses lazy loading etc.

While npm run watch / dev worked without any issues, when running for production i used to get this error.

```
CssSyntaxError: /css/app.css:34243:19: Missed semicolon
    at Input.error (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\input.js:130:16)
    at Parser.checkMissedSemicolon (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\parser.js:603:22)
    at Parser.decl (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\parser.js:286:46)
    at Parser.other (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\parser.js:166:12)
    at Parser.parse (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\parser.js:77:16)
    at parse (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\parse.js:17:12)
    at new LazyResult (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\lazy-result.js:60:16)
    at Processor.<anonymous> (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\processor.js:138:12)
    at Processor.process (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\processor.js:117:23)
    at Function.creator.process (C:\Users\Sidirgot\Development\tenacms\node_modules\postcss\lib\postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (C:\Users\Sidirgot\Development\tenacms\node_modules\optimize-css-assets-webpack-plugin\src\index.js:73:21)
    at Object.processor (C:\Users\Sidirgot\Development\tenacms\node_modules\optimize-css-assets-webpack-plugin\src\index.js:13:18)
    at C:\Users\Sidirgot\Development\tenacms\node_modules\last-call-webpack-plugin\src\index.js:150:10
    at arrayEach (C:\Users\Sidirgot\Development\tenacms\node_modules\lodash\_arrayEach.js:15:9)
    at forEach (C:\Users\Sidirgot\Development\tenacms\node_modules\lodash\forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (C:\Users\Sidirgot\Development\tenacms\node_modules\last-call-webpack-plugin\src\index.js:147:5)
    at C:\Users\Sidirgot\Development\tenacms\node_modules\last-call-webpack-plugin\src\index.js:178:28
    at _next0 (eval at create (C:\Users\Sidirgot\Development\tenacms\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:17)
    at eval (eval at create (C:\Users\Sidirgot\Development\tenacms\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:25:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

After a bit of trial and error, i changed my webpack mix js from ( which only worked for watch / dev): 

```
mix.js('resources/js/backend/backend.js','public/js')
   .js('resources/js/frontend/frontend.js','public/js')
   .postCss('resources/css/app.css','public/css',[
       tailwindcss('resources/js/tailwindcss.js')
    ]);
```

To this: 

```
mix.js('resources/js/backend/backend.js','public/js')
   .js('resources/js/frontend/frontend.js','public/js')
   .options({
        postCss: [
            tailwindcss('resources/js/tailwindcss.js'),
        ]
    });
```

And now i am compiling for production without any issues, but this is only because i am not using the app.css file at all. Is there a possible solution to complete this answer?

**Comment by Sheetal575** [comment]
how to solve this @Sidirgot
