### ISSUE TITLE
Failed to run webpack: TypeError: webpack.LoaderOptionsPlugin is not a constructor

### ISSUE THREAD

**Issue by akitengineer** [JeffreyWay/laravel-mix#24]
Following error is occurring when I am trying to run 

node_modules/.bin/webpack

![image](https://cloud.githubusercontent.com/assets/7546373/21546283/d52dcdc0-ce03-11e6-803c-fdc47621ec7b.png)

**Comment by JeffreyWay** [comment]
Can you do `rm -rf node_modules && npm install && node_modules/.bin/webpack`. Does it turn out differently?

**Comment by Bram-Zijp** [comment]
This and cleaning up my package.json solved the error running Laravel 5.3

**Comment by entozoon** [comment]
I keep ending up here debugging the same error but for a different reason - using yarn.
The problem being that the `yarn.lock` somehow ends up with broken packages and the solution, if it helps anyone, is simply to reset it all:
```
rm -rf node_modules
rm yarn.lock
yarn install
node_modules/.bin/webpack
```

**Comment by srikanthpullela** [comment]
Hi All,
I am getting the same issue while running the karma file.

`22 01 2018 12:41:10.996:ERROR [config]: Invalid config file!
  TypeError: webpack.LoaderOptionsPlugin is not a constructor
    at Object.<anonymous> (/Users/srikantpullea/schema-management-ui/webpack.config.js:70:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/srikantpullea/schema-management-ui/karma.conf.js:1:83)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.parseConfig (/usr/local/lib/node_modules/karma/lib/config.js:370:22)
    at new Server (/usr/local/lib/node_modules/karma/lib/server.js:79:20)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:283:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
`
"karma" : "2.0.0",
"karma-webpack": "^2.0.3",
"webpack": "^1.12.2"

Could you please let me know where I went wrong.
