### ISSUE TITLE
mix.js is not a function

### ISSUE THREAD

**Issue by ojabi** [JeffreyWay/laravel-mix#2406]
Laravel Mix 5.0.4
Node 10.15.2
Npm 6.15.4
Ubuntu Eaon

Laravel installed fresh, Laravel Mix installed fresh. webpack --config webpack.mix.js returns the error found below. 

Install Laravel
Install Laravel Mix
Run webpack --config webpack.mix.js

===ERROR===
TypeError: mix.js is not a function
    at Object.<anonymous> (/home/ojabi/Projects/jobslide/node_modules/laravel-mix/setup/webpack.mix.js:14:5)
    at Module._compile (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/ojabi/Projects/jobslide/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports.filename (/usr/lib/node_modules/webpack-cli/node_modules/import-local/index.js:16:66)
    at /usr/lib/node_modules/webpack-cli/bin/cli.js:15:6
    at Object.<anonymous> (/usr/lib/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by hebbet** [comment]
read this:
https://laravel.com/docs/7.x/mix#running-mix

**Comment by JannieT** [comment]
I got this when I got the build order wrong. This  webpack.mix.js resulted in "mix is not a function":

```
mix
    .setPublicPath("public")
    .ts("resources/ts/app.js", "assets").vue()
    .postCss(
        "resources/css/app.css",
        "assets",
        [require("tailwindcss")]
    )
    .copy("resources/images", "public/images")
    .sourceMaps()
    .version();
    ```
    
    And this one worked fine:
    
    ```
mix
    .setPublicPath("public")
    .copy("resources/images", "public/images")
    .ts("resources/ts/app.js", "assets").vue()
    .postCss(
        "resources/css/app.css",
        "assets",
        [require("tailwindcss")]
    )
    .sourceMaps()
    .version();
    ```
