### ISSUE TITLE
Uncaught TypeError: Cannot read property

### ISSUE THREAD

**Issue by chrisgrim** [JeffreyWay/laravel-mix#2410]
-   Laravel Mix Version: 5.0.4 (`npm list --depth=0`)
-   Node Version (`10.13.0`):
-   NPM Version (`6.12.0`):
-   OS: Mac OS Catalina

### Description:

If I try to  add .extract() to my webpack file and I run npm run watch I get the error: 
```
manifest.js:85 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (manifest.js:85)
    at Object../node_modules/css-loader/index.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/leaflet/dist/leaflet.css (vendor.js:168)
    at __webpack_require__ (manifest.js:85)
    at Object../node_modules/leaflet/dist/leaflet.css (vendor.js:14333)
    at __webpack_require__ (manifest.js:85)
    at Module../resources/js/app.js (app.js:3627)
    at __webpack_require__ (manifest.js:85)
    at Object.0 (app.js:4038)
    at __webpack_require__ (manifest.js:85)
    at checkDeferredModules (manifest.js:46)
```
the webpack file:
```
mix.sass('resources/sass/app-create.scss', 'public/css')
    .sass('resources/sass/app-admin.scss', 'public/css')
    .sass('resources/sass/app-lite.scss', 'public/css')
    .sass('resources/sass/app.scss', 'public/css')
    .js('resources/js/app.js', 'public/js')
    .extract(['vue','vuelidate','leaflet','vuelidate-error-extractor','vue-cookies']);
```
If I comment off .extract() it works and I get working js and css files. However, if I try to run npm run production I get a new error
```
CssSyntaxError: /css/app-create.css:902:13: Missed semicolon
    at Input.error (/Users/chrisgrim/code/ei/node_modules/postcss/lib/input.js:130:16)
    at Parser.checkMissedSemicolon (/Users/chrisgrim/code/ei/node_modules/postcss/lib/parser.js:603:22)
    at Parser.decl (/Users/chrisgrim/code/ei/node_modules/postcss/lib/parser.js:286:46)
    at Parser.other (/Users/chrisgrim/code/ei/node_modules/postcss/lib/parser.js:166:12)
    at Parser.parse (/Users/chrisgrim/code/ei/node_modules/postcss/lib/parser.js:77:16)
    at parse (/Users/chrisgrim/code/ei/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/Users/chrisgrim/code/ei/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/Users/chrisgrim/code/ei/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/Users/chrisgrim/code/ei/node_modules/postcss/lib/processor.js:117:23)
    at Function.creator.process (/Users/chrisgrim/code/ei/node_modules/postcss/lib/postcss.js:148:43)
    at OptimizeCssAssetsWebpackPlugin.processCss (/Users/chrisgrim/code/ei/node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
    at Object.processor (/Users/chrisgrim/code/ei/node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
    at each (/Users/chrisgrim/code/ei/node_modules/last-call-webpack-plugin/src/index.js:150:10)
    at arrayEach (/Users/chrisgrim/code/ei/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/chrisgrim/code/ei/node_modules/lodash/forEach.js:38:10)
    at OptimizeCssAssetsWebpackPlugin.process (/Users/chrisgrim/code/ei/node_modules/last-call-webpack-plugin/src/index.js:147:5)
    at compilation.hooks.optimizeChunkAssets.tapPromise.chunks (/Users/chrisgrim/code/ei/node_modules/last-call-webpack-plugin/src/index.js:178:28)
    at _next0 (eval at create (/Users/chrisgrim/code/ei/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:17)
    at _promise0.then._result0 (eval at create (/Users/chrisgrim/code/ei/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Thanks!

**Comment by chrisgrim** [comment]
Other similar questions in the git
