### ISSUE TITLE
Unexpectedly fails with css-loader v4.0.0

### ISSUE THREAD

**Issue by danielbachhuber** [JeffreyWay/laravel-mix#2450]
Just a heads up that I'm seeing this error with css-loader v4.0.0:

```
TypeError: text.forEach is not a function
    at childCompiler.runAsChild (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/extract-text-webpack-plugin/dist/loader.js:145:16)
    at compile (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/webpack/lib/Compiler.js:343:11)
    at hooks.afterCompile.callAsync.err (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/webpack/lib/Compiler.js:681:15)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/danielbachhuber/projects/foodbloggerpro/wp-content/node_modules/webpack/lib/Compiler.js:678:31)
```

Here's a corresponding thread on that repo: https://github.com/webpack-contrib/css-loader/issues/1135

The underlying culprit might be `extract-text-webpack-plugin`.

**Comment by rikless** [comment]
@JeffreyWay Hello, is there something to do on the laravel-mix side ?

**Comment by vishalmaisuria402** [comment]
Seems like it, I am facing the same issue with my clean Laravel 7 installations.

e.g error

`ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
TypeError: text.forEach is not a function
    at childCompiler.runAsChild ({app dir}\node_modules\laravel-mix\node_modules\extract-text-webpack-plugin\dist\loader.js:145:16)`

**Comment by dontfeedthecode** [comment]
Updating the package.json file in the Laravel root dir to require "laravel-mix": "6.0.0-alpha.1" fixed this for me.

**Comment by uran1980** [comment]
Hi, folks!

Have the same problem after update laravel-mix from ```"laravel-mix": "^5.0.4"``` to ```"laravel-mix": "^5.0.5"```

```npm run watch``` and ```npm run dev``` work without errors but ```npm run prod``` fire this errors:

```
ERROR in ./protected/modules/backend/views/assets-dev/sass/main/main.scss (./node_modules/css-loader/dist/cjs.js??ref--90-2!./node_modules/postcss-loader/src??postcss85!./node_modules/sass-loader/dist/cjs.js??ref--90-4!./protected/modules/backend/views/assets-dev/sass/main/main.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: decl.moveTo is not a function
```

eny ideas? Thanks

**Comment by JeffreyWay** [comment]
Fixed in upcoming release.

**Comment by joelpittet** [comment]
I'm seeing this in 5.0.9, what was the fix @JeffreyWay ?

I was seeing it come from ./node_modules/css-loader/dist/cjs.js when parsing less files.

**Comment by underdpt** [comment]
I'm having the same issue as @joelpittet, but am unable to find how to fix it. Any ideas?

**Comment by martsie** [comment]
Same issue with 5.0.9 - rolled back to 5.0.4 to fix issue.
