### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by ousid** [JeffreyWay/laravel-mix#2532]
-   Laravel Mix Version: ^5.0.1
-   Node Version 14.12.0:
-   NPM Version 6.14.8:
-   OS Linux (Arch Linux):

### Description:
I'm trying to compile JS/CSS assets for production, but after typing `npm run production` or `yarn run production` I get this error
```
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
```

### Steps To Reproduce:

- `npm install`
- `npm run dev`
- `npm run production`

### Error Log
```bash
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at /path/into/site/files/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:483
    at LazyResult.run (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at /path/into/site/files/node_modules/postcss/lib/lazy-result.js:250:14
    at new Promise (<anonymous>)
    at LazyResult.async (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:246:23)
    at LazyResult.then (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:127:17)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:212:17)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at /path/into/site/files/node_modules/postcss/lib/lazy-result.js:250:14
    at new Promise (<anonymous>)
    at LazyResult.async (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:246:23)
    at LazyResult.then (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:127:17)
    at /path/into/site/files/node_modules/postcss-loader/src/index.js:142:8
    at /path/into/site/files/node_modules/webpack/lib/NormalModule.js:316:20
    at /path/into/site/files/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /path/into/site/files/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/path/into/site/files/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /path/into/site/files/node_modules/postcss-loader/src/index.js:208:9
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/sass-loader/dist/cjs.js??ref--5-4!./resources/sass/app.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at /path/into/site/files/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:483
    at LazyResult.run (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at /path/into/site/files/node_modules/postcss/lib/lazy-result.js:250:14
    at new Promise (<anonymous>)
    at LazyResult.async (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:246:23)
    at LazyResult.then (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:127:17)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:212:17)
    at LazyResult.asyncTick (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:221:14)
    at /path/into/site/files/node_modules/postcss/lib/lazy-result.js:250:14
    at new Promise (<anonymous>)
    at LazyResult.async (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:246:23)
    at LazyResult.then (/path/into/site/files/node_modules/postcss/lib/lazy-result.js:127:17)
    at /path/into/site/files/node_modules/postcss-loader/src/index.js:142:8
 @ ./resources/sass/app.scss 2:14-196
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### SCSS code
https://gist.github.com/ousid/91c5887fb6dd4a79bf00f85646a434be

**Comment by JeffreyWay** [comment]
Include what's in your webpack.mix.js file.

**Comment by ousid** [comment]
Hey, @JeffreyWay here is what in `webpack.min.js` file
```js
const mix = require("laravel-mix");

require("laravel-mix-tailwind");

mix.js("resources/js/app.js", "public/js/app.js")
    .js("resources/js/follow.js", "public/js/follow.js")
    .js("resources/js/chart.js", "public/js/chart.min.js")
    .js("resources/js/carousel.js", "public/js/swiper.min.js")
    .sass("resources/sass/app.scss", "public/css/app.css")
    .tailwind("./tailwind.config.js")
    .sourceMaps();

if (mix.inProduction()) {
    mix.version();
}
```

**Comment by JeffreyWay** [comment]
Tough to say. Nothing immediately jumps out at me. 

Can you slowly chip away at your webpack.mix.js file until you're able to get the build to compile? Try to figure out exactly where the build blows up.

**Comment by speoman** [comment]
I had the exact same error because _I messed up_ the whitelist options in my tailwind.config.js ...

**Before (`purge:` was double)**
   ```
module.exports = {
       purge: [
            './vendor/laravel/jetstream/**/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php',
       ],
       purge: {
            // These options are passed through directly to PurgeCSS
            options: {
                whitelist: ['bg-red-500', 'px-4'],
            }
       },
       // ...
}
```


**Fixed**
```
module.exports = {
     purge: {
          content: [
              './vendor/laravel/jetstream/**/*.blade.php',
              './storage/framework/views/*.php',
              './resources/views/**/*.blade.php',
          ],

          // These options are passed through directly to PurgeCSS
          options: {
              whitelist: ['bg-red-500', 'px-4'],
          }
     },
     // ...
}
```

**Comment by ousid** [comment]
> I had the exact same error because _I messed up_ the whitelist options in my tailwind.config.js ...
> 
> **Before (`purge:` was double)**
> 
> ```
> module.exports = {
>     purge: [
>          './vendor/laravel/jetstream/**/*.blade.php',
>          './storage/framework/views/*.php',
>          './resources/views/**/*.blade.php',
>     ],
>     purge: {
>          // These options are passed through directly to PurgeCSS
>          options: {
>              whitelist: ['bg-red-500', 'px-4'],
>          }
>     },
>     // ...
> }
> ```
> 
> **Fixed**
> 
> ```
> module.exports = {
>      purge: {
>           content: [
>               './vendor/laravel/jetstream/**/*.blade.php',
>               './storage/framework/views/*.php',
>               './resources/views/**/*.blade.php',
>           ],
> 
>           // These options are passed through directly to PurgeCSS
>           options: {
>               whitelist: ['bg-red-500', 'px-4'],
>           }
>      },
>      // ...
> }
> ```

Thanks @speoman  Your Answer Solved the issue,
thanks @JeffreyWay  for your response, appreciate it.

**Comment by volb** [comment]
Thank you for the explanation! I accidentally had a `purge` block within a `purge` block, so changing it to `content` fixed it for me.

**Comment by mattienodj** [comment]
Hey folks. Just wanted to say, I had this error as well and this thread led me to the purge config as well, BUT mine was failing because it was commented. 

This broke:
```
  purge: {
    // enabled: true,
    // content: ['./src/**/*.js'],
  },
```

**Comment by fl-y** [comment]
Had the same error,
turns out I had `contents` instead of `content`.
