### ISSUE TITLE
mix.version() and mix.copyDirectory() together throw error. 

### ISSUE THREAD

**Issue by robertotcestari** [JeffreyWay/laravel-mix#2556]
-   Laravel Mix Version: 6.0.0-beta.10 (`npm list --depth=0`)
-   Node Version (`node -v`): v12.16.3
-   NPM Version (`npm -v`): 6.14.5
-   OS: Mac

### Description:
When using `mix.version()` and mix.copyDirectory()`, it throws an error:
```bash
Promise rejection: Error: EISDIR: illegal operation on a directory, read
[webpack-cli] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:524:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at File.read (/Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/File.js:207:19)
    at File.version (/Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/File.js:214:25)
    at Manifest.hash (/Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/Manifest.js:53:65)
    at /Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:99:26
    at Collection.each (/Users/robertotcestari/Programming/Production/trilhante/node_modules/collect.js/dist/methods/each.js:21:14)
    at CustomTasksPlugin.applyVersioning (/Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:98:37)
    at /Users/robertotcestari/Programming/Production/trilhante/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:16:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)```

```
I believe mix is trying to apply hash version to directories. 

### Steps To Reproduce:
On the same project, using `mix.copyDiretory()` and mix.version()`
Previous versions were ok.

**Comment by algm** [comment]
Just found the same error. Problem seems to be in the Manifest.js class where it is not checked if the file to be hashed is a directory or not before doing so. I worked it around by adding a try catch block in that method, but it also ended up adding the directories to the manifest file.

**Comment by Spice-King** [comment]
I've hit this as well. Works in beta 4, but not beta 5, so some intersection of [these commits](https://github.com/JeffreyWay/laravel-mix/compare/v6.0.0-beta.4...0f58b70) (beta 5 and 6 are missing tags, for some reason) but a quick skim of the commit messages points to 697c87c as a likely candidate for the change that broke it. I'll be using 4 until beta 11 or something comes along to fix it.
