### ISSUE TITLE
vue@next problem

### ISSUE THREAD

**Issue by Ojvar** [JeffreyWay/laravel-mix#2558]
Hi
I created the "src" folder, that contains two files:
  - main.ts
  - index.html

My webpack.mix.file contains:
  let mix = require("laravel-mix");
  mix.js("./src/main.ts", "public/");

main.ts file contains: 
   import { createApp } from "vue";

  createApp({
    data: () => ({
      name: "ali",
    }),
  }).mount("#app");

**I installed vue@next, then I ran "npm run watch" command.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'vue' in '/path/of/source/src'
 @ ./src/main.ts 1:0-32 3:0-9
 @ multi ./src/main.ts

How can i resolve that?

**Comment by rossgillies** [comment]
Adding `.vue()` to `mix.js("./src/main.ts", "public/");` should fix that

**Comment by Ojvar** [comment]
> Adding `.vue()` to `mix.js("./src/main.ts", "public/");` should fix that

I did this:
   mix.js("./src/frontend/scripts/pages/home.ts", "js/pages").vue();
but I get another error message

Is it wrong?

**Error message:** 

AssertionError [ERR_ASSERTION]: mix.js() is missing required parameter 1: entry
    at Function.js (/my-source-path/node_modules/laravel-mix/src/Assert.js:13:9)
    at JavaScript.register (/my-source-path/node_modules/laravel-mix/src/components/JavaScript.js:40:16)
    at Api.mix.<computed> [as vue] (/my-source-path/node_modules/laravel-mix/src/components/ComponentFactory.js:98:53)
    at Object.<anonymous> (/my-source-path/webpack.mix.js:56:5)
    at Module._compile (/my-source-path/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/my-source-path/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/my-source-path/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (/my-source-path/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/my-source-path/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/my-source-path/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/my-source-path/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /my-source-path/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/my-source-path/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /my-source-path/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/my-source-path/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
    at /my-source-path/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/my-source-path/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/my-source-path/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by Ojvar** [comment]
My project link:
https://github.com/ojvar/sunset-iv

Please get a clone (use **core_dev** branch)
and run: **npm run watch**

Don't forget: you should have mongod running

thanks

**Comment by ExpDev07** [comment]
@Ojvar ``mix.vue({ version: 3 })``

**Comment by Ojvar** [comment]
I did it, but I'm facing a problem again :D
when I add mix.vue({ version: 3 })
  npm run dev command show these results:

▶ npm run dev

> sunset-iv@1.0.0 dev /sourcePath/sunset-iv
> npm run development


> sunset-iv@1.0.0 development /sourcePath/sunset-iv
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/sourcePath/sunset-iv/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

AssertionError [ERR_ASSERTION]: mix.js() is missing required parameter 1: entry
    at Function.js (/sourcePath/sunset-iv/node_modules/laravel-mix/src/Assert.js:13:9)
    at JavaScript.register (/sourcePath/sunset-iv/node_modules/laravel-mix/src/components/JavaScript.js:40:16)
    at Api.mix.<computed> [as vue] (/sourcePath/sunset-iv/node_modules/laravel-mix/src/components/ComponentFactory.js:98:53)
    at Object.<anonymous> (/sourcePath/sunset-iv/webpack.mix.js:54:5)
    at Module._compile (/sourcePath/sunset-iv/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
....

**Comment by benjivm** [comment]
I'm also getting this on Vue 3. Removing the `vue({ version: 3})` installs `vue-template-compiler` and then the error from the first post: `Module not found: Error: Can't resolve 'vue' [...]`

Is anybody using Vue 3 with Laravel Mix?

**Comment by rossgillies** [comment]
@benjivm Your using laravel-mix 5, you need to install the 6 beta to use vue 3 `npm i laravel-mix@next`

**Comment by JeffreyWay** [comment]
@Ojvar You'll need to upgrade to the Mix v6 beta if you want to use Vue 3.

**Comment by iwasherefirst2** [comment]
I don't want to use Vue 3, but I have the same issue.  Using a fresh Laravel 8 application and using 
```
mix.js('resources/js/app.js', 'public/js')
   .vue();
```
as stated in the [docs](https://laravel.com/docs/8.x/mix#vue) will fail with 

```
AssertionError [ERR_ASSERTION]: mix.js() is missing required parameter 1: entry
```

**Comment by JeffreyWay** [comment]
@iwasherefirst2 You encountered that assertion error because you didn't have Mix v6 installed.

**Comment by Umar-malik007** [comment]
I've faced same error on laravel 8 when installing vue on it.

It's actually adding content in webpack.mix.js file like vue().

You encountered that assertion error because you didn't have Mix v6 installed.

So to update mix v5 v6 beta, run `npm i laravel-mix@next`

but if you don't want to update or use vue 3

the do the following:

replace vue() to the following:

`mix.js('resources/js/app.js', 'public/js')
.sass('resources/sass/app.scss', 'public/css');`

then run `npm run watch`

**Comment by ImFranQ** [comment]
i had same issue with react.
i solve changin `js` method by 'react'.

i changed:
```
mix.js('resources/js/app.js', 'public/js')
  .react()
  .sass('resources/sass/app.scss', 'public/css');
```

by

```
mix.react('resources/js/app.js', 'public/js')
  .sass('resources/sass/app.scss', 'public/css');
```

and :rocket:

**Comment by Rj-Aman** [comment]
> I've faced same error on laravel 8 when installing vue on it.
> 
> It's actually adding content in webpack.mix.js file like vue().
> 
> You encountered that assertion error because you didn't have Mix v6 installed.
> 
> So to update mix v5 v6 beta, run `npm i laravel-mix@next`
> 
> but if you don't want to update or use vue 3
> 
> the do the following:
> 
> replace vue() to the following:
> 
> `mix.js('resources/js/app.js', 'public/js') .sass('resources/sass/app.scss', 'public/css');`
> 
> then run `npm run watch`

Thanks man for the help. I spent more than 6 hr then used your method. It worked from me. Thanks a lot.

**Comment by Rj-Aman** [comment]
In Laravel 8

Add .vue() at last in webpack.mix.js like       ` .js('resources/js/app.js', 'public/js').vue()`
Run  `npm i laravel-mix@next`
Run `npm install vue` for installing vue
Now you can run `npm install && npm run dev`

**Comment by rehantoday** [comment]
The issue is the outdated Laravel-mix package. As suggested by @Rj-Aman , run `npm i laravel-mix@next` to update it.
