### ISSUE TITLE
[6.*] Add typings folder when publish the package

### ISSUE THREAD

**Issue by wahyubucil** [JeffreyWay/laravel-mix#2561]
-   Laravel Mix Version: 6.0.0-beta.10
-   Node Version: 12.19.0
-   NPM Version: 6.14.8
-   OS: macOS Catalina (10.15.7)

### Description:
I want to use the Laravel Mix typings, but because on `package.json` the typings folder doesn't exist on the `files` array, I couldn't get the typing when installing Laravel Mix on my project. I think it will be a simple change :)

### Steps To Reproduce:
- Install `laravel-mix@next`
- Create `webpack.mix.ts`
- Try to import laravel-mix like this: `import mix from 'laravel-mix'`, and the typing not work

**Comment by thecrypticace** [comment]
I knew I forgot something. 🤦

**Comment by arcanedev-maroc** [comment]
Wait a minute, you can `webpack.mix` in typescript ? That's amazing !!!

And thanks @thecrypticace, you're a lifesaver :heart:

**Comment by arcanedev-maroc** [comment]
Hi @wahyubucil, did the PR fixed your issue ?

After renaming the `webpack.mix.js` to `webpack.mix.ts`

I'm getting this issue when using `import mix from 'laravel-mix'`:

```
import * as mix from 'laravel-mix'
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (d:\Code\laravel-vue.test\node_modules\v8-compile-cache\v8-compile-cache.js:242:18)
    at Module._compile (d:\Code\laravel-vue.test\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (d:\Code\laravel-vue.test\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (d:\Code\laravel-vue.test\node_modules\laravel-mix\setup\webpack.config.js:3:1)
    at Module._compile (d:\Code\laravel-vue.test\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
```

Or i'm suppose to use mix like this: `let mix = require('laravel-mix')` ?

@thecrypticace Any idea how to fix this *issue* ?

**Comment by thecrypticace** [comment]
Typescript typings enable auto-completion and use of `// @ts-check`. It doesn't mean that you can use typescript in your mix file. Webpack would need to support that too which it doesn't afaik.

**Comment by wahyubucil** [comment]
@arcanedev-maroc You still need to compile it to Javascript, you can't directly use Typescript.

FYI, I'm using Laravel Mix with AdonisJS v5. Which is a Typescript based framework. That's why I can use `webpack.mix.ts` and the framework will compile it for me.
