### ISSUE TITLE
chunkModule.source is not a function

### ISSUE THREAD

**Issue by jcharcosset** [JeffreyWay/laravel-mix#2579]
-   Laravel Mix Version: 5.0.7
```
├── @fortawesome/fontawesome-svg-core@1.2.32
├── @fortawesome/free-solid-svg-icons@5.15.1
├── @fortawesome/vue-fontawesome@2.0.0
├── cross-env@7.0.2
├── deepmerge@4.2.2
├── fibers@5.0.0
├── laravel-mix@5.0.7
├── mini-css-extract-plugin@1.1.1
├── node-gyp@7.1.2
├── resolve-url-loader@3.1.2
├── sass-loader@9.0.3
├── sass@1.27.0
├── tiny-debounce@0.1.1
├── vue-auth@1.0.0-alpha.1
├── vue-extend-layout@2.0.6
├── vue-headful@2.1.0
├── vue-i18n@8.22.1
├── vue-router@3.4.7
├── vue-template-compiler@2.6.12
├── vue@2.6.12
├── vuetify-loader@1.6.0
├── vuetify@2.3.15
└── vuetifyjs-mix-extension@0.0.14
```
-   Node Version (`node -v`): 15.0.1
-   NPM Version (`npm -v`): 7.0.3
-   OS: OSX Catelina 10.15.6 (19G2021)

### Description:

Problem with `npm run prod` only : 
```bash
TypeError: chunkModule.source is not a function
    at Function.renderExtractedChunk (/Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.<anonymous> (/Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:313:46)
    at Array.forEach (<anonymous>)
    at /Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:301:25
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/user/Projects/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/user/Projects/project/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/user/Projects/project/node_modules/webpack/lib/Compilation.js:1405:32
    at eval (eval at create (/Users/user/Projects/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:296:11
    at /Users/user/Projects/project/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/user/Projects/project/node_modules/async/dist/async.js:1064:13)
    at /Users/user/Projects/project/node_modules/async/dist/async.js:969:16
    at /Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:274:13
    at /Users/user/Projects/project/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/user/Projects/project/node_modules/async/dist/async.js:1064:13)
    at /Users/user/Projects/project/node_modules/async/dist/async.js:969:16
    at /Users/user/Projects/project/node_modules/extract-text-webpack-plugin/dist/index.js:261:26
    at callback (/Users/user/Projects/project/node_modules/webpack/lib/Compilation.js:1223:5)
    at /Users/user/Projects/project/node_modules/webpack/lib/Compilation.js:1246:5
```
No problem with `npm run dev`

### Steps To Reproduce:

Create laravel project.
Add deps.
Run `npm run production`

**Comment by thecrypticace** [comment]
Does the issue go away if you install with `npm install --legacy-peer-deps`?

**Comment by jcharcosset** [comment]
Thank you.

I run
```bash
rm -r node_modules
rm package-lock.json
npm install --legacy-peer-deps
npm run prod
```

Unfortunately, same issue.

**Comment by JeffreyWay** [comment]
Was this project compiling properly before you upgraded to NPM 7?

**Comment by jcharcosset** [comment]
No, I tried to upgrade to npm 7.x because there was the error

**Comment by goper-leo** [comment]
What I did is to upgrade to laravel-mix 6
