### ISSUE TITLE
[6.*] Error: compiling RuleSet failed: Unexpected property test in condition

### ISSUE THREAD

**Issue by jakedowns** [JeffreyWay/laravel-mix#2613]
-   Laravel Mix Version:  laravel-mix `6.0.0-beta.14` 
-   Node Version (`node -v`): `v12.18.1`
-   NPM Version (`npm -v`): `v6.14.5`
-   OS: Ubuntu 18.0.4 on WSL2 on Windows 10

### Description:
This is a reduced test case for an issue i ran into while trying to upgrade a Vue 2 project from laravel-mix `^2.1.14`

### Steps To Reproduce:
`package.json`
```
{
        "private": true,
        "devDependencies": {
                "babel-preset-minify": "^0.5.1",
                "laravel-mix": "^6.0.0-beta.14",
                "postcss": "^8.1.7",
                "webpack": "^5.4.0"
        },
        "dependencies": {},
        "scripts": {
                "dev": "npm run development",
                "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
                "watch": "npm run development -- --watch",
                "watch-poll": "npm run watch -- --watch-poll",
                "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
                "prod": "npm run production",
                "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
        }
}
```

`webpack.mix.js`
```
let mix = require("laravel-mix");
mix
  .js("resources/assets/js/app/index.js", "./public/dist/app.js")
  .vue()
```

i tried `.vue({version: 2})` and it did not behave any differently 

### Error Output:
```
3% setup run[webpack-cli] Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:365:10)
    at RuleSetCompiler.compileCondition (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:301:17)
    at /root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/BasicMatcherRulePlugin.js:29:40
    at Hook.eval [as call] (eval at create (/root/LinuxBindMounted/wright/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
    at RuleSetCompiler.compileRule (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:175:19)
    at /root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:152:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:151:16)
    at RuleSetCompiler.compileRule (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:182:30)
    at /root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:152:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:151:16)
    at RuleSetCompiler.compile (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/rules/RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/NormalModuleFactory.js:198:34)
    at Compiler.createNormalModuleFactory (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/Compiler.js:948:31)
    at Compiler.newCompilationParams (/root/LinuxBindMounted/wright/app/node_modules/webpack/lib/Compiler.js:967:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T03_20_38_126Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-13T03_20_38_182Z-debug.log
```

for this test `index.js` just has a simple `let a = "foobar"` statement 

`.babelrc`
```
{
  "presets": [["@babel/preset-env", { "modules": false }]],
  "plugins":[
    "@babel/plugin-proposal-class-properties"
  ],
  "env": {
      "test": {
        "presets": [["@babel/preset-env", { "targets": { "node": "current" } }]]
      },
      "production": {
        "presets": ["minify"]
      }
  }
}
```

trying to do a little debugging in RuleSetCompiler.js

this is what i get if i add a console.log at the top of:
```
compileCondition(path, condition) {
		console.log(path, condition);
```

```
ruleSet[0].rules[1].mimetype application/node
ruleSet[0].rules[2].test /\.json$/i
ruleSet[0].rules[3].mimetype application/json
ruleSet[0].rules[4].test /\.mjs$/i
ruleSet[0].rules[5].test /\.js$/i
ruleSet[0].rules[5].descriptionData.type module
ruleSet[0].rules[6].test /\.cjs$/i
ruleSet[0].rules[7].test /\.js$/i
ruleSet[0].rules[7].descriptionData.type commonjs
ruleSet[0].rules[8].mimetype { or: [ 'text/javascript', 'application/javascript' ] }
ruleSet[0].rules[8].mimetype.or [ 'text/javascript', 'application/javascript' ]
ruleSet[0].rules[8].mimetype.or[0] text/javascript
ruleSet[0].rules[8].mimetype.or[1] application/javascript
ruleSet[0].rules[9].dependency url
ruleSet[1].rules[0].resourceQuery [Function: resourceQuery]
ruleSet[1].rules[1].resource { test: [Function: test] }
[webpack-cli] Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
```

The whole config as generated by laravel-mix and passed to webpack:

https://gist.github.com/jakedowns/f957c0a9b13943a60e405ad57d3be0fe

**Comment by jakedowns** [comment]
note: same with node v12.14.1

**Comment by CristianDeluxe** [comment]
Same error with a fresh installation of Laravel 8, I have installed Vue 3 and updated the Laravel Mix to version 6, I am also using node v7:

`npm run watch

> watch
> mix watch

3% setup watch run webpack-cli[webpack-cli] Compilation starting...
3% setup watch run[webpack-cli] Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:367:10)
    at RuleSetCompiler.compileCondition (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:303:17)
    at /Users/X/Proyectos/X/node_modules/webpack/lib/rules/BasicMatcherRulePlugin.js:29:40
    at Hook.eval [as call] (eval at create (/Users/X/Proyectos/X/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:17:1)
    at RuleSetCompiler.compileRule (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:177:19)
    at /Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compileRule (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:184:30)
    at /Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:154:9
    at Array.map (<anonymous>)
    at RuleSetCompiler.compileRules (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:153:16)
    at RuleSetCompiler.compile (/Users/X/Proyectos/X/node_modules/webpack/lib/rules/RuleSetCompiler.js:68:22)
    at new NormalModuleFactory (/Users/X/Proyectos/X/node_modules/webpack/lib/NormalModuleFactory.js:198:34)
    at Compiler.createNormalModuleFactory (/Users/X/Proyectos/X/node_modules/webpack/lib/Compiler.js:993:31)
    at Compiler.newCompilationParams (/Users/X/Proyectos/X/node_modules/webpack/lib/Compiler.js:1012:30)
npm ERR! code 2
npm ERR! path /Users/X/Proyectos/X
npm ERR! command failed
npm ERR! command sh -c webpack --progress --watch '--config=/Users/X/Proyectos/X/node_modules/laravel-mix/setup/webpack.config.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/X/.npm/_logs/2020-12-20T01_10_34_296Z-debug.log`

**Comment by Calvin-LL** [comment]
This is a problem with `vue-loader`, you can see the code mentioned in the error here: https://github.com/vuejs/vue-loader/blob/master/lib/plugin-webpack5.js#L171

**Comment by ScorpioT1000** [comment]
In my case it was Webpack encore 1.*, installed 0.30 and it's fixed

**Comment by EvgnEkb** [comment]
Запустите команду `npm install vue-loader`

**Comment by LowSociety** [comment]
I solved this issue by running `yarn add vue-loader@next` – haven't dug deeper but it seems like my version was incompatible with something else.

**Comment by alokVishu** [comment]
It works for me. I just add below two package.

   "vue-loader": "^16.1.2",
   "@vue/compiler-sfc": "^3.0.4",

**Comment by vedmant** [comment]
Yeah, Id' never guess that it needs vue-loader by this cryptic error message, shouldn't laravel-mix install it automatically like it's installing sass-loader for example?
