### ISSUE TITLE
TypeError: mix.saas is not a function

### ISSUE THREAD

**Issue by marknown** [JeffreyWay/laravel-mix#2618]
-   Laravel Mix Version: 5.0.7
-   Node Version (`node -v`): v14.4.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: macOS Catalina 10.15.7

### Description:
when i run `npm run dev` under Laravel Framework 8.13.0 root directory a error occurred.

### Steps To Reproduce:
1. `npm run dev` under Laravel Framework 8.13.0
2. output is below:
```
> @ dev /Users/jack/apps/laravel8
> npm run development


> @ development /Users/jack/apps/laravel8
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/jack/apps/laravel8/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

TypeError: mix.saas is not a function
    at Object.<anonymous> (/Users/jack/apps/laravel8/webpack.mix.js:14:5)
    at Module._compile (/Users/jack/apps/laravel8/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/jack/apps/laravel8/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/jack/apps/laravel8/node_modules/laravel-mix/setup/webpack.config.js:12:1)
    at Module._compile (/Users/jack/apps/laravel8/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (/Users/jack/apps/laravel8/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/jack/apps/laravel8/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/jack/apps/laravel8/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/jack/apps/laravel8/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/jack/apps/laravel8/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /Users/jack/apps/laravel8/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/Users/jack/apps/laravel8/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
    at /Users/jack/apps/laravel8/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/jack/apps/laravel8/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/jack/apps/laravel8/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jack/.npm/_logs/2020-11-18T01_41_58_972Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jack/.npm/_logs/2020-11-18T01_41_58_999Z-debug.log
```

3. /Users/jack/.npm/_logs/2020-11-18T01_41_58_999Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/14.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jack/apps/laravel8/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/jack/apps/go/bin:/Users/jack/.composer/vendor/bin
9 verbose lifecycle @~dev: CWD: /Users/jack/apps/laravel8
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid @
15 verbose cwd /Users/jack/apps/laravel8
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/Cellar/node/14.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v14.4.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
4. webpack.mix.js 
```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.saas('resources/css/h5.scss', 'public/css/h5.css')
```

5. h5.scss
```
#app {
    .mint-radiolist-title {
        font-size: 14px;
    }
}
```

6. package.json
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "resolve-url-loader": "^3.1.0",
        "vue-template-compiler": "^2.6.12"
    }
}
```

**Comment by jonXmack** [comment]
The function you need is `mix.sass` not `mix.saas` (two s's vs two a's).

**Comment by marknown** [comment]
it's my problem. thank you!
