### ISSUE TITLE
[6.0.0-beta.14] 'HookWebpackError: item.node is not a function' on prod build

### ISSUE THREAD

**Issue by zaxn1234** [JeffreyWay/laravel-mix#2649]
-   Laravel Mix Version: laravel-mix@6.0.0-beta.14 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.11.0
-   NPM Version (`npm -v`): 7.0.15
-   OS: macOS Catalina 10.15.7

### Description:
Whenever I try to do a production build (`mix --production`) I get the following error:

```
[webpack-cli] HookWebpackError: item.node is not a function
    at makeWebpackError (node_modules/webpack/lib/HookWebpackError.js:49:9)
    at node_modules/webpack/lib/Compilation.js:2107:11
    at eval (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:55:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: item.node is not a function
    at node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at node_modules/terser-webpack-plugin/dist/index.js:323:27
    at node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:23:31
    at run (node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:23:43)
    at node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:45:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
caused by plugins in Compilation.hooks.processAssets
TypeError: item.node is not a function
    at node_modules/webpack-sources/lib/ConcatSource.js:59:50
    at Array.map (<anonymous>)
    at ConcatSource.node (node_modules/webpack-sources/lib/ConcatSource.js:58:63)
    at ConcatSource.proto.sourceAndMap (node_modules/webpack-sources/lib/SourceAndMapMixin.js:29:18)
    at node_modules/terser-webpack-plugin/dist/index.js:323:27
    at node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:23:31
    at run (node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:23:43)
    at node_modules/terser-webpack-plugin/node_modules/p-limit/index.js:45:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

I can run a *dev build perfectly fine*, this only happens on the production build.
Unfortunately I cannot supply much code/a repo as it's a big company project however here is my `webpack.mix.js` file.

```
const mix = require('laravel-mix');

const CKEditorWebpackPlugin = require( '@ckeditor/ckeditor5-dev-webpack-plugin' );
const CKEStyles = require('@ckeditor/ckeditor5-dev-utils').styles;
const CKERegex = {
    svg: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
    css: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
};

Mix.listen('configReady', webpackConfig => {
    const rules = webpackConfig.module.rules;
    const targetSVG = /(\.(png|jpe?g|gif|webp)$|^((?!font).)*\.svg$)/;
    const targetFont = /(\.(woff2?|ttf|eot|otf)$|font.*\.svg$)/;
    const targetCSS = /\.css$/;

    // exclude CKE regex from mix's default rules
    for (let rule of rules) {
        if (rule.test.toString() === targetSVG.toString()) {
            rule.exclude = CKERegex.svg;
        }
        else if (rule.test.toString() === targetFont.toString()) {
            rule.exclude = CKERegex.svg;
        }
        else if (rule.test.toString() === targetCSS.toString()) {
            rule.exclude = CKERegex.css;
        }
    }
});

mix.webpackConfig(webpack => { 
    return {
        plugins: [
            new webpack.DefinePlugin({
                '__VUE_OPTIONS_API__': 'true',
                '__VUE_PROD_DEVTOOLS__': 'false'
            })
        ]
    }
});

mix.options({
    processCssUrls: false
});

// For production version control the files and run babel
// to transpile JS to ES5 files so compatible with IE11
if (mix.inProduction()) {
    mix.version()
        .babel(['public/js/admin/app.js'], 'public/js/admin/app.es5.js')
        .babel(['public/js/app.js'], 'public/js/app.es5.js');
}

mix.js('resources/assets/js/admin/app.js', 'public/js/admin')
    .js('resources/assets/js/app.js', 'public/js')
    .sourceMaps()
    .vue();
    
mix.sass('resources/assets/sass/admin/app.scss', 'public/css/admin')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sourceMaps();
    
mix.browserSync({
    proxy: 'https://dev-site.test',
    files: [
        'public/css/admin/app.css',  // Generated admin .css file
        'public/css/app.css',  // Generated front .css file
        'public/js/admin/app.js',    // Generated admin .js file
        'public/js/app.js',    // Generated front .js file
        'laravel/resources/views/**/*.php',  // Laravel-specific view files
    ]
});

mix.webpackConfig({
    plugins: [
        new CKEditorWebpackPlugin({
            language: 'en',
            addMainLanguageTranslationsToAllAssets: true
        })
    ],
    module: {
        rules: [
            {
                test: /ckeditor5-[^\/\\]+[\/\\].+\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            },
            {
                test: CKERegex.svg,
                use: [ 'raw-loader' ]
            },
            {
                test: CKERegex.css,
                use: [
                    {
                        loader: 'style-loader',
                        options: {
                            injectType: "singletonStyleTag"
                        }
                    },
                    {
                        loader: 'postcss-loader',
                        options: CKEStyles.getPostCssConfig({
                            themeImporter: {
                                themePath: require.resolve('@ckeditor/ckeditor5-theme-lark')
                            },
                            minify: true
                        })
                    },
                ]
            }
        ]
    }
});
```

If it helps to know:
All CKEditor modules are v23.1.0,
Vue is v3.0.3, Vue-loader is v16.0.0
Laravel v6.18.42

I've tried everything I can think of including nuking the `node_modules` folder, switching package versions and I even moved from npm 6 to npm 7 too. 

### Steps To Reproduce:
Run `mix --production`

**Comment by parkerault** [comment]
Hah, I got this error too, and this is the only search result. 😂 

I'm using typescript, css modules, and react. Here's my webpack config:

```ts
import { resolve } from "path";
import CopyWebpackPlugin from "copy-webpack-plugin";
import MiniCssExtractPlugin from "mini-css-extract-plugin";
import HtmlWebpackPlugin from "html-webpack-plugin";
import ExtensionReloaderPlugin from "webpack-extension-reloader";
import { Compiler } from "webpack";
import { Configuration } from "webpack";
import { CleanWebpackPlugin } from "clean-webpack-plugin";

const paths = {
  root: resolve(__dirname),
  build: resolve(__dirname, "build"),
  public: resolve(__dirname, "public"),
  src: resolve(__dirname, "src"),
  manifest: resolve(__dirname, "src/manifest.json"),
  popup: resolve(__dirname, "src/popup.tsx"),
  pageTemplate: resolve(__dirname, "src/pageTemplate.hbs")
};

const rules = [
  {
    test: /\.tsx?$/,
    include: paths.src,
    loader: "ts-loader",
  },
  {
    test: /\.module\.css$/,
    include: paths.src,
    use: [
      "style-loader",
      "@teamsupercell/typings-for-css-modules-loader",
      {
        loader: "css-loader",
        options: {
          modules: true
        }
      }
    ],
  },
];

const mode = process.env.NODE_ENV;

const plugins: Configuration["plugins"] = [
  new MiniCssExtractPlugin({ filename: "style.css" }),
  new CopyWebpackPlugin({
    patterns: [paths.manifest, paths.public],
  }),
  new HtmlWebpackPlugin({
    filename: "background.html",
    template: paths.pageTemplate,
    chunks: ["background"],
    appMountIds: "root",
  }),
  new HtmlWebpackPlugin({
    filename: "popup.html",
    template: paths.pageTemplate,
    chunks: ["popup"],
    appMountId: "root",
  }),
  new HtmlWebpackPlugin({
    filename: "options.html",
    template: paths.pageTemplate,
    chunks: ["options"],
    appMountId: "root",
  }),
  new CleanWebpackPlugin({
    cleanAfterEveryBuildPatterns: ["*.LICENSE.txt"],
  }),
];
if (mode === "development") {
  plugins.push(
    new (ExtensionReloaderPlugin as typeof ExtensionReloaderIsFucked)({
      manifest: resolve(paths.src, "manifest.json"),
    }),
  );
}

const optimization: Configuration["optimization"] = {
  runtimeChunk: "single",
  splitChunks: {
    cacheGroups: {
      vendor: {
        name: "vendor",
        test: /[\\/]node_modules[\\/](react|react-dom|redux|react-redux|webext-redux)[\\/]/,
        chunks: "all",
        reuseExistingChunk: true,
      },

      /**
       * Creating seperate chunks for each CSS file
       */

      contentStyles: {
        name: "contentStyles",
        test: "content.module.css",
        chunks: "all",
        enforce: true,
      },
    },
  },
};

const configuration: Configuration = {
  devtool: "inline-source-map",

  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx", ".json", ".module.css"],
    roots: [paths.src]
  },

  entry: {
    background: resolve(paths.src, "background.ts"),
    content: resolve(paths.src, "content.ts"),
    popup: resolve(paths.src, "popup.tsx"),
    options: resolve(paths.src, "options.tsx"),
  },

  output: {
    publicPath: "",
    path: paths.build,
    filename: "[name].bundle.js",
    libraryTarget: "umd",
  },

  optimization,
  plugins,
  module: {
    rules,
  },
};

function buildManifest(content: Buffer): string | Buffer {
  try {
    const manifest = JSON.parse(content.toString());
  } catch(e) {
    const {name, message} = e as Error;
    console.warn(`${name}: ${message}`)
  }
  return content;
}

export default configuration;

/**
 * This is crap, but the type definitions for ExtensionReloaderPlugin are
 * broken and the maintainer is not merging PRs, so this is the only quick way
 * to fix it.
 */

interface IEntriesOption {
  contentScript: string;
  background: string;
  extensionPage: string;
}

interface IPluginOptions {
  port?: number;
  reloadPage?: boolean;
  manifest?: string;
  entries?: IEntriesOption;
}

declare class ExtensionReloaderIsFucked {
  constructor(options?: IPluginOptions);
  apply(compiler: Compiler): void;
}
```

**Comment by ookblah** [comment]
@zaxn1234 Not sure if you figured it out, but I have a webpack build from scratch using ckeditor5 and vue2.  If I remove the plugin "CKEditorWebpackPlugin" from the config (it's only needed for localisation) then I'm able to build production.  Leaving it in there throws the error.

**Comment by amatyas001** [comment]
Hi, according to the error message it's related to the source maps. I faced this issue as well and removed `devtool` entry from the config. It works, though heavy tradeoffs. Any better solution?

**Comment by uluhonolulu** [comment]
Dear @stale, please don't close it!

I have the same error with webpack 5.47.1

In my case, `item` is of type `CachedSource` and doesn't have a `node` function.

**Comment by uluhonolulu** [comment]
Rolling back to 5.24.2 fixed the issue

**Comment by konstantin-tw** [comment]
We also see the same issue in 5.47.0 and 5.47.1
Removing `devtools` doesn't help.
Any ideas what the root cause can be? Thx!

**Comment by lmk123** [comment]
I just upgraded webpack from 5.46.0 to 5.50.0 and got this error, roll back to 5.46.0 and the error is gone.

**Comment by lmk123** [comment]
After some experimentation, I found that this is not a webpack problem.

I used [webpack-extension-reloader](https://github.com/rubenspgcavalcante/webpack-extension-reloader) in my project, but it only supports webpack v4. Once I removed this plugin, the project worked fine, even after using devtools `inline-source-map`.

**Comment by valoni01** [comment]
@zaxn1234  did you ever get the culprit of your issue?
