### ISSUE TITLE
Issue with Plugin + Vue Loader

### ISSUE THREAD

**Issue by matthew-kerle** [JeffreyWay/laravel-mix#2715]
-   Laravel Mix Version: `6.0.5`
-   Node Version: `v.14.3.0`
-   Yarn Version: `1.22.4`
-   OS: MacOS

### Description:
When I run `yarn run prod` using `laravel-mix`, I am getting the following error, which seems to be an issue of how laravel-mix composes its webpack config. Any help here would be appreciated! 🙏 

**Error:**
```
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js
[webpack-cli] Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
```

**Webpack Config Base:**
```
const path = require('path');
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

module.exports = {
    plugins: [new VuetifyLoaderPlugin()],
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            vue$: 'vue/dist/vue.esm.js',
            '@': path.resolve(__dirname, 'src'),
            '~': path.resolve(__dirname, '../'),
        },
    },
};

```

**Mix Config:**
```
const mix = require('laravel-mix');
const baseWebpackConfig = require('./webpack.config');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.webpackConfig(baseWebpackConfig);

const vendors = ['axios', 'lodash', 'lodash-es', 'vue', 'vuetify'];

mix.setPublicPath('../public');

mix.copy('images/*', '../public/images/');

mix.js('src/app.js', 'js/').extract(vendors).sourceMaps();

mix.sass('sass/app.scss', 'css/');

if (mix.inProduction()) {
    mix.version();
}
```

**Comment by JeffreyWay** [comment]
If you're using Vue, make sure you add `mix.vue()` to your webpack.mix.js file.

**Comment by matthew-kerle** [comment]
@JeffreyWay that causes another error:

```
$ cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js
[webpack-cli] Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": {},
  "use": [
    {
      "loader": "babel-loader",
      "options": {
        "presets": [
          [
            "/Users/matthewkerle/repos/erp/frontend/node_modules/@babel/preset-env/lib/index.js",
            {
              "modules": false,
              "forceAllTransforms": true
            }
          ]
        ],
        "plugins": [
          "/Users/matthewkerle/repos/erp/frontend/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js",
          "/Users/matthewkerle/repos/erp/frontend/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js",
          [
            "/Users/matthewkerle/repos/erp/frontend/node_modules/@babel/plugin-transform-runtime/lib/index.js",
            {
              "helpers": false
            }
          ]
        ],
        "cacheDirectory": true
      },
      "ident": "clonedRuleSet-5[0].rules[0].use[0]"
    }
  ]
}
    at checkResourceSource (/Users/matthewkerle/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/Users/matthewkerle/node_modules/webpack/lib/RuleSet.js:198:4)
    at /Users/matthewkerle/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/Users/matthewkerle/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/Users/matthewkerle/node_modules/webpack/lib/RuleSet.js:104:24)
    at VuetifyLoaderPlugin.apply (/Users/matthewkerle/repos/erp/frontend/node_modules/vuetify-loader/lib/plugin.js:22:23)
    at createCompiler (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack/lib/webpack.js:69:12)
    at create (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack/lib/webpack.js:113:15)
    at webpack (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack/lib/webpack.js:121:46)
    at f (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack/lib/index.js:37:15)
    at WebpackCLI.createCompiler (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack-cli/lib/webpack-cli.js:1093:24)
    at async WebpackCLI.bundleCommand (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack-cli/lib/webpack-cli.js:1217:20)
    at async Command.<anonymous> (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack-cli/lib/webpack-cli.js:271:21)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/matthewkerle/repos/erp/frontend/node_modules/webpack-cli/lib/webpack-cli.js:652:13)
```

Any ideas?

**Comment by JeffreyWay** [comment]
Hmm - it seems like vuetify-loader hasn't yet been updated to support webpack 5.

https://github.com/vuetifyjs/vuetify-loader/pulls

**Comment by matthew-kerle** [comment]
@JeffreyWay oh nice find, I appreciate you taking the time to look into this issue for me. Have a great New Years, cheers!
