### ISSUE TITLE
Cannot read property 'hmr' of undefined

### ISSUE THREAD

**Issue by sertn** [JeffreyWay/laravel-mix#2718]
-   Laravel Mix Version: 6.0.5 (`npm list --depth=0`)
-   Node Version : v14.15.3
-   NPM Version : 6.14.9
-   OS: Widows 10 Pro /64bit

### Description:

When I run the "npx run watch" command, I get the following error.

```
[webpack-cli] TypeError: Cannot read property 'hmr' of undefined
    at Object.<anonymous> (C:\vue-project\x-tools\webpack.mix.js:59:26)
    at Module._compile (C:\vue-project\x-tools\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\vue-project\x-tools\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at module.exports (C:\vue-project\x-tools\node_modules\laravel-mix\setup\webpack.config.js:3:5)
    at C:\vue-project\x-tools\node_modules\webpack-cli\lib\webpack-cli.js:720:43
    at Array.map (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ watch: `mix watch`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pcm\AppData\Roaming\npm-cache\_logs\2020-12-29T06_59_32_296Z-debug.log
```

### Steps To Reproduce:
This is my current webpackConfig content.

```
const path = require('path')
const fs = require('fs-extra')
const mix = require('laravel-mix')
require('laravel-mix-versionhash')
const tailwindcss = require('tailwindcss')
const {CleanWebpackPlugin} = require('clean-webpack-plugin')

mix
    .js('resources/js/app.js', 'public/dist/js')
    .options({
        processCssUrls: false,
        postCss: [tailwindcss('./tailwind.config.js')]
    }).postCss('resources/sass/app.css', 'public/dist', [require('tailwindcss')])




if (mix.inProduction()) {
    mix
        .versionHash()
} else {
    mix.sourceMaps()
}
mix.webpackConfig({
    mode: "development",
    devtool: "inline-source-map",
    devServer: {
        disableHostCheck: true,
        headers: {
            'Access-Control-Allow-Origin': '*'
        },
        host: "web",
        port: 80
    },
    plugins: [
        new CleanWebpackPlugin()
    ],
    resolve: {
        extensions: ['.js', '.json', '.vue'],
        alias: {
            '@': path.join(__dirname, './resources/js')
        }
    },
    output: {
        chunkFilename: 'dist/js/[chunkhash].js',
        path: mix.config.hmr ? '/' : path.resolve(__dirname, './public/build')

    }
})

mix.then(() => {
    if (!mix.config.hmr) {
        process.nextTick(() => publishAseets())
    }
})

function publishAseets() {
    const publicDir = path.resolve(__dirname, './public')

    if (mix.inProduction()) {
        fs.removeSync(path.join(publicDir, 'dist'))
    }

    fs.copySync(path.join(publicDir, 'build', 'dist'), path.join(publicDir, 'dist'))
    fs.removeSync(path.join(publicDir, 'build'))
}
```

**Comment by RefreshEnterAbel** [comment]
the same problem happens to me  Please help how can fix this case

**Comment by EspetoRx** [comment]
OU Alguém conseguiu resolver isso daí??? Smbdy solve this?

**Comment by sertn** [comment]
I solved it by removing "hmr".

**Comment by sertn** [comment]
```
mix.then(() => {
    if (!mix.config.hmr) {
        process.nextTick(() => publishAseets())
    }
})
```

to 

```
mix.then(() => {
  if (mix.inProduction()) {
    process.nextTick(() => publishAseets())
  }
})
```

before
` path: mix.config.hmr ? '/' : path.resolve(__dirname, './public/build')`

after
`path: path.resolve(__dirname, './public/build')`

**Comment by Peken-bower** [comment]
> mix.then(() => {
>   if (mix.inProduction()) {
>     process.nextTick(() => publishAseets())
>   }
> }

is not fixed i get this error 

[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received function chunkFilename
    at validateString (internal/validators.js:122:11)
    at Object.dirname (path.js:1128:5)
    at VersionHash.webpackConfig (/home/around-pfe/public_html/node_modules/laravel-mix-versionhash/src/index.js:78:34)
    at /home/around-pfe/public_html/node_modules/laravel-mix/src/components/ComponentRegistrar.js:124:54
    at /home/around-pfe/public_html/node_modules/laravel-mix/src/Dispatcher.js:39:62
    at Array.map (<anonymous>)
    at Dispatcher.fire (/home/around-pfe/public_html/node_modules/laravel-mix/src/Dispatcher.js:39:47)
    at Mix.dispatch (/home/around-pfe/public_html/node_modules/laravel-mix/src/Mix.js:248:32)
    at WebpackConfig.build (/home/around-pfe/public_html/node_modules/laravel-mix/src/builder/WebpackConfig.js:37:24)
    at async loadConfigByPath (/home/around-pfe/public_html/node_modules/webpack-cli/lib/webpack-cli.js:1747:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by DrZiLLo** [comment]
@Peken-bower did you solve this problem?
