### ISSUE TITLE
Mix hot - font directory issue

### ISSUE THREAD

**Issue by xf039** [JeffreyWay/laravel-mix#2731]
-   Laravel Mix Version: 6.0.0-beta.17
-   Node Version: v14.15.3
-   NPM Version: 6.14.9
-   OS: Windows 10 19041.685

### Description:
Mix hot throws a directory exception:
```
C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:141
                throw new Error(
                ^

Error: \fonts\vendor\@fortawesome\fontawesome-pro\webfa-brands-400.eot is neither a posix nor a windows path, and there is no 'dirname' method defined in the file system
    at dirname (C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:141:9)
    at C:\wamp64\www\project\node_modules\webpack\lib\Compiler.js:790:19
    at arrayIterator (C:\wamp64\www\project\node_modules\neo-async\async.js:3467:9)
    at timesSync (C:\wamp64\www\project\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (C:\wamp64\www\project\node_modules\neo-async\async.js:3463:5)
    at emitFiles (C:\wamp64\www\project\node_modules\webpack\lib\Compiler.js:536:13)
    at C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:182:5
    at Immediate.<anonymous> (C:\wamp64\www\project\node_modules\memfs\lib\volume.js:684:17)
    at processImmediate (internal/timers.js:461:21)
```
### Steps To Reproduce:
1. Adding the `@fortawesome/fontawesome-pro` package
2. Running `mix watch --hot`

**Comment by xf039** [comment]
Issue overlap with #2666

**Comment by J-Brk** [comment]
I believe this issue is caused by webpack and have opened an issue.
https://github.com/webpack/webpack/issues/12305
