### ISSUE TITLE
[webpack-cli] Error: Universal Chunk Loading is not implemented yet

### ISSUE THREAD

**Issue by asolopovas** [JeffreyWay/laravel-mix#2736]
-   Laravel Mix Version: 6.0.6 (`npm list --depth=0`)
```
├── @babel/plugin-syntax-import-meta@7.10.4
├── @types/lodash@4.14.167
├── autoprefixer@10.1.0
├── axios@0.21.1
├── babel-plugin-lodash@3.3.4
├── browser-sync@2.26.13
├── browser-sync-webpack-plugin@2.3.0
├── cross-env@7.0.3
├── laravel-mix@6.0.6
├── lazysizes@5.2.2
├── lodash@4.17.20
├── photoswipe@4.1.3
├── postcss@8.2.2
├── resolve-url-loader@3.1.2
├── sass@1.32.0
├── sass-loader@8.0.2
├── swiper@6.4.5
├── ts-loader@8.0.13
├── typescript@4.1.3
└── when-dom-ready@1.2.12
```
-   Node Version (`node -v`):14.15.1
I also tested 15.5.0 but it had the same result
-   NPM Version (`npm -v`):6.14.10
-   OS:Linux 5.9.14-arch1-1

### Description:
`npx mix` causes the following behaviour:
```
[webpack-cli] Error: Universal Chunk Loading is not implemented yet
    at EnableChunkLoadingPlugin.apply (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/javascript/EnableChunkLoadingPlugin.js:104:12)
    at WebpackOptionsApply.process (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/WebpackOptionsApply.js:146:40)
    at createCompiler (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/webpack.js:76:28)
    at create (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/webpack.js:113:15)
    at webpack (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/webpack.js:121:46)
    at f (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack/lib/index.js:37:15)
    at WebpackCLI.createCompiler (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack-cli/lib/webpack-cli.js:1165:24)
    at async WebpackCLI.bundleCommand (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack-cli/lib/webpack-cli.js:1292:20)
    at async Command.<anonymous> (/home/andrius/www/test.test/wp-content/themes/theme/node_modules/webpack-cli/lib/webpack-cli.js:322:21)
    at async Promise.all (index 1)
```
### Steps To Reproduce:
webpack.mix.js:
```
#!/usr/bin/env bash
let mix = require('laravel-mix')

mix.ts('src/js/test.js', 'static/js').webpackConfig({
    resolve: {
        alias: {
            'photoSwipe': 'photoswipe/dist/photoswipe.js',
            'photoSwipeUI': 'photoswipe/dist/photoswipe-ui-default.js',
        },
    },
})
   .sass('src/scss/app.scss', 'static/css')
   .browserSync({
       proxy: 'host.test',
   })
```
test.js:
```
console.log('test')
```

**Comment by asolopovas** [comment]
issue was caused by 
  "browserslist": [
    "last 1 version",
    "> 1%",
    "maintained node versions",
    "not dead"
  ],

in package.json
