### ISSUE TITLE
Error Unexpected token

### ISSUE THREAD

**Issue by yonchando** [JeffreyWay/laravel-mix#2753]
-   Laravel Mix Version: ^6.0.9
-   Node Version (`node -v`): 10.15.1
-   NPM Version (`npm -v`): 6.14.11
-   OS: Window

### Description:
[webpack-cli]  //node_modules\laravel-mix\src\Mix.js:18
static _primary = null;
                       ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at NativeCompileCache._moduleCompile (D:\wamp64\www\Laravel\LaravelWebUI\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\wamp64\www\Laravel\LaravelWebUI\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\wamp64\www\Laravel\LaravelWebUI\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at module.exports (D:\wamp64\www\Laravel\LaravelWebUI\node_modules\laravel-mix\setup\webpack.config.js:2:17)

**Comment by dannyft** [comment]
I just had the same problem. You need to update your version of nodejs.

The easy way is to use the n package:
sudo npm install -g n
sudo n stable
