### ISSUE TITLE
[webpack-cli] TypeError: Promise.allSettled is not a function

### ISSUE THREAD

**Issue by smitexpert** [JeffreyWay/laravel-mix#2760]
-   Laravel Mix Version: 6.0.6
-   Node Version: v12.5.0
-   NPM Version: 6.9.0
-   OS: Widows 10

### Description:

=> npm run watch

> @ watch D:\DML\dml-software
> mix watch

[webpack-cli] TypeError: Promise.allSettled is not a function
    at Dispatcher.fire (D:\DML\dml-software\node_modules\laravel-mix\src\Dispatcher.js:34:24)
    at Mix.dispatch (D:\DML\dml-software\node_modules\laravel-mix\src\Mix.js:217:32)
    at Mix.installDependencies (D:\DML\dml-software\node_modules\laravel-mix\src\Mix.js:95:20)
    at module.exports (D:\DML\dml-software\node_modules\laravel-mix\setup\webpack.config.js:6:15)
    at D:\DML\dml-software\node_modules\webpack-cli\lib\webpack-cli.js:792:43
    at Array.map (<anonymous>)
    at evaluateConfig (D:\DML\dml-software\node_modules\webpack-cli\lib\webpack-cli.js:784:24)
    at D:\DML\dml-software\node_modules\webpack-cli\lib\webpack-cli.js:825:28
    at async Promise.all (index 0)
    at async WebpackCLI.resolveConfig (D:\DML\dml-software\node_modules\webpack-cli\lib\webpack-cli.js:814:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ watch: `mix watch`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SM\AppData\Roaming\npm-cache\_logs\2021-01-10T08_03_54_574Z-debug.log

**Comment by thecrypticace** [comment]
Mix requires at least node v12.14. Please upgrade your version of Node.

**Comment by smitexpert** [comment]
> Mix requires at least node v12.14. Please upgrade your version of Node.

Thanks @thecrypticace,  Your solution is work perfectly.
Thanks again for your help.
