### ISSUE TITLE
Error on Windows, Linux works fine

### ISSUE THREAD

**Issue by Wulfheart** [JeffreyWay/laravel-mix#2779]
-   Laravel Mix Version: 6.0.10 
-   Node Version (`node -v`): v14.15.4
-   NPM Version (`npm -v`): 6.14.10
-   OS: Windows 10 

### Description:
On Linux this works fine, on windows there is an error.
``webpack.mix.js``

````js
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss'),
        require('autoprefixer'),
        require('postcss-import'),
    ]);
````

``npm run dev``
````
> mix

ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (D:\code\dnw\hannibal\src\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:119:10)
    at D:\code\dnw\hannibal\src\node_modules\webpack\lib\javascript\CommonJsChunkFormatPlugin.js:30:19
    at Hook.eval [as call] (eval at create (D:\Code\DNW\hannibal\src\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (D:\Code\DNW\hannibal\src\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (D:\Code\DNW\hannibal\src\node_modules\webpack\lib\Compiler.js:990:30)
    at D:\Code\DNW\hannibal\src\node_modules\webpack\lib\Compiler.js:1033:29
:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Code\DNW\hannibal\src\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (D:\Code\DNW\hannibal\src\node_modules\webpack\lib\Compiler.js:1028:28)
    at Compiler.runAsChild (D:\Code\DNW\hannibal\src\node_modules\webpack\lib\Compiler.js:495:8)
````

**Comment by kinger251285** [comment]
Im also having this error!

When i run npm run dev i get this error:

```
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
```

Full Error:

```
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (C:\users\user\desktop\newlaravelprojects\UpdatedSignUpApp\node_modules\webpack\lib\NormalModule.js:179:10)
    at C:\users\user\desktop\newlaravelprojects\UpdatedSignUpApp\node_modules\vue-loader\lib\plugin-webpack5.js:36:70
    at Hook.eval [as call] (eval at create (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:991:26)
    at C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:1033:29
    at Hook.eval [as callAsync] (eval at create (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:1028:28)
    at C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:471:12
    at Compiler.readRecords (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:869:11)
    at C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:468:11
    at Hook.eval [as callAsync] (eval at create (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\Hook.js:18:14)
    at C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\webpack\lib\Compiler.js:465:20
    at Hook.eval [as callAsync] (eval at create (C:\Users\user\Desktop\NewLaravelProjects\UpdatedSignUpApp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `mix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-01-22T14_22_54_749Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-01-22T14_22_54_876Z-debug.log
```


No duplicate of webpack - npm list webpack outputs:

```
$ npm list webpack
C:\users\user\desktop\newlaravelprojects\UpdatedSignUpApp
`-- laravel-mix@6.0.10
  `-- webpack@5.16.0
```




Any help appreciated

**Comment by Niatik** [comment]
[https://github.com/JeffreyWay/laravel-mix/issues/2791](url)

**Comment by kinger251285** [comment]
> @Wulfheart @kinger251285
> 
> Maybe this can help
> 
> [https://github.com/JeffreyWay/laravel-mix/issues/2791](url)

This didnt work for me.

The only work around i could find is to run Yarn Install rather than npm install.

I read somewhere else there could be a naming issue with spaces when using npm install (not the case in my project). But yarn install seems to have done the trick. Workaround rather than a fix.
