### ISSUE TITLE
HMR build not loading with React

### ISSUE THREAD

**Issue by mboynes** [JeffreyWay/laravel-mix#2854]
-   Laravel Mix Version: 6.0.11
-   Node Version 14.15.0
-   NPM Version 6.14.10
-   OS: macOS 10.15.7 (Intel), using valet with PHP 7.4
-   Chrome 88.0.4324.182

### Description:

The HMR build doesn't appear to work at all using `.react()` in Mix on a brand new/vanilla Laravel installation. The problem appears to stem from the fact that the websocket URL doesn't have a protocol, `//localhost:8080/sockjs-node`. If instead of using the `mix()` PHP helper I explicitly set the URL to `http://localhost:8080//js/app.js`, everything works as we'd expect. Since this does work with Vue, perhaps it's a difference in dependencies (`@pmmmwh/react-refresh-webpack-plugin` or `react-refresh`), and maybe there's some incompatibility there?

This is at least related to #2666 and #2719, but I couldn't be certain that it's a duplicate.

### Steps To Reproduce:

1. Create a brand new Laravel project
2. Update `webpack.mix.js` to add `.react()`
3. Replace the body of `welcome.blade.php` with
   ```php
   <div id="app"></div>
   <script src="{{ mix('js/app.js') }}"></script>
   ```
4. Install React (`npm i react react-dom`)
5. Create a simple React application in `app.js`:
   ```js
   import * as React from 'react';
   import { render } from 'react-dom';
   render(<h1>Hello World</h1>, document.getElementById('app'));
   ```
6. run `npm run hot` (repeat after mix installs additional dependencies). The build should succeed and as far as node is concerned, everything appears to work as advertised.
7. Load the site in the browser. In Chrome's console, I see:
   ```
   Uncaught DOMException: Failed to construct 'WebSocket': The URL '//localhost:8080/sockjs-node' is invalid.
       at new WebsocketClient (http://localhost:8080//js/app.js:56566:20)
       at initWDSSocket (http://localhost:8080//js/app.js:1536:24)
       at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js (http://localhost:8080//js/app.js:88:3)
       at Object.options.factory (http://localhost:8080//js/app.js:58035:31)
       at __webpack_require__ (http://localhost:8080//js/app.js:57515:32)
       at checkDeferredModulesImpl (http://localhost:8080//js/app.js:58692:24)
       at Function.__webpack_require__.x (http://localhost:8080//js/app.js:58705:69)
       at http://localhost:8080//js/app.js:58713:57
       at http://localhost:8080//js/app.js:58715:12
   ```

**Comment by andreyberezhnoy** [comment]
+. I got same error

**Comment by nticaric** [comment]
This error isn't actually related to this repo but to [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin)

I created a pull request to fix this, so hopefully they'll accept it.

https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/323

**Comment by Nacoma** [comment]
[pmmmwh/react-refresh-webpack-plugin#323](https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/323) has been closed by [pull #332](https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/332). 

Mix is forcing the dependency version to `0.5.0-beta.0` which does not contain these fixes Dec. 2020.
