### ISSUE TITLE
Error: Prevent writing to file that only differs in casing or query string from already written file. This will lead to a race-condition and corrupted files on case-insensitive file systems.

### ISSUE THREAD

**Issue by gemul** [JeffreyWay/laravel-mix#2884]
-   Laravel Mix Version: 6.0.6 (`npm list --depth=0`)
-   Node Version (`node -v`):v14.16.0
-   NPM Version (`npm -v`):6.14.11
-   OS: Windows 10

### Description:
Ive got an error while running npm run serve
```
Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
D:\deployed\xampp7\htdocsPHP7\pas\tnde\public\images\2.png
D:\deployed\xampp7\htdocsPHP7\pas\tnde\public\images\2.png
    at checkSimilarFile (D:\deployed\xampp7\htdocsPHP7\pas\tnde\node_modules\webpack\lib\Compiler.js:599:22)
    at writeOut (D:\deployed\xampp7\htdocsPHP7\pas\tnde\node_modules\webpack\lib\Compiler.js:769:13)
    at D:\deployed\xampp7\htdocsPHP7\pas\tnde\node_modules\webpack\lib\util\fs.js:227:5
```
i thought it has something to do with 2 files with the same name being copied in one same directory. How to keep the original image directory structure?

### Steps To Reproduce:

1. Fresh install laravel 8
2. Add laravel ui package `composer install laravel/ui`
3. Add react scaffolding `php artisan ui react`

Next, i made2 components.

i imported a file named 2.png in a component.
```
import two from '../../assets/images/user/2.png';
```
then i imported another file with same name but different directory in another components
```
import twobtc from '../../assets/images/bitcoin/2.png';
```
When i run npm run serve, the webpack created an `image` directory in public directory and only one 2.png file inside it. Then error occurs.

**Comment by hoiihop** [comment]
I have same issue.

- Laravel: 5.8
- Laravel Mix: 6.0.19
- OS: Windows 10
- Frontend: Vue

**Comment by rgyph** [comment]
If anyone else has a similar problem, this will probably help you:

```
mix.options({
    fileLoaderDirs:  {
        images: 'assets/images/[path]',
        fonts: 'assets/fonts/[path]'
    }
});
```
The [path] pattern will prevent all images from being merged into the same directory.
