### ISSUE TITLE
Vue testing with laravel mix is a nightmare

### ISSUE THREAD

**Issue by mfissehaye** [JeffreyWay/laravel-mix#2901]
-   Laravel Mix Version: 5.0.1
-   Node Version (12.19.1):
-   NPM Version (`6.14.8`):
-   OS:

### Description:
I spent the whole day trying to run a single vue test using laravel mix configuration. But it fails for a thousand different reasons. Here is what I reached at and still with no solution.

I am using:
```
"@vue/test-utils": "^1.1.3"
"jsdom": "^16.5.1"
"jsdom-global": "^3.0.2"
"mocha": "^8.3.2"
"mochapack": "^2.0.6"
"vue-loader": "^15.9.6"
"vue-template-compiler": "^2.6.12"
```

And here is my test script
`"test": "cross-env NODE_ENV=testing mochapack --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require resources/js/tests/setup.js resources/js/tests/\\*\\*/\\*.spec.js"`

When I run `yar test` I get the following error.

```
TypeError: File.find is not a function
    at Manifest.refresh (C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\Manifest.js:76:14)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\webpackPlugins\ManifestPlugin.js:12:43
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compiler.js:491:19)
    at onCompiled (C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compiler.js:278:9)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\123\Documents\code\laravel\minisend\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\webpack\lib\Compilation.js:1414:32
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And then I made the following change to my setup.js file
```
const file = require('laravel-mix/src/File')
require('jsdom-global')()
global.File = file
```

Then I found the following error
```
 WEBPACK  Compiling...

  [=========================] 98% (after emitting)

 DONE  Compiled successfully in 359ms                                                                                                           7:10:59 PM

(node:3972) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\123\Documents\code\laravel\minisend\public\main.js'    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at File.read (C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\File.js:166:19)
    at File.version (C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\File.js:173:25)
    at Manifest.hash (C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\Manifest.js:52:65)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:96:26
    at Collection.each (C:\Users\123\Documents\code\laravel\minisend\node_modules\collect.js\dist\methods\each.js:21:14)
    at CustomTasksPlugin.applyVersioning (C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:95:37)
    at C:\Users\123\Documents\code\laravel\minisend\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:16:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Done in 14.10s.
```

I checked my public/manifest json file and it looks like:
```
{
    "/main.js": "/main.js"
}
```

Normally however when I run `yarn dev` the following mix-manifest is generated:
(`yarn dev` is the standard shipped with laravel which is `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js`
```
{
    "/js/app.js": "/js/app.js?id=50d64a484147ea7080ad",
    "/css/app.css": "/css/app.css?id=9e4f237bff356f530aab"
}
```

What is missing in all this?

**Comment by thecrypticace** [comment]
Laravel Mix isn't really intended to be used as a test harness. I'd suggest using something like Jest and Vue Testing Library (https://testing-library.com/docs/vue-testing-library/intro). Also this isn't strictly an issue with Mix but it would be good if we at least had some kind of documentation on possible approaches.
