### ISSUE TITLE
Cannot find module 'lru-cache'

### ISSUE THREAD

**Issue by karneaud** [JeffreyWay/laravel-mix#2932]
-   Laravel Mix Version: 6.0.16
-   Node Version : v14.16.1
-   Yarn Version: 1.22.10
-   OS: Linux homestead 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Description:
Intrying to run the `yarn dev` (`mix watch`) I get the following stack error

> internal/modules/cjs/loader.js:883
>   throw err;
>   ^
> 
> Error: Cannot find module 'lru-cache'
> Require stack:
> - /home/vagrant/modules/xxx/laravel-mix/node_modules/semver/classes/range.js
> - /home/vagrant/modules/xxx/laravel-mix/node_modules/semver/classes/comparator.js
> - /home/vagrant/modules/xxx/laravel-mix/node_modules/semver/index.js
> - /home/vagrant/modules/xxx/laravel-mix/src/Engine.js
> - /home/vagrant/modules/xxx/laravel-mix/bin/cli.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/vagrant/modules/xxx/laravel-mix/node_modules/semver/classes/range.js:187:13)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/vagrant/modules/xxx/laravel-mix/node_modules/semver/classes/range.js',
>     '/home/vagrant/modules/xxx/llaravel-mix/node_modules/semver/classes/comparator.js',
>     '/home/vagrant/modules/xxx/laravel-mix/node_modules/semver/index.js',
>     '/home/vagrant/modules/xxx/laravel-mix/src/Engine.js',
>     '/home/vagrant/modules/xxx/laravel-mix/bin/cli.js'
>   ]
> }
> error Command failed with exit code 1.

### Steps To Reproduce:

Install from package.json

```
{
  "private": true,
  "scripts": {
    "prod": "mix --production",
    "dev": "mix watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "buble": "^0.12.5",
    "jquery": "^3.1.0",
    "laravel-mix": "*",
    "lodash": "^4.16.2",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.0",
    "vue-stash": "^2.0.1-beta",
    "vue-template-compiler": "^2.1.10"
  },
  "dependencies": {
    "bootstrap-datepicker": "^1.6.4",
    "jquery-simple-upload": "^1.0.0",
    "json-loader": "^0.5.4",
    "moment": "*",
    "vuejs-datepicker": "^0.9.24"
  }
}
```
Then run `yarn dev`

**Comment by karneaud** [comment]
I can confirm that the module **lru-cache** is infact install `yarn list` yields **─ lru-cache@6.0.0** as a package installed

**Comment by karneaud** [comment]
tried downgrading to `laravel-mix@6.0.6` with no success
