### ISSUE TITLE
Laravel Mix error after running npx mix watch

### ISSUE THREAD

**Issue by PabloC** [JeffreyWay/laravel-mix#2937]
-   Laravel Mix Version: 6.0.16
-   Node Version: 15.14
-   NPM Version: 7.7.6
-   OS: MacOS Big Sur 11.3 (ARM / M1) without Rosetta2 installed.

After running "npx mix watch" I'am getting this error. Apparently is related to webpack, but I don't understand exactly where is the problem.

```
[webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:609:9)
    at Object.execFile (node:child_process:254:17)
    at Object.module.exports.fileCommandJson (/Users/pibefision/Proyectos/devopspanda/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/pibefision/Proyectos/devopspanda/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/pibefision/Proyectos/devopspanda/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/pibefision/Proyectos/devopspanda/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/pibefision/Proyectos/devopspanda/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

```

**Comment by thecrypticace** [comment]
This is related to `node-notifier` not supporting Apple Silicon: https://github.com/mikaelbr/node-notifier/issues/361

They need to recompile `terminal-notifier` in Xcode with Apple Silicon support. I tested this myself and it compiles just fine but I don't have an M1 Mac to verify functionality.

**Comment by atiqsu** [comment]
Is there any way around?
