### ISSUE TITLE
I always get this error while trying to use laravel/ui with laravel 8, in "npm run dev" step while mixing, but it work fine with laravel 7

### ISSUE THREAD

**Issue by abdulbasit-dev** [JeffreyWay/laravel-mix#2950]
-   Laravel Mix Version: #.#.# (`laravel-mix@6.0.18`)
-   Node Version (`v14.16.1`):
-   NPM Version (`6.14.12`):
-   OS: windows 10

### Description:
> @ dev D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister
> npm run development

> @ development D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister
> mix

× Mix
  Compiled with some errors in 257.38ms

ERROR in ../../../../../../#PROJECTS/Web developing/@Back-End Projects/@laravel/@cloned/checklister/resources/js/app.js
Module build failed: Error: Cannot find module 'D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\babel-loader\lib\index.js'
Require stack:
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\ProgressPlugin.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\index.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\lib\webpack-cli.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\lib\bootstrap.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\bin\cli.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\tapable\lib\Hook.js:14:14)
    at NormalModule.doBuild (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\NormalModule.js:878:15)
    at D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\Compilation.js:1311:12

ERROR in ../../../../../../#PROJECTS/Web developing/@Back-End Projects/@laravel/@cloned/checklister/resources/sass/app.scss
Module build failed: Error: Cannot find module 'D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\ProgressPlugin.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\index.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\lib\webpack-cli.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\lib\bootstrap.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack-cli\bin\cli.js
- D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\NormalModule.js:878:15)
    at D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (D:\#PROJECTS\Web developing\@Back-End Projects\@laravel\@cloned\checklister\node_modules\webpack\lib\NormalModule.js:1143:32)

webpack compiled with 2 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abdulbasit-dev\AppData\Roaming\npm-cache\_logs\2021-04-26T14_11_33_148Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abdulbasit-dev\AppData\Roaming\npm-cache\_logs\2021-04-26T14_11_33_222Z-debug.log

**Comment by thecrypticace** [comment]
It looks like it can't find babel-loader. Not sure why that'd be.

I will note that, unfortunately, Windows paths with spaces and npm don't mix well. We tried to work around a few of these bugs but apparently there are still more. In the mean time my suggestion is to try a path that doesn't include any spaces in any folder all the way up to the D: drive. Let me know how that goes?

**Comment by abdulbasit-web** [comment]
it still gives me error, even I moved the project to the htdoc in c drive some problem and I removed all the spaces in the path "/d/#PROJECTS/Web-developing/@Back-End_Projects/@laravel/@cloned/checklister"
