### ISSUE TITLE
issue with mix.copy

### ISSUE THREAD

**Issue by benlumia007** [JeffreyWay/laravel-mix#2953]
apparently, I was using laravel-mix 5.0.9 and i was able to use the following to copy a file 
`mix.copy( '.htaccess', 'somehwere/.htaccess' );`

when I upgraded to laravel-mix 6.0.18. i get this error now

```
> benjlu@1.0.0 export
> cross-env export=1 NODE_ENV=production node_modules/webpack/bin/webpack.js --progress  --config=node_modules/laravel-mix/setup/webpack.config.js


● Mix █████████████████████████ sealing (92%) asset processing 
 RealContentHashPlugin

node:fs:1057
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, scandir '/home/benlumia007/WordPress/sites/benjlu/public_html/.htaccess'
    at Object.readdirSync (node:fs:1057:3)
    at FileCollection.copyTo (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/FileCollection.js:85:30)
    at /home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/FileCollection.js:77:38
    at Array.forEach (<anonymous>)
    at FileCollection.copyTo (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/FileCollection.js:77:17)
    at CopyFilesTask.run (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/tasks/CopyFilesTask.js:16:20)
    at CustomTasksPlugin.runTask (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:46:36)
    at CustomTasksPlugin.runTasks (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:87:21)
    at /home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:20:18
    at Hook.eval [as callAsync] (eval at create (/home/benlumia007/WordPress/sites/benjlu/public_html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:85:1) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/home/benlumia007/WordPress/sites/benjlu/public_html/.htaccess'
  ```

**Comment by benlumia007** [comment]
```
Error: ENOTDIR: not a directory, scandir '/home/benlumia007/WordPress/sites/benjlu/public_html/.htaccess'
```
is what concerns me.

**Comment by gerardnll** [comment]
Me too... In my case, this error is thrown if the target directory structure does not exist.
