### ISSUE TITLE
Build Error : Cannot read property 'prefix_exceptions' of undefined on 6.0.18

### ISSUE THREAD

**Issue by key60529** [JeffreyWay/laravel-mix#2967]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 6.0.18
-   Node Version (`node -v`): v14.16.1
-   NPM Version (`npm -v`): 6.14.12
-   OS: Max OSX 10.15.7 

### Description:
Got this error while run `npm run production`

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Browsers.prefix (./node_modules/autoprefixer/lib/browsers.js:64:23)
    at ./node_modules/autoprefixer/lib/prefixes.js:135:54
    at Array.map (<anonymous>)
    at Prefixes.select (./node_modules/autoprefixer/lib/prefixes.js:135:31)
    at new Prefixes (./node_modules/autoprefixer/lib/prefixes.js:75:53)
    at loadPrefixes (./node_modules/autoprefixer/lib/autoprefixer.js:107:22)
    at Object.prepare (./node_modules/autoprefixer/lib/autoprefixer.js:117:22)
    at ./node_modules/postcss/lib/lazy-result.js:133:39
    at Array.map (<anonymous>)
    at new LazyResult (./node_modules/postcss/lib/lazy-result.js:131:43)
    at processResult (./node_modules/webpack/lib/NormalModule.js:676:19)
    at ./node_modules/webpack/lib/NormalModule.js:778:5
    at ./node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (./node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (./node_modules/postcss-loader/dist/index.js:96:7)
```

### Steps To Reproduce:
`npm run production`

### Temp Solution :
After downgrade `laravel-mix` to `6.0.16` which could solve the error.

**Comment by thecrypticace** [comment]
This is an autoprefixer issue. Make sure caniuse-lite is on the latest version: `yarn upgrade caniuse-lite` or `npm upgrade caniuse-lite`
