### ISSUE TITLE
Update laravel-mix to 6.0.19

### ISSUE THREAD

**Issue by federicavecchi22** [JeffreyWay/laravel-mix#2989]
laravel/framework : "^8.12",

-   Laravel Mix Version: 5.0.9
-   Node Version 17.7.0
-   NPM Version 7.4.3
-   OS: nginx

### Description:

/var/www/html/erp/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

AssertionError [ERR_ASSERTION]: mix.js() is missing required parameter 1: entry
    at Function.js (/var/www/html/erp/node_modules/laravel-mix/src/Assert.js:13:9)
    at JavaScript.register (/var/www/html/erp/node_modules/laravel-mix/src/components/JavaScript.js:40:16)
    at Api.mix.<computed> [as vue] (/var/www/html/erp/node_modules/laravel-mix/src/components/ComponentFactory.js:98:53)
    at Object.<anonymous> (/var/www/html/erp/webpack.mix.js:18:6)
    at Module._compile (/var/www/html/erp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

### Steps To Reproduce:

run  npm install vue2-datepicker

return: 
42 vulnerabilities (37 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix
  
run  npm audit fix

return:
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating resolve-url-loader to 2.3.2,which is a SemVer major change.
npm WARN audit Updating laravel-mix to 5.0.9,which is a SemVer major change.
npm WARN audit Updating vue-loader to 16.2.0,which is a SemVer major change.

run  npm audit fix --force

Will install laravel-mix@6.0.19, which is a breaking change
43 vulnerabilities (35 moderate, 8 high)

-   Laravel Mix Version: 6.0.19

**Here starts the problem!**

run  npm run dev

> dev
> npm run development

> development
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

/var/www/html/erp/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

AssertionError [ERR_ASSERTION]: **mix.js() is missing required parameter 1: entry**
    at Function.js (/var/www/html/erp/node_modules/laravel-mix/src/Assert.js:13:9)
    at JavaScript.register (/var/www/html/erp/node_modules/laravel-mix/src/components/JavaScript.js:40:16)
    at Api.mix.<computed> [as vue] (/var/www/html/erp/node_modules/laravel-mix/src/components/ComponentFactory.js:98:53)
    at Object.<anonymous> (/var/www/html/erp/webpack.mix.js:18:6)
    at Module._compile (/var/www/html/erp/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

run npm i --legacy-peer-deps

It doesn't fixed for me, even if it took me to the previus laravel-mix version.

**Comment by cerw** [comment]
try to use node 15?

**Comment by JeffreyWay** [comment]
What's your webpack.mix.js file look like? Is that assertion error wrong?

```
AssertionError [ERR_ASSERTION]: mix.js() is missing required parameter 1: entry
```

**Comment by mikesaintsg** [comment]
Did you update your scripts?
I noticed the development command included cross-env which is used in laravel-mix 5 scripts but have been changed to: 
```json
  "scripts": {
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "prod": "npm run production",
    "production": "mix --production"
  },
```
