### ISSUE TITLE
npm run hot not working and not finding existing react-refresh package

### ISSUE THREAD

**Issue by ArondeParon** [JeffreyWay/laravel-mix#3022]
-   Laravel Mix Version: 6.0.18
-   Node Version: 12.20.0
-   NPM Version: 7.5.4
-   OS: MacOS 11.4

### Description:

My project: Laravel + TypeScript + React.
When I run `npm run hot` I get the following error:

```
        Additional dependencies must be installed. This will only take a moment.
 
        Running: npm install react-refresh --save-dev --legacy-peer-deps
 
        Finished. Please run Mix again.
 
npm ERR! code 1
npm ERR! path /Users/aron/Code/aron.codes/discover.cx
npm ERR! command failed
npm ERR! command sh -c webpack "serve" "--hot" "--config=node_modules/laravel-mix/setup/webpack.config.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aron/.npm/_logs/2021-06-22T14_45_36_550Z-debug.log
npm ERR! code 1
npm ERR! path /Users/aron/Code/aron.codes/discover.cx
npm ERR! command failed
npm ERR! command sh -c mix watch --hot

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aron/.npm/_logs/2021-06-22T14_45_36_602Z-debug.log
```

Some observations:

- The debug log does not seem to provide anything helpful.
```
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/aron/.nvm/versions/node/v12.20.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
- The suggested packages are not installed.
- I can install these packages by hand, but Mix will still not detect them and provide me the same error.

**Comment by KevinBatdorf** [comment]
This command worked for me here:

```
npm install @pmmmwh/react-refresh-webpack-plugin@^0.5.0-rc.0 --save-dev
```

**Comment by matt5346** [comment]
above did not work for me, however, this worked!

Changed <script src="{{ asset('js/main.js') }}" defer></script> to <script src="{{ mix('js/main.js') }}"></script> in BLADE view

https://laravel-mix.com/docs/5.0/hot-module-replacement
