### ISSUE TITLE
[webpack-cli] Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by ntqtuan** [JeffreyWay/laravel-mix#3027]
I build a project laravel + vuejs in macos.
I follow the steps:

laravel new blog
cd blog
composer require laravel/ui
php artisan ui vue
npm install && npm run dev
and then asked for the following
```

       Additional dependencies must be installed. This will only take a moment.

	Running: npm install vue-loader@^15.9.7 --save-dev --legacy-peer-deps

	Finished. Please run Mix again.
```

I run : npm install vue-loader@^15.9.7 --save-dev --legacy-peer-deps
finally i run the following command 'npm run dev' .
always get below error:
 ```
                        
[webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:415:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at Object.module.exports.fileCommandJson (/Users/panda/Sites/blog/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/panda/Sites/blog/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/panda/Sites/blog/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/panda/Sites/blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by davidshingie** [comment]
I am facing exactly the same issue.

**Comment by davidshingie** [comment]
> I am facing exactly the same issue.

Just figured out that it was an issue with [terminal-notifier](https://github.com/julienXX/terminal-notifier).

This [solution](https://github.com/mikaelbr/node-notifier/issues/361#issuecomment-873839550) worked for me.

**Comment by ntqtuan** [comment]
@davidshingie thank pro, i fixed

**Comment by esausaravia** [comment]
Thanks! @davidshingie

**Comment by thecrypticace** [comment]
I'd love to have a better fix for this. That is a significant annoyance to have to deal with. It'll require switching to a different plugin or something though.

**Comment by phuclh** [comment]
@scottgrayson I have the same error on m1 16" macbook, did you find out a solution?

**Comment by thecrypticace** [comment]
You can try running it through rosetta. for now: `arch -x86_64  npm run mix`. Let me know if that works?

**Comment by andrewgarrison** [comment]
Also just got an M1 mac and am facing this issue. @scottgrayson's suggestion fixed the issue for me.

**Comment by alexanderhorner** [comment]
# Easiest fix: 

Add `mix.disableNotifications()`to your `webpack.mix.js`

This disables notifications completely and the error disappears.

**Comment by arjun4554** [comment]
uninstall any new antivirus software,
it will work

**Comment by i-bajrai** [comment]
Quick fix if you don't mind rosetta
`softwareupdate --install-rosetta`

**Comment by dusandz** [comment]
2026 update for anyone landing here after upgrading to macOS 27 (Golden Gate): this error is back, including on machines where it was fixed years ago.
 
 The cause hasn't changed. `node-notifier` bundles an Intel-only `terminal-notifier`:
 
     $ file node_modules/node-notifier/vendor/mac.noindex/terminal-notifier.app/Contents/MacOS/terminal-notifier
     ...: Mach-O 64-bit executable x86_64
 
 `-86` is errno 86, `EBADARCH`, the same thing a shell reports as "Bad CPU type in executable". If you solved this in 2021 with `softwareupdate --install-rosetta`, the macOS 27 upgrade undid it. Apple's      [release notes](https://developer.apple.com/documentation/macos-release-notes/macos-27-release-notes): "If Rosetta was previously installed, it is not automatically restored after upgrading to macOS 27.0."
 
 Note that the compile itself succeeds. Only the notification spawn fails, but webpack exits non-zero, so anything chained after it with `&&` never runs.
 
 `mix.disableNotifications()` is now the better fix of the two. Reinstalling Rosetta works today, but macOS 28 removes it for everything except legacy games.
 
 Details, plus the same errno showing up in zsh: https://ddz.dev/blog/bad-cpu-type-in-executable-macos-27/
