### ISSUE TITLE
Error with options.url

### ISSUE THREAD

**Issue by 0xARK** [JeffreyWay/laravel-mix#3044]
-   Laravel Mix Version : 6.0.25
-   Node Version : 14.15.4
-   NPM Version : 7.5.2
-   OS : Ubuntu 18.03

### Description:

Hello ! Today I updated my libraries with `npm update` and since this update I have this error :

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.url should be one of these:
   boolean | object { filter? }
   -> Allows to enables/disables `url()`/`image-set()` functions handling.
   -> Read more at https://github.com/webpack-contrib/css-loader#url
   Details:
    * options.url should be a boolean.
    * options.url should be an object:
      object { filter? }
    at validate (/var/www/jackpotrealm.com/jackpotrealm/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.getOptions (/var/www/jackpotrealm.com/jackpotrealm/node_modules/webpack/lib/NormalModule.js:527:19)
    at Object.loader (/var/www/jackpotrealm.com/jackpotrealm/node_modules/css-loader/dist/index.js:31:27)
    at processResult (/var/www/jackpotrealm.com/jackpotrealm/node_modules/webpack/lib/NormalModule.js:701:19)
    at /var/www/jackpotrealm.com/jackpotrealm/node_modules/webpack/lib/NormalModule.js:807:5
    at /var/www/jackpotrealm.com/jackpotrealm/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /var/www/jackpotrealm.com/jackpotrealm/node_modules/loader-runner/lib/LoaderRunner.js:251:18
```

And my `webpack.mix.js` file :

```
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss')

mix.js('resources/js/app.js', 'public/app/js/app.js').vue()
    .sass('resources/sass/app.scss', 'public/app/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })

```

I've tried to find a solution for the moment, but I can't. I just know that when I comment out the "sass" function in my "webpack.mix.js" file, I no longer get an error (and my css file is not compiled, obviously).

I really don't understand, if someone can help me to solve it I thank you.

If you need more information, ask me !

**Comment by 0xARK** [comment]
For those with the same error, it seems that the problem comes from sass-loader and css-loader and not from laravel-mix. Here is the temporary solution and the explanation :

https://github.com/webpack-contrib/css-loader/issues/1347#issuecomment-883715208
