### ISSUE TITLE
ModuleBuildError:  Can't resolve relative url for fonts and images in scss

### ISSUE THREAD

**Issue by ArjunKishore** [JeffreyWay/laravel-mix#3058]
-   Laravel Mix Version: laravel-mix@6.0.27 
-   Node Version: v16.4.1
-   NPM Version :7.18.1
-   OS:Ubuntu 20.04.2 LTS (within Sail)

### Description:

When I run mix, it is not resolving the relative URL for images and fonts we have in theme.scss file

package.json

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production",
        "widgets": "webpack --config webpack.widgets.js",
        "cypress:open": "cypress open"
    },
```

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve './img/masks/avatar-status.svg' in '/var/www/html/resources/assets/sass'
    at finishWithoutResolve (/var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /var/www/html/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /var/www/html/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /var/www/html/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/var/www/html/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at processResult (/var/www/html/node_modules/webpack/lib/NormalModule.js:707:19)
    at /var/www/html/node_modules/webpack/lib/NormalModule.js:813:5
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/html/node_modules/css-loader/dist/index.js:155:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps To Reproduce:

My code 

webpack.mix.js

```
mix.js("resources/assets/js/register.js", "public/js").vue({ version: 2 })
	.scripts(["node_modules/iframe-resizer/js/iframeResizer.min.js", "resources/assets/js/widget.js"], "public/js/widget.js")
	.js("resources/assets/js/app.js", "public/js").vue({ version: 2 })
	.extract(["vue", "vue-router", "select2", "axios", "bootstrap", "chart.js", "jquery", "jquery-mask-plugin", "raven-js", "shady-css-parser", "v-select2-component", "vue-color", "vue-timeago", "webfontloader"])
	.sass("resources/assets/sass/app.scss", "public/css")
	.sass("resources/assets/sass/theme.scss", "public/css")
	.copyDirectory("resources/assets/fonts/feather", "public/fonts/feather")
	.copy("resources/views/widgets/*/*.png", "storage/app/public/images/widget_screenshots");

```

npm run dev

**Comment by thecrypticace** [comment]
It's looking for `./img` and `./fonts` inside the ./sass folder. Imports are relative to the source file location (see the error: Can't resolve … in **'/var/www/html/resources/assets/sass'**).

You need to back up a level by using `../`
