### ISSUE TITLE
Mix v6 + Vue style tag => compilation hangs

### ISSUE THREAD

**Issue by ilyen85** [JeffreyWay/laravel-mix#3070]
-   Laravel Mix Version: 6.0.27 
(`npm list --depth=0`)
```
├── @fortawesome/fontawesome-free@5.15.4
├── @johmun/vue-tags-input@2.1.0
├── @popperjs/core@2.9.3
├── @shopify/draggable@1.0.0-beta.8
├── @tailwindcss/forms@0.3.3
├── autoprefixer@10.3.1
├── axios@0.21.1
├── chart.js@2.9.4
├── chartjs-plugin-zoom@0.7.7
├── core-js@3.16.1
├── css-loader@5.2.7
├── jstimezonedetect@1.0.7
├── laravel-mix@6.0.27
├── lodash@4.17.21
├── moment@2.29.1
├── moment-timezone@0.5.33
├── normalize.css@8.0.1
├── postcss@8.3.6
├── postcss-custom-properties@10.0.0
├── postcss-import@14.0.2
├── postcss-loader@4.3.0
├── regenerator-runtime@0.13.9
├── resolve-url-loader@4.0.0
├── sass@1.38.0
├── sass-loader@12.1.0
├── sass-resources-loader@2.2.4
├── tailwindcss@2.2.7
├── v-lazy-image@1.4.0
├── v-tooltip@2.1.3
├── vee-validate@3.4.11
├── vue@2.6.14
├── vue-chartjs@3.5.1
├── vue-loader@15.9.8
├── vue-multiselect@2.1.6
├── vue-simple-alert@1.1.1
├── vue-svg-inline-loader@2.1.2
├── vue-template-compiler@2.6.14
├── vue2-datepicker@3.9.2
└── vuex@3.6.2
```
-   Node Version (`node -v`): v14.9.0
-   NPM Version (`npm -v`): 6.14.8
-   OS: Mac OS 11.2.3 (20D91)
- webpack.mix.js: (most of the tasks are commented out, for now, to be able to find the issue)
```
const mix = require('laravel-mix')
const path = require('path')
const tailwindcss = require('tailwindcss')

mix
    .webpackConfig({
        resolve: {
            alias: {
                "@sass": path.resolve(__dirname, "resources/sass"),
                "@js": path.resolve(__dirname, "resources/js"),
                "@json": path.resolve(__dirname, "public/json"),
                "@filters": path.resolve(__dirname, "resources/js/filters"),
                "@components": path.resolve(__dirname, "resources/js/components"),
                "@image": path.resolve(__dirname, "public/image"),
                "@mixins": path.resolve(__dirname, "resources/js/mixins"),
                "@services": path.resolve(__dirname, "resources/js/services"),
                "@store": path.resolve(__dirname, "resources/js/store"),
                "@utils": path.resolve(__dirname, "resources/js/utils"),
                "@tracking": path.resolve(__dirname, "resources/js/tracking"),
            }
        },
    })
    .js('resources/js/checkout.js', 'js/checkout.js').vue()
    .sass('resources/sass/checkout-one.sass', 'css/checkout-one.css')
    .options({
        postCss: [
            require("postcss-import"),
            require("tailwindcss"),
            require("autoprefixer"),
        ],
    })
```

### Description:
I'm updating a project that was working fine with laravel-mix 5.0.9. I think I have some kind of configuration issue. If I ran `npx mix` it always stuck at this point:

```
● Mix █████████████████████████ building (18%) 0/2 entries 2700/2700 dependencies 796/810 modules 14 active
 style-loader › css-loader › vue-loader › postcss-loader › sass-loader › vue-loader › resources/js/components/loader-component.vue
```

I have tried to figure out what is the problem with that component, and my best guess is that it's the first component in the `resources/js` folder with a style tag.

```
<template>
	<div :class="{'loader_component': true, 'loader_component_full': full_height}">
		<span v-if="is_loading" class="flex items-center justify-center">
			<svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" :class="`animate-spin ${ loader_size } ${ loader_colour }`" :alt="loader_text"><path d="M526 1394q0 53-37.5 90.5t-90.5 37.5q-52 0-90-38t-38-90q0-53 37.5-90.5t90.5-37.5 90.5 37.5 37.5 90.5zm498 206q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-704-704q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm1202 498q0 52-38 90t-90 38q-53 0-90.5-37.5t-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-964-996q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113zm1170 498q0 53-37.5 90.5t-90.5 37.5-90.5-37.5-37.5-90.5 37.5-90.5 90.5-37.5 90.5 37.5 37.5 90.5zm-640-704q0 80-56 136t-136 56-136-56-56-136 56-136 136-56 136 56 56 136zm530 206q0 93-66 158.5t-158 65.5q-93 0-158.5-65.5t-65.5-158.5q0-92 65.5-158t158.5-66q92 0 158 66t66 158z" class="fill-current" /></svg>
			<span v-if="loader_text" :class="`pl-2 ${ loader_colour }`" v-text="loader_text"></span>
		</span>
	</div>
</template>

<script>
	export default {
		props: {
			is_loading: {
				type: Boolean,
				default: false,
			},
			loader_text: {
				type: String,
				default: "",
			},
			loader_size: {
				type: String,
				default: "h-6",
			},
			loader_colour: {
				type: String,
				default: "text-brown-300",
			},
			full_height: {
				type: Boolean,
				default: false,
			}
		},
  }
</script>

<style lang="sass">
.lazy_loader_styles 
	@apply relative
	.loader_component_full
		@apply absolute inset-0 flex items-center justify-center
.loader_component
	min-height: 1px
	svg
		animation-duration: 1.5s

</style>

```

Is it normal that a loader shows up more than once in the output?

`style-loader › css-loader › vue-loader › postcss-loader › sass-loader › vue-loader › resources/js/components/loader-component.vue`

Can someone help me out maybe? Thank you!

**Comment by ilyen85** [comment]
An addition to the issue:
If I change the sass task from:

```
.sass('resources/sass/checkout-one.sass', 'css/checkout-one.css')
    .options({
        postCss: [
            require("postcss-import"),
            require("tailwindcss"),
            require("autoprefixer"),
        ],
    })
```

to: 

```
.postCss('resources/sass/checkout-one.sass', 'css/checkout-one.css', [
        require("postcss-import"),
        require("tailwindcss"),
        require("autoprefixer"),
    ])
```

I receive an error message:

```
npx mix

✖ Mix
  Compiled with some errors in 4.07s



  ERROR in ./resources/sass/checkout-one.sass (./node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[1]!./node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[2]!./node_modules/style-loader/dist/cjs.js!./node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[1]!./node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[3]!./resources/sass/checkout-one.sass)
  Module build failed (from ./node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js):
  SyntaxError

  (1:1) /Users/avgjoe/Repos/project/resources/sass/checkout-one.sass Unknown word

  > 1 | import api from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
      | ^
    2 |             import content from "!!../../node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[1]!../../node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[2]!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[3]!./checkout-one.sass";
    3 |

  Child mini-css-extract-plugin /Users/avgjoe/Repos/project/node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[1]!/Users/avgjoe/Repos/project/node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-6[0].rules[0].use[2]!/Users/avgjoe/Repos/project/node_modules/style-loader/dist/cjs.js!/Users/avgjoe/Repos/project/node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[1]!/Users/avgjoe/Repos/project/node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[2]!/Users/avgjoe/Repos/project/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[3]!/Users/avgjoe/Repos/project/resources/sass/checkout-one.sass compiled with 1 error

ERROR in ./resources/sass/checkout-one.sass
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /Users/avgjoe/Repos/project/resources/sass/checkout-one.sass Unknown word

> 1 | import api from "!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../node_modules/laravel-mix/node_modules/css-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[1]!../../node_modules/laravel-mix/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[2]!../../node_modules/sass-loader/dist/cjs.js??clonedRuleSet-15[0].rules[0].use[3]!./checkout-one.sass";
  3 |

    at processResult (/Users/avgjoe/Repos/project/node_modules/webpack/lib/NormalModule.js:713:19)
    at /Users/avgjoe/Repos/project/node_modules/webpack/lib/NormalModule.js:819:5
    at /Users/avgjoe/Repos/project/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/avgjoe/Repos/project/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/avgjoe/Repos/project/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/avgjoe/Repos/project/node_modules/laravel-mix/node_modules/postcss-loader/dist/index.js:140:7)

webpack compiled with 2 errors
```

I'm not sure if this is related, but at least an error message. I have found some stack-overflow issues with a similar error message:

https://stackoverflow.com/questions/65416595/webpack-syntaxerror-and-unknown-word-when-building-ssr-cra-app#answer-65450496

In the answer, file-loader is mentioned, I'm not sure if this is related at all, but maybe someone can help me ;)

**Comment by thecrypticace** [comment]
Can you provide a reproduction repo? I'm not sure what the issue is here but at a glance I'm not sure what I can do to help without one.

**Comment by ilyen85** [comment]
Thanks for at least looking into it, I will try to create a repo without the "sensitive" stuff.

**Comment by ilyen85** [comment]
@thecrypticace I have created a repo you can reach it here:
https://github.com/ilyen85/reproduct-mix-issue-3070

I have added every vendor I use in the other repo, so most of the stuff is not used at all, but the issues are still present, so Its either something in the loader-component.vue or one of the configs files.

Thanks for your help

**Comment by ilyen85** [comment]
No way... I have the issue I had a style that caused an infinite loop!

```
.label_like
	@apply py-3 text-lg leading-normal text-brown-300
	&.py-0
		@apply py-0
```

the `.py-0` caused the issue, I had to enable every sheet one by one then every line till I have found it...

🤦 

Thanks for the help and sorry for the time you wasted on me! Closing this issue

**Comment by thecrypticace** [comment]
No worries! Glad you got it figured out!
