### ISSUE TITLE
Assumed File Path structure causing failure

### ISSUE THREAD

**Issue by bradenkeith** [JeffreyWay/laravel-mix#317]
I am experiencing an issue with compiling sass code. See thread with Jeffrey here - https://twitter.com/jeffrey_way/status/828702307357425665

Using Laravel 5.4 and Laravel-Mix 0.6.0

Reproduction steps:
`cd /Users/bradenkeith/Downloads/ && laravel new test && cd test && npm install && npm run dev`

Compiles fine, however - this does not:
`cd /Users/bradenkeith/Dropbox\ \(Personal\)/Home\ Folder/Sites/Jet\ Metals/ && laravel new test && cd test && npm install && npm run dev`

I'm assuming something with the special characters in my directory structure?

Error returned from the compiler is:
```

ERROR

  Failed to compile with 1 errors

 error  in ./resources/assets/sass/app.scss

Module parse failed: /Users/bradenkeith/Dropbox (Personal)/Home Folder/Sites/Jet Metals/test/resources/assets/sass/app.scss Unexpected character '@' (3:0)
You may need an appropriate loader to handle this file type.
| 
| // Fonts
| @import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);
| 
| // Variables

 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

            Asset      Size  Chunks                    Chunk Names
       /js/app.js   1.16 MB       0  [emitted]  [big]  /js/app
mix-manifest.json  32 bytes          [emitted]         

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bradenkeith/Dropbox (Personal)/Home Folder/Sites/Jet Metals/test/npm-debug.log

```

**Comment by bradenkeith** [comment]
npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/bradenkeith/Dropbox (Personal)/Home Folder/Sites/Jet Metals/test/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bradenkeith/.composer/vendor/bin
10 verbose lifecycle @~dev: CWD: /Users/bradenkeith/Dropbox (Personal)/Home Folder/Sites/Jet Metals/test
11 silly lifecycle @~dev: Args: [ '-c',
11 silly lifecycle   'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~dev: Returned: code: 2  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/bradenkeith/Dropbox (Personal)/Home Folder/Sites/Jet Metals/test
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 2
23 error Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by wesleyhf** [comment]
:+1:

**Comment by JeffreyWay** [comment]
Yeah that's probably messing up the regular expression we use.

https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L138

Any Windows users want to play around with escaping file paths like that?

**Comment by bradenkeith** [comment]
@JeffreyWay - I was able to confirm this resolves my issue

`test: new RegExp(toCompile.src.path.replace(/(\s|\(|\))/g,'\\$1').normalize() + '$'),`

This will regex a space, ( or ) and escape them, then normalize the file path. 

Notice I also used normalize() instead of a regex replace for the Windows clients. Everything I can find points to this being the way to solve slashes in windows, but we will need a windows user to confirm https://millermedeiros.github.io/mdoc/examples/node_api/doc/path.html#path.normalize

Opened a pull request for discussion and testing. My first PR, so let me know if I need to improve on this process https://github.com/JeffreyWay/laravel-mix/pull/351

**Comment by forehalo** [comment]
@bradenkeith 
In windows, we should still replace `\\` with `\\\\` first.

`test: new RegExp(toCompile.src.path.replace(/\\/g, '\\\\').replace(/(\s|\(|\))/g,'\\$1').normalize() + '$'),`
![image](https://cloud.githubusercontent.com/assets/8281226/22766889/ff196192-eeb2-11e6-96e9-abe9fc34e76a.png)

![image](https://cloud.githubusercontent.com/assets/8281226/22766920/2012afd4-eeb3-11e6-8f44-32fe962dd63c.png)

**Comment by bradenkeith** [comment]
Thanks for confirming @forehalo! I have updated my PR.
