### ISSUE TITLE
mix wont compile multiple CSS files [sass AND less]

### ISSUE THREAD

**Issue by goodbytes-gb** [JeffreyWay/laravel-mix#375]
I am using Laravel Spark which is using LESS for styling. I normally use SASS so I'm sticking with that for the frontend website.. and less for the spark client/billing area.

Mix doesn't seem to like that I am using both.

```
mix.less('resources/assets/less/app.less', 'public/css/app.css').sass('resources/assets/scss/style.scss', 'public/css/style.css');

mix.version([
    'css/style.css',
    'css/app.css'
]);
```

This will only output style.css

Now if I change the functions around, like so:

```
mix.sass('resources/assets/scss/style.scss', 'public/css/style.css').less('resources/assets/less/app.less', 'public/css/app.css');
```

This will only output app.css

This tells me that it's ignoring the first reference to sass/less and only using the second.. or over overwriting the first.

I take it this isn't the intended behaviour?

**Comment by JeffreyWay** [comment]
What version of Laravel Mix do you have installed?

**Comment by goodbytes-gb** [comment]
From Spark's package.json file:
```
    "laravel-mix": "^0.5.0",
```

I changed it to:
```
    "laravel-mix": "^0.7.5",
```

then run `npm update` then `npm run dev`

Now get error:

```
$ npm run dev                                                                                                                                                                                (master✱) 

> @ dev /Users/user/Sites/myhomehelp
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'css/style.css'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at File.read (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/File.js:71:19)
    at File.version (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/File.js:129:29)
    at manualFiles.forEach.file (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/Versioning.js:52:47)
    at Array.forEach (native)
    at Versioning.writeHashedFiles (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/Versioning.js:52:26)
    at new Versioning (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/Versioning.js:18:14)
    at Mix.enableVersioning (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/Mix.js:63:27)
    at Mix.initialize (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/src/Mix.js:53:35)
    at Object.<anonymous> (/Users/user/Sites/myhomehelp/node_modules/laravel-mix/setup/webpack.config.js:18:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Sites/myhomehelp/npm-debug.log
```

**Comment by goodbytes-gb** [comment]
Looks like the problem may have been related to spark, I noticed a version released 13th Feb. I updated to this and it now compiles both .less and .scss file.
