### ISSUE TITLE
TypeError: mix.stylus is not a function

### ISSUE THREAD

**Issue by luminarious** [JeffreyWay/laravel-mix#385]
I'm surprised, because I started a new mix project and was happy to see Stylus mentioned in the webpack.mix.js file. I see it's a recent addition, so maybe there's a bug of some sort?
```
mix.stylus('source/css/app.styl',
TypeError: mix.stylus is not a function
    at Object.<anonymous> (/Users/hardi/WWW/galerii/webpack.mix.js:3:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Mix.initialize (/Users/hardi/WWW/galerii/node_modules/laravel-mix/src/Mix.js:44:13)
    at Object.<anonymous> (/Users/hardi/WWW/galerii/webpack.config.js:18:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

- Laravel Mix Version: 0.7.5
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: macOS

**Comment by terion-name** [comment]
It is not at npm yet

**Comment by luminarious** [comment]
Yes, looks I was early to the party :)
