### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by reorg-hle** [JeffreyWay/laravel-mix#399]
- Laravel Mix Version: 0.8.1
- Node Version (`node -v`): 7.4.0
- NPM Version (`npm -v`): 4.0.5
- OS: ubuntu 14.04

### Description:

```
$ npm run dev

> @ dev /var/www/event
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules

 94% asset optimization/var/www/event/node_modules/laravel-mix/src/Manifest.js:73
            path = this.preparePath(path);
                        ^

TypeError: this.preparePath is not a function
    at flattenedPaths.forEach.path (/var/www/event/node_modules/laravel-mix/src/Manifest.js:73:25)
    at Array.forEach (native)
    at Object.transform (/var/www/event/node_modules/laravel-mix/src/Manifest.js:72:24)
    at Compiler.<anonymous> (/var/www/event/node_modules/webpack-stats-plugin/lib/stats-writer-plugin.js:74:32)
    at Compiler.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at Compiler.emitAssets (/var/www/event/node_modules/webpack/lib/Compiler.js:292:7)
    at onCompiled (/var/www/event/node_modules/webpack/lib/Compiler.js:231:11)
    at /var/www/event/node_modules/webpack/lib/Compiler.js:480:13
    at next (/var/www/event/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/var/www/event/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at /var/www/event/node_modules/webpack/lib/Compiler.js:477:10
    at Compilation.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/var/www/event/node_modules/webpack/lib/Compilation.js:640:19)
    at next (/var/www/event/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/var/www/event/node_modules/webpack/lib/ProgressPlugin.js:122:5)
    at Compilation.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/var/www/event/node_modules/webpack/lib/Compilation.js:631:11)
    at next (/var/www/event/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/var/www/event/node_modules/webpack/lib/ProgressPlugin.js:118:5)
    at Compilation.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/var/www/event/node_modules/webpack/lib/Compilation.js:626:10)
    at next (/var/www/event/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/var/www/event/node_modules/webpack/lib/ProgressPlugin.js:114:5)
    at Compilation.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/var/www/event/node_modules/webpack/lib/Compilation.js:622:9)
    at next (/var/www/event/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/var/www/event/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at Compilation.applyPluginsAsyncSeries (/var/www/event/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/var/www/event/node_modules/webpack/lib/Compilation.js:570:8)
```

**Comment by JeffreyWay** [comment]
Looks like you copied our webpack.config.js file to your project root? Make sure you update it to match ours. https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js

**Comment by reorg-hle** [comment]
Yep that was it, thanks!
