### ISSUE TITLE
Mix.root not a function - error when using mix.copy

### ISSUE THREAD

**Issue by AlexanderWright** [JeffreyWay/laravel-mix#45]
when using mix.copy() I get the following error:

`TypeError: Mix.root is not a function
    at Object.module.exports.copy (/Users/me/project/node_modules/laravel-mix/src/index.js:128:17)
    at Object.<anonymous> (/Users/me/project/webpack.mix.js:18:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Mix.initialize (/Users/me/project/node_modules/laravel-mix/src/Mix.js:35:9)
    at Object.<anonymous> (/Users/me/project/node_modules/laravel-mix/setup/webpack.config.js:18:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

`npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node@6/6.9.2/bin/node" "/usr/local/bin/npm" "run" "webpack"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1`

**Comment by natocTo** [comment]
This was fixed some hours ago.
https://github.com/JeffreyWay/laravel-mix/pull/41/commits/d50b58204a14ac58e40d03dae21058c41b09f2d3

**Comment by AlexanderWright** [comment]
Ah, I thought I had the latest copy.

Pulling the latest fixed the issue for me.
