### ISSUE TITLE
Adding Files to mix-manifes.json, Versioning Extra Files

### ISSUE THREAD

**Issue by danremollino** [JeffreyWay/laravel-mix#451]
- Laravel Mix Version: 0.8.3
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: MacOS 10.12.3

I'd like to call some JS and CSS on only on a few specific pages. I'm achieve this by using Blade `@stack()` and `@push()`, however, simply using `copy()` does not add these files to mix-manifes.json. This causes Laravel to throw an error when adding the files via `{{ mix('myFile.ext') }}`. (I guess I could not use `mix()`, but I feel like I should be.)

The only way I have found to add these files to mix-manifes.json is to version them. Is there another way to tell Mix to add files to the manifest?

This process lead me to the compile error below... am I doing something incorrect?

### Description:

Versioning copied extra files throws an error when having a clean public folder. Error does not occur if the file exists from a previous non-versioned build.

```
mix.js('resources/assets/js/wfl.js', 'public/js')
   .extract(['fluidvids.js', 'jquery', 'vue'])

   .copy('node_modules/flatpickr/dist/flatpickr.js', 'public/js')
   .copy('node_modules/flatpickr/dist/flatpickr.css', 'public/css')

   .copy('node_modules/slick-carousel/slick/slick.js', 'public/js')
   .copy('node_modules/slick-carousel/slick/slick.css', 'public/css')

   .sass('resources/assets/sass/wfl.scss', 'public/css')

   .copy('resources/assets/fonts', 'public/fonts', false)
   .copy('resources/assets/images', 'public/images', false)

   .sourceMaps()
   .version(['public/css/flatpickr.css', 'public/js/flatpickr.js', 'public/css/slick.css', 'public/js/slick.js']);
```

### Steps To Reproduce:

1. have a clean public directory
2. copy a css or js file to your public directory via `copy()`
3. version that file

**Comment by JeffreyWay** [comment]
`mix.copy()` won't affect your `mix-manifest.json` file. You could potentially copy dozens and dozens of files in a directory, and you don't want all of those to clutter up `mix-manifest`. 

`mix-manifest.json` is primarily to assist with versioned files that will contain a hash that you don't immediately know at run-time. In your case, just reference the file path as your normally would.

**Comment by danremollino** [comment]
Thanks.

Would you have any idea why my current implementation of `version()` throws an error while adding the optional files?

**Comment by JeffreyWay** [comment]
Are you getting some error like "Error: ENOENT: no such file or directory, open"?

**Comment by danremollino** [comment]
Yes... I assume `version()` is running before it can tell the files are there. Am I using it wrong? 

```
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'public/css/flatpickr.css'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at File.read (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/File.js:71:19)
    at File.version (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/File.js:129:29)
    at manualFiles.forEach.file (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/Versioning.js:52:47)
    at Array.forEach (native)
    at Versioning.writeHashedFiles (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/Versioning.js:52:26)
    at new Versioning (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/Versioning.js:18:14)
    at Mix.enableVersioning (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/Mix.js:65:27)
    at Mix.initialize (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/src/Mix.js:55:35)
    at Object.<anonymous> (/Users/dan/Documents/Work/Resin/World Fitness League/sites/wfl-laravel/node_modules/laravel-mix/setup/webpack.config.js:18:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by JeffreyWay** [comment]
Right now, anything you pass to `mix.version()` is expected to exist. The issue is that the file doesn't exist yet at the time `mix.version()` triggers.

**Comment by danremollino** [comment]
Right, so as of now there is no way to `copy()` a file to the build directory, and then version it out in a single chain. This is a little confusing as the [Versioning Extra Files example](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/versioning.md#versioning-extra-files) sort of hints at that is the purpose.

Changing my `.copy()` instances to `.js()` and `.sass()` give me the functionality that I'd like, but just seem a little out of purpose.

**Comment by JeffreyWay** [comment]
I'm pushing an update to allow you to do this.

**Comment by danremollino** [comment]
Hey @JeffreyWay, this is working great, thanks!

The workflow seems to copy the file to the destination as specified in your webpack.mix.js and then make a copy of that file to version it, leaving two files in the target directory. Would it be possible to have it trash the unhashed file at build?
