### ISSUE TITLE
npm run dev error on Ubuntu 16.04, Laravel Homestead Laravel 5.4 on fresh project

### ISSUE THREAD

**Issue by mirbatworks** [JeffreyWay/laravel-mix#479]
I use laravel homestead on my Ubuntu 16.04. LTS. On new Laravel 5.4 project I get this errors when I run `npm run dev` command. On npm/npm they said it's problem with `webpack.config.js` in `laravel-mix` This is errors from terminal:

```
vagrant@homestead:~/www/blog$ npm run dev

> @ dev /home/vagrant/www/blog
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/vagrant/www/blog/node_modules/laravel-mix/setup/webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/www/blog/npm-debug.log
```
Log:
[npm-debug.log.zip](https://github.com/JeffreyWay/laravel-mix/files/802128/npm-debug.log.zip)

**Comment by JeffreyWay** [comment]
Update your installed version of Node.

**Comment by mirbatworks** [comment]
@JeffreyWay My Vagrant Box is updated but Node is still 5.7 version. How to do that in Laravel Homestead?
