### ISSUE TITLE
mix.copy error

### ISSUE THREAD

**Issue by g0ld3lux** [JeffreyWay/laravel-mix#50]
im receiving this error when i use mix.copy in my webpack.mix.js
```
npm run webpack

> @ webpack /mnt/c/Users/uriah/sites/royalflush
> cross-env NODE_ENV=development webpack --progress --hide-modules

/mnt/c/Users/uriah/sites/royalflush/node_modules/laravel-mix/src/index.js:128
        to: Mix.root(to)
                ^

TypeError: Mix.root is not a function
    at Object.module.exports.copy (/mnt/c/Users/uriah/sites/royalflush/node_modules/laravel-mix/src/index.js:128:17)
    at Object.<anonymous> (/mnt/c/Users/uriah/sites/royalflush/webpack.mix.js:15:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Mix.initialize (/mnt/c/Users/uriah/sites/royalflush/node_modules/laravel-mix/src/Mix.js:35:9)
    at Object.<anonymous> (/mnt/c/Users/uriah/sites/royalflush/webpack.config.js:18:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ webpack script 'cross-env NODE_ENV=development webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/uriah/sites/royalflush/npm-debug.log


```

**Comment by DarkaOnLine** [comment]
Update to the latest version. #41 fixed this.

**Comment by g0ld3lux** [comment]
thanks
