### ISSUE TITLE
Error running mix

### ISSUE THREAD

**Issue by MysticSheik** [JeffreyWay/laravel-mix#504]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 7.6.0
- NPM Version (`npm -v`): 4.1.2
- OS: Windows 10 (Laravel Homestead)

### Description:
I've run npm install straight out of the box, which works fine. However, when run "npm run dev" I get an error: 

`npm` ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules `--config=node_modules/laravel-mix/setup/webpack.config.js`

The error code is ELIFECYCLE.

**Comment by JeffreyWay** [comment]
I have no idea. Have you made any tweaks at all? Can you do:

```
laravel new app && cd app
npm install
npm run dev
```

Do you still get that ELIFECYCLE error?

**Comment by MysticSheik** [comment]
Mhm, still the same error ~

**Comment by JeffreyWay** [comment]
Hmm, not sure at all. You're the only one who has made an issue like this.

Is anyone else experienced this, who can shed some light on a solution?

**Comment by QWp6t** [comment]
What if you run it manually?

```js
node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

or even
```js
set NODE_ENV=development
node node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

Can you post the full error log(s)?

**Comment by MysticSheik** [comment]
Running  `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js` manually gives a more fun error ~

(It seems to be unable to find som directories, even though they exist :/ )

`
ERROR  Failed to compile with 3 errors                                                                                                6:16:11 PM

 error  in ./resources/assets/sass/app.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/vagrant/Projects/app/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:912:18)
    at Object.getInstalledBinaries (/home/vagrant/Projects/app/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/home/vagrant/Projects/app/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/vagrant/Projects/app/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/vagrant/Projects/app/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/vagrant/Projects/app/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/vagrant/Projects/app/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Projects/app/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./resources/assets/sass/app.scss 4:14-234
 @ multi ./~/laravel-mix/src/mock-entry.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: Error
    at /home/vagrant/Projects/app/node_modules/webpack/lib/NormalModule.js:141:35
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Projects/app/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/vagrant/Projects/app/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/vagrant/Projects/app/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/home/vagrant/Projects/app/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/home/vagrant/Projects/app/node_modules/webpack/lib/Compilation.js:142:10)
    at moduleFactory.create (/home/vagrant/Projects/app/node_modules/webpack/lib/Compilation.js:424:9)
    at /home/vagrant/Projects/app/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /home/vagrant/Projects/app/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /home/vagrant/Projects/app/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/home/vagrant/Projects/app/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/vagrant/Projects/app/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/home/vagrant/Projects/app/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/home/vagrant/Projects/app/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

 error

/home/vagrant/Projects/app/node_modules/extract-text-webpack-plugin/loader.js??ref--8-0!/home/vagrant/Projects/app/node_modules/style-loader/index.js!/home/vagrant/Projects/app/node_modules/css-loader/index.js!/home/vagrant/Projects/app/node_modules/postcss-loader/index.js!/home/vagrant/Projects/app/node_modules/resolve-url-loader/index.js!/home/vagrant/Projects/app/node_modules/sass-loader/lib/loader.js??ref--8-5!/home/vagrant/Projects/app/resources/assets/sass/app.scss doesn't export content
`

**Comment by danielthomascarr** [comment]
Getting the same error with a fresh install of Windows 10, Node and Laravel
node 6.10.0
npm 3.10.10
Laravel Framework 5.4.15

Haven't touched the package.json file or any other file and get errors on npm run dev
``

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Daniel\Projects\card\npm-debug.log

``
The package.json file


``

{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.1.1",
    "laravel-mix": "^0.8.1",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  }
}

``

**Comment by danielthomascarr** [comment]
Found a solution, had originally used npm install --no-bin-links it didn't work, but didi npm rebuild --no-bin-links and npm run dev works fine @MysticSheik @JeffreyWay

**Comment by MysticSheik** [comment]
I tried running "npm rebuild --no-bin-links" with no luck. Still the ELIFECYCLE. I decided to try a fresh install on my Windows 7, but got the same results after running:
1. "laravel new [APP NAME]"
2. "npm install --no-bin-links"
3. "npm rebuild --no-bin-links"
4. "npm run dev"

My errors looks like [this](http://imgur.com/a/gQX5R)
My NPM Debug Log file looks like [this](http://pastebin.com/t2JHNpt5)

**Comment by danielthomascarr** [comment]
Have you tried going to node js and installing to get the latest version?

**Comment by MysticSheik** [comment]
Yes, both Node and NPM is up to date ~

**Comment by danielthomascarr** [comment]
Are you using Git bash if so try using command line. This didn't work for me but I also did npm clean cache command and then the npm rebuild --no-bin-links

**Comment by danielthomascarr** [comment]
If you have problems with this I have used windows 7 with Laravel 5.2 & 5.3 using gulp, I suggest searching that and using it instead, most of these laravel things are built by people using macs so windows aren't really top of the agenda, hope this helps, if not let me know and will try to help.

**Comment by MysticSheik** [comment]
Yeah, I've used Gulp before ~
I guess I'll just continue using that then c:

**Comment by MicroDreamIT** [comment]
Currently I am developing a non-laravel, but i want to use laravel-mix as @JeffreyWay showed in Vue2.0 lesson, but its not working. I have tried all the command, "npm run watch", "npm run dev", "npm run production", nothing is working. Here is the error report,

`C:\wamp64\www\OurProject\shapecss-framework>npm run watch

> @ watch C:\wamp64\www\OurProject\shapecss-framework
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\wamp64\www\OurProject\shapecss-framework\node_modules\cross-env\bin\cross-env.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ watch: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp64\www\OurProject\shapecss-framework\npm-debug.log
`

**Comment by JeffreyWay** [comment]
Do `npm install cross-env -D` and then update your package.json file to look like this:

https://github.com/laravel/laravel/blob/master/package.json#L4-L8

**Comment by MicroDreamIT** [comment]
@JeffreyWay Thank you. You are simply boss. 

https://github.com/MicroDreamIT/ShapeCss its a shape generator, now I am trying to build a complete framework like bootstrap. I have used laravel-elixir before.

The testing repository I have just created, https://github.com/MicroDreamIT/shapecss-framework

Now I am using laravel-mix, and you lessons... :)

**Comment by matt83bar** [comment]
Just want to comment, I had the same problem as OP and the `npm rebuild --no-bin-links` worked for me.  I am running nodejs 8 on ubuntu 16.04 so I wasn't sure if the "do this if you're running a VM on Windows" thing would work, but it did.  Thanks!

**Comment by El-Diablo1** [comment]
how can i remove error on this?
@import '~bootstrap/scss/bootstrap';
