### ISSUE TITLE
Error Running npm run production

### ISSUE THREAD

**Issue by xoco70** [JeffreyWay/laravel-mix#505]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): 6.10.0
- NPM Version (`npm -v`): 3.10.10
- OS: Ubuntu 16.04

### Description:

`npm run dev` works great.
`npm run production` seems to be working, but at the end, gives me:

```
forge@KZ:~/my.kendozone.com$ npm run production

> @ production /home/forge/my.kendozone.com
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
 95% emitting                                                                           

 DONE  Compiled successfully in 63823ms                                                                                                                                                          12:18:02 PM



undefined:1555
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:1555:11)
    at croak (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2102:9)
    at unexpected (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2108:9)
    at semicolon (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2128:56)
    at simple_statement (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2319:73)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2188:19)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2141:24)
    at block_ (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2434:20)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2406:25)
    at function_ (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2412:15)
    at expr_atom (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2627:24)
    at maybe_unary (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2797:19)
    at expr_ops (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2832:24)
    at maybe_conditional (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2837:20)
    at maybe_assign (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2861:20)
    at expression (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2880:20)
    at expr_list (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2646:24)
    at subscripts (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2780:30)
    at expr_atom (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2633:20)
    at maybe_unary (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2797:19)
    at expr_ops (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2832:24)
    at maybe_conditional (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2837:20)
    at maybe_assign (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2861:20)
    at expression (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2880:20)
    at simple_statement (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2319:55)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2188:19)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2141:24)
    at eval (eval at <anonymous> (/home/forge/my.kendozone.com/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:2909:23)

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ production: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/forge/my.kendozone.com/npm-debug.log
forge@KZ
```

**Comment by brunowerneck** [comment]
This is a problem with UglifyJS. Your code probably have unsupported code by UglifyJS, most likely some ES6 syntax. 

https://github.com/mishoo/UglifyJS2/issues/688

**Comment by xoco70** [comment]
oo you're right... Is there a way to find the error or should I look 1 by 1 through all my js files???

**Comment by xoco70** [comment]
I empty all my vueJS files, and problem persists... I think I will never be able to use production mode... Have no clue where to search

**Comment by xoco70** [comment]
But shouldn't mix first automatically convert my ECMA script to vanilla JS??? 
[Here](https://laravel.com/docs/5.4/mix#working-with-scripts) they say: 

> Mix provides several features to help you work with your JavaScript files, such as compiling ECMAScript 2015, module bundling, minification, and simply concatenating plain JavaScript files. Even better, this all works seamlessly, without requiring an ounce of custom configuration:

**Comment by xoco70** [comment]
Ok. I used combine instead of js. that's why it was not translated

**Comment by shane-scalable** [comment]
I am having the same issue accept it is happening right away and doesn't appear to be compiling the assets first.

```
$ npm run production

> @ production /var/www/site
> node node_modules/cross-env/bin/dist/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/var/www/site/node_modules/cross-env/bin/dist/cross-env.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/n/versions/node/7.6.0/bin/node" "/usr/bin/npm" "run" "production"
npm ERR! node v7.6.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ production: `node node_modules/cross-env/bin/dist/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script 'node node_modules/cross-env/bin/dist/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/dist/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/site/npm-debug.log
```

I have emptied all of my scss files aside from an import of google fonts and deleted everything inside Example.view.

**Comment by iraklisg** [comment]
@shane-scalable From your output it seems that either you have not `cross-env` (try `yarn add cross-env`)  or you are not correctly referencing the `cross-env` in your `package.json`
