### ISSUE TITLE
Upgrade from 5.3 to 5.4 npm run dev not working homestead

### ISSUE THREAD

**Issue by gduffy100** [JeffreyWay/laravel-mix#506]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`):7.6.0 
- NPM Version (`npm -v`): 4.4.0
- OS: Laravel Homestead on Windows 7
vagrant version 1.8.1
Ubuntu 14.04.3 LTS

### Description:

trying to run npm run dev
see error log below , 3 errors:
1) no vendor folder for node-sass
2) webpack error
3) /sass/app.scss doesn't export content

### Steps To Reproduce:

Upgraded from 5.2 -> 5.3 -> 5.4 making all changes from 5.3-5.4 as per github.

not used Elixir previously

Updated package.json and added webpack.mix.js
added app.js and app.scss
steps:
npm install 
npm install https://github.com/JeffreyWay/laravel-mix

vagrant@homestead:~/Code/Citium$ npm run dev

> @ dev /home/vagrant/Code/Citium
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 3 errors                                                                                                                                       9:32:36 PM

 error  in ./resources/assets/sass/app.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/home/vagrant/Code/Citium/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:912:18)
    at Object.getInstalledBinaries (/home/vagrant/Code/Citium/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/home/vagrant/Code/Citium/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/vagrant/Code/Citium/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/vagrant/Code/Citium/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/vagrant/Code/Citium/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/vagrant/Code/Citium/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Code/Citium/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./resources/assets/sass/app.scss 4:14-243
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: Error
    at /home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModule.js:141:35
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/vagrant/Code/Citium/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModule.js:129:2)
    at NormalModule.build (/home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModule.js:180:15)
    at Compilation.buildModule (/home/vagrant/Code/Citium/node_modules/webpack/lib/Compilation.js:142:10)
    at moduleFactory.create (/home/vagrant/Code/Citium/node_modules/webpack/lib/Compilation.js:424:9)
    at /home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModuleFactory.js:242:4
    at /home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModuleFactory.js:93:13
    at /home/vagrant/Code/Citium/node_modules/tapable/lib/Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/home/vagrant/Code/Citium/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/vagrant/Code/Citium/node_modules/tapable/lib/Tapable.js:208:13)
    at onDoneResolving (/home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModuleFactory.js:68:11)
    at onDoneResolving (/home/vagrant/Code/Citium/node_modules/webpack/lib/NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

 error

/home/vagrant/Code/Citium/node_modules/extract-text-webpack-plugin/loader.js??ref--8-0!/home/vagrant/Code/Citium/node_modules/style-loader/index.js!/home/vagrant/Code/Citium/node_modules/css-loader/index.js??ref--8-2!/home/vagrant/Code/Citium/node_modules/postcss-loader/index.js!/home/vagrant/Code/Citium/node_modules/resolve-url-loader/index.js!/home/vagrant/Code/Citium/node_modules/sass-loader/lib/loader.js??ref--8-5!/home/vagrant/Code/Citium/resources/assets/sass/app.scss doesn't export content

            Asset      Size  Chunks                    Chunk Names
       /js/app.js   1.18 MB       0  [emitted]  [big]  /js/app
mix-manifest.json  32 bytes          [emitted]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-03-01T21_32_36_701Z-debug.log

**Comment by borisdamevin** [comment]
> error in ./resources/assets/sass/app.scss

Check this file, the error is in it.

**Comment by gduffy100** [comment]
here is my ./resources/assets/sass/app.scss file
// Fonts
@import url(https://fonts.googleapis.com/css?family=Raleway:300,400,600);

// Variables
@import "variables";

// Bootstrap
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap-sprockets";
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

**Comment by JeffreyWay** [comment]
Can you make sure that node-sass is installed on your machine?

**Comment by gduffy100** [comment]
installed node-sass and removed 
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
from app.scss.
seems to be working now, although I haven't got styles() working yet.
