### ISSUE TITLE
mix.combine: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by jbreuer95** [JeffreyWay/laravel-mix#51]
Not sure if it is me who is doing something wrong, any suggestions?

node -v: 6.9.4
npm -v: 4.0.5

script:
`mix.combine([
    'resources/assets/js/lib/MooTools-Core-1.6.0.js',
    'resources/assets/js/lib/MooTools-More-1.6.0.js',
    'resources/assets/js/classes/ui.class.js',
    'resources/assets/js/classes/menu.class.js',
    'resources/assets/js/classes/login.class.js',
    'resources/assets/js/classes/article.class.js',
    'resources/assets/js/classes/modal.class.js',
    'resources/assets/js/classes/articles.class.js',
    'resources/assets/js/classes/page.class.js',
    'resources/assets/js/classes/forms.class.js',
    'resources/assets/js/classes/read.class.js',
    'resources/assets/js/classes/ui_elements.class.js'
], 'public/js/admin.js');`

error:

> /Users/jellebreuer/Code/valda/node_modules/laravel-mix/src/Mix.js:70
        let entry = this.js.reduce((result, paths) => {
                           ^

> TypeError: Cannot read property 'reduce' of undefined
    at Mix.entry (/Users/jellebreuer/Code/valda/node_modules/laravel-mix/src/Mix.js:70:28)
    at Object.<anonymous> (/Users/jellebreuer/Code/valda/node_modules/laravel-mix/setup/webpack.config.js:46:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/jellebreuer/Code/valda/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/jellebreuer/Code/valda/node_modules/webpack/bin/convert-argv.js:110:17
    at Array.forEach (native)
    at module.exports (/Users/jellebreuer/Code/valda/node_modules/webpack/bin/convert-argv.js:108:15)
    at Object.<anonymous> (/Users/jellebreuer/Code/valda/node_modules/webpack/bin/webpack.js:152:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by DarkaOnLine** [comment]
See https://github.com/JeffreyWay/laravel-mix/issues/39

**Comment by jbreuer95** [comment]
@DarkaOnLine Thanks, just added a dummy file now it works
