### ISSUE TITLE
0.8.8 not run in vue 2.0

### ISSUE THREAD

**Issue by fly-studio** [JeffreyWay/laravel-mix#544]
- Laravel Mix Version: 0.8.8
- Node Version (`node -v`): v7.0.0
- NPM Version (`npm -v`): 3.10.8
- OS: Windows 10 x64

### Steps To Reproduce:
1. package.json
```
    "axios": "^0.15.3",
    "babel-preset-latest": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",
    "cross-env": "^3.2.3",
    "laravel-mix": "^0.8.1",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
```
2. .babelrc 
```
{
	"presets": [
		"latest",
		"stage-0"
	]
}
```

2. Npm will install the vue@2.2.2 and vue-template-compiler@2.2.2 
```
at 2017-03-09 GMT+0800 (PRC)
```

3.  It reported:
```
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 10% building modules 1/1 modules 0 active
Webpack is watching the files…

 95% emitting

 ERROR  Failed to compile with 2 errors                                                                                                           11:11:07


 error  in ./static/js/catalog/vue/catalog-site.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.1.10
- vue-template-compiler@2.2.2

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (................\node_modules\.2.2.2@vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Website\project\teenjoin\node_modules\.10.3.0@vue-loader\lib\parser.js:1:78)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Website\project\teenjoin\node_modules\.10.3.0@vue-loader\lib\loader.js:2:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Website\project\teenjoin\node_modules\.10.3.0@vue-loader\index.js:1:80)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

It can fixed:
```
npm install vue@2.1.10
npm install vue-template-compiler@2.1.10
```

**Comment by chhaihongsrun** [comment]
Great job. 
Thanks

**Comment by JeffreyWay** [comment]
You should be able to fix this by nuking your node_modules directory and reinstalling.

**Comment by fly-studio** [comment]
I deleted `node_modules` then `NPM install`
It also installed the vue 2.2.2, and reported a exception
It's true.

Please attach importance to this issue, please
