### ISSUE TITLE
Error ELIFECYCLE

### ISSUE THREAD

**Issue by alexbowers** [JeffreyWay/laravel-mix#55]
When trying to run this on a mac, I get:

```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! 2017.sucks@1.0.0 webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the 2017.sucks@1.0.0 webpack script 'cross-env NODE_ENV=development webpack --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 2017.sucks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --progress --hide-modules
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 2017.sucks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 2017.sucks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alex/Development/2017.sucks/npm-debug.log
```

log file:

<details>

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack' ]
2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle 2017.sucks@1.0.0~prewebpack: 2017.sucks@1.0.0
6 silly lifecycle 2017.sucks@1.0.0~prewebpack: no script for prewebpack, continuing
7 info lifecycle 2017.sucks@1.0.0~webpack: 2017.sucks@1.0.0
8 verbose lifecycle 2017.sucks@1.0.0~webpack: unsafe-perm in lifecycle true
9 verbose lifecycle 2017.sucks@1.0.0~webpack: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/alex/Development/2017.sucks/node_modules/.bin:/Users/alex/.cargo/bin:/Users/alex/Development/spark-installer:/Users/alex/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alex/.yarn/bin
10 verbose lifecycle 2017.sucks@1.0.0~webpack: CWD: /Users/alex/Development/2017.sucks
11 silly lifecycle 2017.sucks@1.0.0~webpack: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules' ]
12 silly lifecycle 2017.sucks@1.0.0~webpack: Returned: code: 255  signal: null
13 info lifecycle 2017.sucks@1.0.0~webpack: Failed to exec webpack script
14 verbose stack Error: 2017.sucks@1.0.0 webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid 2017.sucks@1.0.0
16 verbose cwd /Users/alex/Development/2017.sucks
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error 2017.sucks@1.0.0 webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules`
22 error Exit status 255
23 error Failed at the 2017.sucks@1.0.0 webpack script 'cross-env NODE_ENV=development webpack --progress --hide-modules'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the 2017.sucks package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=development webpack --progress --hide-modules
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs 2017.sucks
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls 2017.sucks
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

</details>

**Comment by alexbowers** [comment]
Reproduction: 
[laravel-mix-test.zip](https://github.com/JeffreyWay/laravel-mix/files/690797/laravel-mix-test.zip)

**Comment by alexbowers** [comment]
The issue appears to be the lack of the config file. I copied directly from: https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md

 Might be worth including it in here.

**Comment by JeffreyWay** [comment]
The instructions tell you to copy the webpack.config.js file to your project root. So it's not necessary to specify the full config path in that case.
