### ISSUE TITLE
Not compiling linked packages rightly

### ISSUE THREAD

**Issue by vTripes** [JeffreyWay/laravel-mix#724]
- Laravel Mix Version: 0.10.0
- Node Version: 7.4.0
- NPM Version: 4.1.2
- OS: Ubuntu 16.04 LTS

### Description:
After having linked a local private package, Laravel Mix is not able to compile the module as it should (either with `npm run dev` or `npm run prod`), thus throwing this error:
```
Module build failed: Error: Couldn't find preset "env" relative to directory "/usr/share/nginx/user/noderegistries/utilsjs"
    at /usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/share/nginx/user/site/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/share/nginx/user/site/node_modules/babel-loader/lib/index.js:46:20)
    at /usr/share/nginx/user/site/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/usr/share/nginx/user/site/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
```

### Steps To Reproduce:

- Create a node module (`npm init` in a folder) and set it to private in the `package.json`
- In this folder, run `npm link`
- In the app where you want to use the package, run `npm link <pckgname>`
- Import the module in the app's script
- Try compiling by running `npm run dev` or `npm run prod`

**Comment by JeffreyWay** [comment]
As I understand it, this is a general issue with Webpack. So we can't do anything about it on the Mix end.
