### ISSUE TITLE
npm run dev not woring on Window

### ISSUE THREAD

**Issue by razet93** [JeffreyWay/laravel-mix#762]
Laravel Version: 5.4.21
PHP Version: 7.1.1
node v4.4.5
npm v4.5.0

npm commands are completely broken on windows (windows 7 in this case), whenever I run npm run dev I get the following error:

```

> @ dev E:\xampp\htdocs\laravelblog
> npm run development


> @ development E:\xampp\htdocs\laravelblog
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

E:\xampp\htdocs\laravelblog\node_modules\laravel-mix\setup\webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { let path = require('path');
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (E:\xampp\htdocs\laravelblog\node_modules\webpack\bin\convert-argv.js:96:18)
    at E:\xampp\htdocs\laravelblog\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\winuser-pc\AppData\Roaming\npm-cache\_logs\2017-04-29T18_27_27_864Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'npm run development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\winuser-pc\AppData\Roaming\npm-cache\_logs\2017-04-29T18_27_27_938Z-debug.log
```

I tried default `package.json`
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.2.3",
    "jquery": "^3.1.1",
    "laravel-mix": "0.*",
    "lodash": "^4.17.4",
    "vue": "^2.1.10"
  }
}
```

I also tried other helps from internet as well like this one
  ```
"scripts": {
    "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
```

Guide me what's wrong here. Why it is not working

**Comment by QWp6t** [comment]
update node

**Comment by himanshuapril1** [comment]
I'm also facing the same issue since morning. Any luck, anyone?

**Comment by razet93** [comment]
@QWp6t Now I have updated to latest node version (v6.10.2). But facing same problem.

**Comment by pgbrown** [comment]
I get the same error. I commented out the line

`mix.version(['js/app.js','css/app.css']);`

and no errors.

Maybe this points to the problem ....

**Comment by himanshuapril1** [comment]
Seems like there is some issue with Laravel-mix npm package.

**Comment by ruchern** [comment]
@himanshuapril1 More information about your whole environment please?

Like Laravel Mix version, npm version, node version?

**Comment by himanshuapril1** [comment]
@ruchern This is my env details-

NODE - v4.4.5
NPM - v4.5.0
PHP - 5.6.3
Laravel-Mix - 0.*

**Comment by ruchern** [comment]
@himanshuapril1 Your Node version seems to old. Mostly are v6 or v7 now.

**Comment by adiachenko** [comment]
This isn't a bug. Laravel Mix has been written in ES2015 from the start. Node 4 doesn't support most of the feature set of a new spec.

You should use Node 6 which is the latest active LTS release.

**Comment by himanshuapril1** [comment]
There was a typo- I'm using node version 6.9.1. And on this it's not working.

**Comment by ruchern** [comment]
@himanshuapril1 More info on your packages? Assuming that the errors are exactly the same, I suspect it could be the vue-loader issue based on the npm debug attached in first post.

**Comment by realtebo** [comment]
Try npm install cross-env - g.

This is a binary package and on Windows should be used only globally. 

Of course, - g flag could require admin rights. 

Try Also using - - no-bin-links

**Comment by lorvent** [comment]
for me, using `yarn` showing me that error.

if i remove node_modules and use `npm install` its working

so no clue whether its a mix issue or yarn issue.

BTW, installing cross-env globally doesn't fix that issue.

**Comment by kosychike** [comment]
you typed 'npm run development' maybe you should type 'npm run dev'
