### ISSUE TITLE
Running "npm run dev" outputs missing resource error

### ISSUE THREAD

**Issue by NightOwlPrgmr** [JeffreyWay/laravel-mix#767]
- Laravel Mix Version: 0.11.4
- Node Version: 6.10.2
- NPM Version: 4.2.0
- OS: MacOS Sierra (v. 10.12.4)

> Running `npm run dev` outputs an error regarding a missing `css/app.css` file; however, the compilation appears to complete successfully. package.json has been updated with the new `dist/` directory for cross-env.js

### Package.json
```
{
  "private": true,
  "scripts": {
    "dev": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
     "axios": "^0.16.1",
     "bootstrap-sass": "^3.3.7",
     "copy-webpack-plugin": "^4.0.1",
     "jquery": "^3.2.1",
     "laravel-mix": "^0.11.4",
     "lodash": "^4.17.4",
     "vue": "^2.3.0"
 },
 "dependencies": {
     "bxslider": "^4.2.11",
     "dropzone": "^4.3.0",
     "font-awesome": "^4.7.0",
     "lightbox2": "^2.9.0"
  }
}
```

### Terminal Output:
```
$ npm run dev

> @ dev /var/www/vhosts/site/> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 DONE  Compiled successfully in 7331ms                                                                     12:13:23 PM

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'css/app.css'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at File.read (/var/www/vhosts/site/node_modules/laravel-mix/src/File.js:71:19)
    at File.version (/var/www/vhosts/site/node_modules/laravel-mix/src/File.js:129:29)
    at manualFiles.forEach.file (/var/www/vhosts/site/node_modules/laravel-mix/src/Versioning.js:65:47)
    at Array.forEach (native)
    at Versioning.writeHashedFiles (/var/www/vhosts/site/node_modules/laravel-mix/src/Versioning.js:65:26)
    at Versioning.prune (/var/www/vhosts/site/node_modules/laravel-mix/src/Versioning.js:85:14)
    at global.events.listen (/var/www/vhosts/site/node_modules/laravel-mix/src/Versioning.js:30:47)
    at events.(anonymous function).forEach.handler (/var/www/vhosts/site/node_modules/laravel-mix/src/Dispatcher.js:36:47)
    at Array.forEach (native)
    at Dispatcher.fire (/var/www/vhosts/site/node_modules/laravel-mix/src/Dispatcher.js:36:28)
    at Compiler.plugins.push.webpackPlugins.WebpackOnBuildPlugin.stats (/var/www/vhosts/site/node_modules/laravel-mix/setup/webpack.config.js:434:32)
    at Compiler.applyPlugins (/var/www/vhosts/site/node_modules/tapable/lib/Tapable.js:61:14)
    at /var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:266:13
    at Compiler.emitRecords (/var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:362:37)
    at /var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:260:12
    at /var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:355:11
    at next (/var/www/vhosts/site/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/var/www/vhosts/site/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/var/www/vhosts/site/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:352:8)
    at Compiler.<anonymous> (/var/www/vhosts/site/node_modules/webpack/lib/Compiler.js:347:14)
    at /var/www/vhosts/site/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/var/www/vhosts/site/node_modules/webpack/node_modules/async/dist/async.js:998:13)
    at /var/www/vhosts/site/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /var/www/vhosts/site/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

### Steps To Reproduce:
- rm -rf node_modules
- npm install
- npm run dev

**Comment by NightOwlPrgmr** [comment]
Solved, not a mix issue!
