### ISSUE TITLE
Run Dev doesn't work on Cloud 9 

### ISSUE THREAD

**Issue by jhechtf** [JeffreyWay/laravel-mix#777]
- Laravel Mix Version: 0.8.9 (`npm list --depth=0`)
- Node Version (`node -v`): 7.5.0
- NPM Version (`npm -v`): 4.1.2
- OS: Ubuntu 

### Description:

I've tried multiple fixes I've found online about this and none of them seem to work, including changing the command from `cross-env ....` to `node node_modules/cross-env/dist/bin/cross-env.js ...` and still nothing seems to work. I can't figure out what the error message is trying to say. 

I've done `npm install --no-bin-links` to see, and that didn't seem to work either 

### npm-debug.log

```0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v7.5.0/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v7.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v7.5.0/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
10 verbose lifecycle @~dev: CWD: /home/ubuntu/workspace
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 1  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /home/ubuntu/workspace
17 error Linux 4.9.17-c9
18 error argv "/home/ubuntu/.nvm/versions/node/v7.5.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.5.0/bin/npm" "run" "dev"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script 'npm run development'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run development
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ] 
```

### Steps To Reproduce:

1. Create a laravel project on cloud 9.
2. Try to use `npm run dev`
3. run `npm rebuild node-sass` to make sure that node-sass has the `vendor` directory.
4. Try every other fix found on the internet, including the `node node_modules/cross-env/dist/bin/cross-env.js ...` which worked on a windows machine, but will not work on c9.

**Comment by ruchern** [comment]
Try updating Laravel-Mix, some of it's packages might be updated as well.

**Comment by jhechtf** [comment]
By updating laravel-mix and the two things that were listed by doing `npm outdated` I now get this error

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v7.5.0/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v7.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v7.5.0/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
10 verbose lifecycle @~dev: CWD: /home/ubuntu/workspace
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 1  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /home/ubuntu/workspace
17 error Linux 4.9.17-c9
18 error argv "/home/ubuntu/.nvm/versions/node/v7.5.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.5.0/bin/npm" "run" "dev"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script 'npm run development'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run development
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by JeffreyWay** [comment]
You might try adding `mix.disableNotifications()`. 

Otherwise, not sure how Cloud9 is setup so probably best to use a forum instead.
