### ISSUE TITLE
Error: EACCES: permission denied, unlink '/hot'

### ISSUE THREAD

**Issue by mwesterm** [JeffreyWay/laravel-mix#785]
- Laravel Mix Version: 0.11.4 1
- Node Version (`node -v`): v6.10.3
- NPM Version (`npm -v`): 3.10.10.
- OS: Ubuntu Linux 16.04.2

### Description:
Settings up a demo vue project with this description:
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md

With a "npm run dev" I get  following error

fs.js:1103
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EACCES: permission denied, unlink '/hot'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1103:18)
    at File.delete (/home/mwesterm/Projects/laravel/node_modules/laravel-mix/src/File.js:98:16)
    at Mix.detectHotReloading (/home/mwesterm/Projects/laravel/node_modules/laravel-mix/src/Mix.js:82:20)
    at Mix.initialize (/home/mwesterm/Projects/laravel/node_modules/laravel-mix/src/Mix.js:40:14)
    at Object.<anonymous> (/home/mwesterm/Projects/laravel/webpack.config.js:35:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! laravel@1.0.0 dev: `cross-env NODE_ENV=development webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the laravel@1.0.0 dev script 'cross-env NODE_ENV=development webpack --progress --hide-modules'.

### Steps To Reproduce:
- Setup laravel-mix as described
- create an src/app.js-file
-  "npm run dev"

**Comment by ruchern** [comment]
Check your npm global permissions, otherwise you might have to run it with `sudo`.

**Comment by mwesterm** [comment]
>Check your npm global permissions
Looks like ok.
>otherwise you might have to run it with sudo.
Doesn't change anything

**Comment by JeffreyWay** [comment]
Yeah it's a permissions issue on your machine.

**Comment by stevieg83** [comment]
what is likely to be the permissions issue here?

**Comment by JLMorales** [comment]
I am having this problem when running `npm run prod` from envoyer.io, on a forge managed EC2 instance I just launched like two weeks ago. Didn't have this issue before, but then again, I didn't have the copy command I added on my current failing deployment. When I added the `copy` to the mix it broke down with this permission error.

In my case, I am running the following:
laravel-mix:2.0.0
node:8.9.4
npm:5.6.0

The command is being run as the user forge on envoyer.io, the folders there are owned by the forge user and the permissions are normal as just set by forge originally... no issues with permissions anywhere else, except with this. Here's my output...  It would seem like there's a permissions issue like Jeffrey says, (he's definitely not wrong on that account) but this has to be the mother of all hidden permissions issues... I can't see it.

```
> @ prod /home/forge/my-awesome-site.com/releases/20180215212737
> npm run production


> @ production /home/forge/my-awesome-site.com/releases/20180215212737
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 DONE  Compiled successfully in 27276ms21:28:49

/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:49
          throw err0
          ^

Error: EACCES: permission denied, mkdir '/public'
    at Object.fs.mkdirSync (fs.js:885:18)
    at mkdirsSync (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.mkdirsSync (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:37:16)
    at Object.copySync (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/fs-extra/lib/copy-sync/copy-sync.js:49:37)
    at File.copyTo (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/File.js:210:12)
    at FileCollection.copyTo (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/FileCollection.js:88:24)
    at src.forEach.file (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/FileCollection.js:82:38)
    at Array.forEach (<anonymous>)
    at FileCollection.copyTo (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/FileCollection.js:82:17)
    at CopyFilesTask.run (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/tasks/CopyFilesTask.js:14:20)
    at CustomTasksPlugin.runTask (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:34:14)
    at Mix.tasks.forEach.task (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:44)
    at Array.forEach (<anonymous>)
    at Compiler.compiler.plugin.stats (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:23)
    at Compiler.applyPlugins (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:264:11)
    at Compiler.emitRecords (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/forge/my-awesome-site.com/releases/20180215212737/node_modules/async/dist/async.js:1050:13)
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/async/dist/async.js:958:16
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/cacache/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/forge/my-awesome-site.com/releases/20180215212737/node_modules/yargs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What my `mix.copy()` is trying to do is throw some font files into the `public/fonts` folder. These folders are both writable... (permissions for the fonts folder, similar to the public folder different number of links is all) `drwxrwxr-x  3 forge forge` and owned by the user executing the `npm run prod` command, so I am at a loss in figuring out the permissions mess here... 

It is also happening locally, only for this project. I haven't seen this behavior on other projects, will try rolling back mix versions to see if that does anything... (doubting it a lot, but something's gotta give...)

**Comment by tpraxl** [comment]
I find `mkdir '/public'` suspicious. It sounds like it's trying to create a public folder in the root directory, which is very likely not correct. Can you post your config?

**Comment by JLMorales** [comment]
@tpraxl   My man! You just called a very sneaky thing to my attention. I must be burned out... didn't see it... 

I had started the path with a slash... of course it would try to go and make the dir in the root... where the user has no permission to write to. 

Man, the stupidest of details... I should make a scrapbook with printed screenshots of these moments.... take it with me to conventions and stuff... should be funny.

Thanks!

**Comment by ruchern** [comment]
@LordZombi that doesn’t seem to right.

**Comment by ITDeveloperDotUz** [comment]
This issue may happen if you are building project or running npm with other user than owner of the project directory. 
In my case there was a problem with nuxt compilation when I run npm run dev similar error appeared. 
my project was located at /var/www/project and owner of directory was nginx which is www-data. and I ran npm run dev with non-root user on phpstorm. When I re changed owner to my user it worked.
