### ISSUE TITLE
.DS_Store and mix.copyDirectory permissions error

### ISSUE THREAD

**Issue by codev0** [JeffreyWay/laravel-mix#791]
- Laravel Mix Version: 0.11.3
- Node Version (`node -v`): v6.9.2
- NPM Version (`npm -v`): 4.1.2
- OS: macOS Sierra 10.12.4

### Description:
Image copy process `mix.copyDirectory('resources/assets/images', 'public/images');` returns error.

```
Copying resources/assets/images/.DS_Store to ../public/images
fs.js:1089
  return binding.unlink(pathModule._makeLong(path));
Error: EPERM: operation not permitted, unlink '../public/images'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at copyFileSync (../node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:15:10)
    at Object.copySync (../node_modules/fs-extra/lib/copy-sync/copy-sync.js:43:5)
    at FileCollection.copyTo (../node_modules/laravel-mix/src/FileCollection.js:41:12)
    at FSWatcher.chokidar.watch.on.updatedFile (../node_modules/laravel-mix/src/FileCollection.js:77:47)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at FSWatcher.<anonymous> (../node_modules/chokidar/index.js:191:15)
    at FSWatcher._emit (../node_modules/chokidar/index.js:233:5)
    at FSWatcher.<anonymous> (../node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (../node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at FSWatcher.<anonymous> (../node_modules/chokidar/lib/fsevents-handler.js:236:16)
    at filteredListener (../node_modules/chokidar/lib/fsevents-handler.js:58:7)
    at ../node_modules/chokidar/lib/fsevents-handler.js:83:11
    at Array.forEach (native)
    at FSEvents.<anonymous> (/Users/codev0/projects/mamp/buhta-landing/node_modules/chokidar/lib/fsevents-handler.js:82:34)
    at emitThree (events.js:116:13)
    at FSEvents.emit (events.js:194:7)
    at Immediate.<anonymous> (/Users/codev0/projects/mamp/buhta-landing/node_modules/fsevents/fsevents.js:47:11)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)```

**Comment by ruchern** [comment]
What is your permission for `public/` folder?

`ls -l` should show it.

**Comment by codev0** [comment]
@ruchern Hi, thanks for response. Permission for `/public` is `drwxr-xr-x`.

**Comment by ruchern** [comment]
@codev0 Just for testing and to make it work now, perhaps you want to set full permissions to the folder?

`chmod -R 777 public/`

If it works, then we will change the permission to restrict a little bit.

**Comment by codev0** [comment]
@ruchern It isn't helps :(

**Comment by codev0** [comment]
I observe this issue when I add new images to resources folder, and laptop go to sleep (close top)

**Comment by hdl-helsinki** [comment]
I added this on line 403:

```js
if (Mix.copy.length) {
    new webpackPlugins.CopyWebpackPlugin(Mix.copy, {
        ignore: ['.DS_Store']
    });
}
```

**Comment by ruchern** [comment]
@hdl-helsinki What is the `if (Mix.copy.length)` for?

**Comment by hdl-helsinki** [comment]
@ruchern I'm not sure, it comes on the [original code](https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.config.js#L398).

**Comment by JeffreyWay** [comment]
Closing this, as we no longer use that CopyWebpackPlugin in 1.0.
