### ISSUE TITLE
Latest laravel mix Module build failed: TypeError: pPipe(...) is not a function

### ISSUE THREAD

**Issue by stefensuhat** [JeffreyWay/laravel-mix#803]
- Laravel Mix Version: 0.11.4
- Node Version (`node -v`): 7.10.0
- NPM Version (`npm -v`): 4.2.0
- OS: Windows 10

### Description:
compiling and return those error

### Steps To Reproduce:
on my .scss file there is this code:

```
 .secondary {
       background: $secondary-color url('images/promo2_texture.png');
}
```

when those code compile it return error 
```
 error  in ./src/styles/images/promo2_textur.png

Module build failed: TypeError: pPipe(...) is not a function
    at Function.module.exports.buffer (D:\www\example\node_modules\imagemin\index.js:64:60)
    at Object.module.exports (D:\www\example\node_modules\img-loader\index.js:43:6)

 @ ./~/css-loader!./~/sass-loader/lib/loader.js!./src/styles/main.scss 7:28545-28572 7:28655-28682
 @ ./src/styles/main.scss
 @ ./src/index.js
 @ multi ./src/index.js
```

**Comment by stefensuhat** [comment]
Solved this by removing `react-router-transition`.  https://github.com/maisano/react-router-transition

Seems odd to impact this package .
