### ISSUE TITLE
Not sure if issue or own fault

### ISSUE THREAD

**Issue by sipman** [JeffreyWay/laravel-mix#83]
I'm trying to get laravel-mix to work, but i keep getting this error:
`SyntaxError: /Users/{USER}/package.json: Error while parsing JSON - Unexpected token < in JSON at position 2
    at Object.parse (native)`

Heres is a small GIF of whats happening:
![issue](https://cloud.githubusercontent.com/assets/6494644/21889834/2a712b8e-d8cb-11e6-942d-a97f1cfb6340.gif)

I'm running:
* node v6.9.4
* npm  v4.1.1

More detailed error message is here:
`ERROR in ./src/app.js
Module build failed: SyntaxError: /Users/{USER}/package.json: Error while parsing JSON - Unexpected token < in JSON at position 2
    at Object.parse (native)
    at ConfigChainBuilder.addConfig (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:102:30)
    at buildConfigChain (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:58)
    at File.initOptions (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/{USER}/{PROJECTPATH}/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/{USER}/{PROJECTPATH}/node_modules/babel-loader/lib/index.js:38:20)
    at /Users/{USER}/{PROJECTPATH}/node_modules/babel-loader/lib/fs-cache.js:78:18
    at ReadFileContext.callback (/Users/{USER}/{PROJECTPATH}/node_modules/babel-loader/lib/fs-cache.js:14:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
 @ multi ./src/app.js ./src/app.scss`

**Comment by sipman** [comment]
I fixed the issue, for some reason there was an package.json file at my user directory. That file got called when i ran "npm run dev" -- INSIDE that file there was an error.. So i fixed it by deleting the file and now everything is running SMOOOOTH...

So it was my own fault, sorry for posting :)
