### ISSUE TITLE
Error if no mix.js() in webpack.config.js?

### ISSUE THREAD

**Issue by claytonrcarter** [JeffreyWay/laravel-mix#87]
Issuing command `npm run webpack` with this `webpack.mix.js`:
```
let mix = require('laravel-mix').mix;

mix.sass('resources/assets/sass/app.scss', 'public/css')
```

results in an error:

```
> @ webpack /Users/crcarter/Software/Fedco/fedco-new-db
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/laravel-mix/src/Mix.js:67
        let entry = this.js.reduce((result, paths) => {
                           ^

TypeError: Cannot read property 'reduce' of undefined
    at Mix.entry (/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/laravel-mix/src/Mix.js:67:28)
    at Object.<anonymous> (/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/laravel-mix/setup/webpack.config.js:46:28)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/crcarter/Software/Fedco/fedco-new-db/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/webpack/bin/convert-argv.js:107:15)
    at Object.<anonymous> (/Users/crcarter/Software/Fedco/fedco-new-db/node_modules/webpack/bin/webpack.js:152:40)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ webpack script 'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
```

This is a new `laravel-mix` setup (migrating from `laravel-elixir`) so it's very possible that I messed something up on the install.

**Comment by kpilard** [comment]
You need a `mix.js()` part

https://github.com/JeffreyWay/laravel-mix/issues/39

**Comment by claytonrcarter** [comment]
Oh, sorry. Closing as duplicate.
