### ISSUE TITLE
CircleCI failed

### ISSUE THREAD

**Issue by jinseokoh** [JeffreyWay/laravel-mix#935]
### Description:

everything works as intended within my local environment, however, on CircleCI it produces the following error.

```
$ npm install
-|-npm WARN engine laravel-mix@1.0.6: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/-\/\|-\/-|-\/\|-|/-\/\|-|-npm WARN engine dotenv@4.0.0: wanted: {"node":">=4.6.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine extract-text-webpack-plugin@2.1.2: wanted: {"node":">=4.3.0 < 5.0.0 || >= 5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-loader@2.0.6: wanted: {"node":">= 4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine style-loader@0.18.2: wanted: {"node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine sass-loader@6.0.6: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine uglifyjs-webpack-plugin@0.4.6: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine babel-loader@7.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine css-loader@0.28.4: wanted: {"node":">=0.12.0 || >=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine webpack-dev-server@2.5.0: wanted: {"node":">=4.7"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine clean-css@4.1.4: wanted: {"node":">= 4.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine webpack@3.0.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|-\|-|/\/\|/-|-\/\npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN peerDependencies The peer dependency webpack@^2.2.0 included from extract-text-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/\|npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin-optipng@5.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin-mozjpeg@6.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin-pngquant@5.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin-gifsicle@5.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin@5.3.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine imagemin-svgo@5.2.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/\/npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine schema-utils@0.3.0: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
-npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine find-cache-dir@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine camelcase@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine schema-utils@0.3.0: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-load-config@1.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/\npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine html-minifier@3.5.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine schema-utils@0.3.0: wanted: {"node":">= 4.3 < 5.0.0 || >= 5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine pify@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-|-|/\|-|-npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss@5.2.17: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-|/\/\npm WARN engine exec-buffer@3.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
-npm WARN engine exec-buffer@3.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|npm WARN engine exec-buffer@3.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-load-config@1.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss@5.2.17: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine exec-buffer@3.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine p-pipe@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine make-dir@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine file-type@4.4.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-npm WARN engine follow-redirects@1.2.4: wanted: {"node":">=4.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
|-|/npm WARN engine make-dir@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine pkg-dir@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/-|/-\/-|npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
/npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
|-npm WARN engine postcss-load-plugins@2.3.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine cosmiconfig@2.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-load-options@1.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
/\/-\|npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\/-|/-|/-|/\|/\|npm WARN engine cosmiconfig@2.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-load-plugins@2.3.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine postcss-load-options@1.2.0: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
/\|-npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine execa@0.5.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine execa@0.5.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine execa@0.5.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine execa@0.5.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-|-\/-\/npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/\|-\|/-\|npm WARN engine find-up@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-|-\|/\|/-\/-\|-\|/-|/-\|/\|/\|/-\|/\|/-\|/-\|-\/-\|/-|/-\|-\|/-\/-\|/-|/-|/-|/-\|/-|/-\|-\|-|/\|/-\|-\|-\|-|npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-|/\|/-\|-\|/-\/-\|npm WARN engine locate-path@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/\|/\|/-\/-\|/-\|/-\|npm WARN engine camelcase@4.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine os-locale@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine string-width@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine read-pkg-up@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-|/-\|/\|/-|/-\|/\|/-\|-|-\|/\|-\/-\|/-\|-\/\|/-npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\|-\|/-\|/\|/\|/\|npm WARN engine normalize-url@1.9.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/\|-\|-|/-\/-\|-\|/-\/-\|/-\npm WARN engine p-locate@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-exists@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\|-\|/npm WARN engine vendors@1.0.1: wanted: {"node":">=0.11.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|-\npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/\|/npm WARN engine execa@0.5.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine mem@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine find-up@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine read-pkg@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-|/-\/-|/-\|-|-|-\|/-\/\|/-|-\|-\|/-\/-\|/\|/\|/-\|/-\|/-\/-\/-|-\|-\/\|/-|/-|/-\|npm WARN engine postcss@6.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-|-\npm WARN engine locate-path@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/\|/\|/\|-|/\|/-|/-\/-\/-\|/\|/npm WARN engine p-finally@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine npm-run-path@2.0.2: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/\|/-\|-\/\|/npm WARN engine p-limit@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|-\|-\npm WARN engine mimic-fn@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-|/\|/npm WARN engine load-json-file@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-type@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|-\|-\|/-\/-\|/-\|/-|/\|/-|/-npm WARN engine p-locate@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine path-exists@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-|/-\|/-npm WARN engine path-key@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-|/-\|/-\/-\|/-\|/-\|/-\|/-\|/-\|/-\|-\|/-\|/-\|/-\|-\|/-\|/-\|/-npm WARN engine strip-bom@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-\|npm WARN engine p-limit@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-|/-\|/-\|/-\npm WARN peerDependencies The peer dependency webpack@^2.2.0 included from webpack-dev-server will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\npm WARN engine coa@1.0.3: wanted: {"node":">= 4.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-\|/-\|/-\|/-\npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-\|/-\|/npm WARN engine del@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine portfinder@1.0.13: wanted: {"node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine esprima@3.1.3: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-npm WARN engine pify@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine p-map@1.1.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\| 

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

/
module.js:340
    throw err;
          ^
Error: Cannot find module 'sync-exec'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/uglifyjs-webpack-plugin/lib/post_install.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
/-\|/-\|/-\|/-\|/-\npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\/-\|/-\|/-\|/-\|/-\|/-\|-\|/-\|/-\|/-\npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|-|/-\|/-\|/-\/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|-|/-|npm WARN engine coa@1.0.3: wanted: {"node":">= 4.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
-\|-\|-\|/\|/-\|/-\|-|/-\|/-\|-|/-\|-\|/\|/-|/-\|/-|-\|-\|-\/-\/-|/-\/-\/-|/\|/-\/-|/\|/\|/\/-|/-\|/\|/-|/-\/-\|-|/\|-|/\|-|/\/-|/\|-\|/-|/-|/\|-\/-|-\/-|/\/\|-\/\\/-|-\/-\|/\|/\|/-|/\|-|/\|-\|-\/\|-|/\|-|/\/\/-|/\|-|/npm WARN engine supports-color@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|/\/-|--|-\/\/\|/-|/\/-|-\-|-|-|/\/- 

> gifsicle@3.0.4 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/img-loader/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

\|--|  ✔ gifsicle pre-build test passed successfully

 

> optipng-bin@3.1.4 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/img-loader/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

/\-|-\/-|-\/-  ✔ optipng pre-build test passed successfully
npm WARN engine loader-utils@1.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine loader-runner@2.3.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine enhanced-resolve@3.1.0: wanted: {"node":">=4.3.0 <5.0.0 || >=5.10"} (current: {"node":"0.10.33","npm":"2.13.5"})

> pngquant-bin@3.1.1 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/img-loader/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

-|-\/\/-|-|-\/\/-|-\/-|-|-  ✔ pngquant pre-build test passed successfully
 

> mozjpeg@4.1.1 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/img-loader/node_modules/imagemin-mozjpeg/node_modules/mozjpeg
> node lib/install.js

-\|-|-\/\|-|/\/\-|/\/-|  ✔ mozjpeg pre-build test passed successfully
-|-|-\/\|-|-\/\/\/\/-|-|-\/\/npm WARN engine pbkdf2@3.0.12: wanted: {"node":">=0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/--|/-|-\/\/\|-|-|-\/\/\|--|-|-\/\/\/\/-|-\/\|-|/-\/\|-\/\/-\|-|-|-|/\/\/\|-|/\/\/-|-|/\|-|-|-|npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/-|-|--|/-|-|/\-\/\/-|-|npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.33","npm":"2.13.5"})
-|-\/\|-\/\/\/\/-|-\/\|/-|/\/-\/-|-\/\|-|/\/-|/\/\|-|-\/\/\|-\-|/\/-|-\/\/\/npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
|-\/\\/\|-|-\/\/-\-|-\/\/\/\/-npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.33","npm":"2.13.5"})
\/\/--|-|-\/\|/\/\|/\|\/\|-|-\/\|/\/\/-|-|npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.13.5"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.33","npm":"2.13.5"})
/\/-\|-\|-|npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
\-|-|/\/\|/-\-\--|/npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.33","npm":"2.13.5"})
-
> node-sass@4.5.3 install /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-11_binding.node
Download complete
Binary saved to /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/node-sass/vendor/linux-x64-11/binding.node
Caching binary to /home/ubuntu/.npm/node-sass/4.5.3/linux-x64-11_binding.node

> node-sass@4.5.3 postinstall /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/node-sass
> node scripts/build.js

Binary found at /home/ubuntu/prime-main-server/node_modules/laravel-mix/node_modules/node-sass/vendor/linux-x64-11/binding.node
Testing binary
Binary is fine
npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "node" "/home/ubuntu/nvm/v0.10.33/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.13.5
npm ERR! code ELIFECYCLE

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! This is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/prime-main-server/npm-debug.log

npm install returned exit code 1

Action failed: npm install
```

**Comment by ruchern** [comment]
This has nothing to do with `Laravel-Mix`. The problem lies with `CircleCI` having an outdated node and npm version.

There should be steps for you to configure them to use the latest version.

**Comment by jinseokoh** [comment]
@ruchern thank you. i'm closing this issue now.
