### ISSUE TITLE
Dependencies missing for install & Fail to exec dev script

### ISSUE THREAD

**Issue by djfurman** [JeffreyWay/laravel-mix#94]
## Observed Behavior

After running `npm run dev` recieved message "Failed to exec dev script"

## Suspected Cause

Dependencies are missing for fresh installation backdating to against an exisiting Laravel 5.3 app 

## Reproduction Steps

Using an existing Laravel 5.3 app (all API driven, but it would be good to add a simple UI to update the data).

1. Delete `gulpfile.js`
2. Delete `yarn.lock` file
3. Recursively delete `node_modules` directory
4. Run `yarn add laravel-mix`
5. Copy `webpack.config.js` and `webpack.mix.js` to home directory.
6. Copy scripts from [npm-scripts laravel-mix documentation](https://github.com/JeffreyWay/laravel-mix/blob/master/docs/installation.md#npm-scripts) to `packages.json`
7. Run `npm run dev`

## Local Stack

- Node v6.3.1
- NPM v4.1.1

## Work Around

I was able to work around the issue and get to a working instance by:

1. Manually install webpack 2.2.0-rc.4 `yarn add webpack@2.2.0-rc.4`
3. Manually install graceful-fs `yarn add graceful-fs`
1. Run `webpack --progress --hide-modules` instead of the script

### NPM Error Log

```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.1/bin/node',
1 verbose cli   '/Users/dfurman/.node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.1.1
3 info using node@v6.3.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /Users/dfurman/.node/lib/node_modules/npm/bin/node-gyp-bin:/Users/dfurman/Code/web/routing/node_modules/.bin:/Users/dfurman/.node/bin:/Users/dfurman/.composer/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle @~dev: CWD: /Users/dfurman/Code/web/routing
11 silly lifecycle @~dev: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development webpack --watch --progress --hide-modules' ]
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/Users/dfurman/.node/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:852:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid @
15 verbose cwd /Users/dfurman/Code/web/routing
16 error Darwin 15.6.0
17 error argv "/usr/local/Cellar/node/6.3.1/bin/node" "/Users/dfurman/.node/bin/npm" "run" "dev"
18 error node v6.3.1
19 error npm  v4.1.1
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error @ dev: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules`
24 error spawn ENOENT
25 error Failed at the @ dev script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the  package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     cross-env NODE_ENV=development webpack --watch --progress --hide-modules
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

```

**Comment by djfurman** [comment]
@JeffreyWay ,

Would you be interested in a PR for including webpack and graceful-fs as dependencies to laravel-mix?

Aside: Long-time listener, first-time caller ;) I'm loving the simplified laravel-mix framework and I'm excited to cut my current projects over to it. Keep up the awesomeness!

**Comment by djfurman** [comment]
Result is replicated using Node 7.4.0 (tested from my other rig).

**Comment by rikless** [comment]
Same here 

```
npm ERR! Linux 4.8.13-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! helpmepyz@1.0.0 dev: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the helpmepyz@1.0.0 dev script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the helpmepyz package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --watch --progress --hide-modules
```

**Comment by JeffreyWay** [comment]
@djfurman - Hmm, Webpack already is a dependency of Laravel Mix.

**Comment by djfurman** [comment]
That's odd. Since we both installed with yarn I'll nuke my node_modules folder and try with npm direct install. Maybe it's a yarn issue? I'll let you know the results this evening. 

Thanks for the quick response!

**Comment by nmfzone** [comment]
@rikless I'm using Yarn also here, but there is no issue at all (in here :D). I guess, it isn't an issue, it just because you don't have `cross-env` or `webpack` globally.

**Comment by rikless** [comment]
@nmfzone Actually, I have boths :) I was just talking about yarn to give more context ;)

**Comment by nmfzone** [comment]
@rikless Haha, so I'm completely wrong about it.😝  I just guess because I've an error like that before. And the problem I don't have `webpack` globally.

**Comment by rikless** [comment]
@nmfzone WOUPS, to be sure, I've installed it again, and now it works ! Just compiled with webpack last week, and it worked, so I don't understand, but thanks :)

**Comment by nmfzone** [comment]
@rikless hmmm 😕  So, I'm not wrong about it ;) Anyway, good to see it works.

**Comment by djfurman** [comment]
Installing both webpack & cross-env works locally (in the project) too. I see both listed in the `packages.json` dependencies so why they aren't being pulled in confuses me, but we do have a work around!

**Comment by ricardocanelas** [comment]
I have a similar problem: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack' ]
2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle @~prewebpack: @
6 silly lifecycle @~prewebpack: no script for prewebpack, continuing
7 info lifecycle @~webpack: @
8 verbose lifecycle @~webpack: unsafe-perm in lifecycle true
9 verbose lifecycle @~webpack: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rica/learnspace/vuejs/www/simple-crud/node_modules/.bin:/usr/local/php5/bin:/Users/rica/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle @~webpack: CWD: /Users/rica/learnspace/vuejs/www/simple-crud
11 silly lifecycle @~webpack: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
12 silly lifecycle @~webpack: Returned: code: 2  signal: null
13 info lifecycle @~webpack: Failed to exec webpack script
14 verbose stack Error: @ webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /Users/rica/learnspace/vuejs/www/simple-crud
17 error Darwin 15.0.0
18 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error @ webpack: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 2
23 error Failed at the @ webpack script 'cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

my package.json
```
{
  "private": true,
  "scripts": {
    "webpack": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "dev": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.1.4",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",
    "laravel-mix": "^0.4.0",
    "lodash": "^4.14.0",
    "vue": "^2.0.1"
  }
}
```

**Comment by nmfzone** [comment]
@ricardocanelas Do you read other comments above?

**Comment by ricardocanelas** [comment]
@nmfzone Sorry, I deleted my commented, because it was my mistake.. I wrote 'resource', and should be 'resources'.

**Comment by nmfzone** [comment]
@ricardocanelas Whoops, nope. Good to see it works.

**Comment by bvangraafeiland** [comment]
I've encountered this as well. When using yarn to install modules, `cross-env` seems to be missing, but with `npm install` there is no problem. Could there be something that is run by npm but not by yarn?

**Comment by adriaanzon** [comment]
This is an issue with yarn: https://github.com/yarnpkg/yarn/issues/1487.

**Comment by JeffreyWay** [comment]
Yeah this is a Yarn issue. Nothing for us to do until it gets fixed on their end. There are 571 open issues right now, so I'm just using good ole `npm install` right now. I recommend the same.
