### ISSUE TITLE
Error open fonts files

### ISSUE THREAD

**Issue by dib258** [JeffreyWay/laravel-mix#941]
I have a Laravel project I'm working on and Laravel-mix was preinstalled in version 0.8.8. When I was making the following command `npm run production` I had an error with uglifyJs and this '`' character. 

After searching on the web I found no correct fix for this but to try to update laravel-mix to the new version. Which is 1.0.3.

Since I did that nothing works anymore. I found out that the web.config.js was completly remodeled and I had a custom one out of node_modules. No warning just so many errors...

I fixed a few of them but now I face one really don't understand even after few hours of search.

```
fs.js:651
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                         ^
Error: ENOENT: no such file or directory, open '/Users/me/LaravelProjects/friendsitting/public/resources/assets/fonts/fontawesome-webfont.eot'
at Object.fs.openSync (fs.js:651:18)
at Object.fs.readFileSync (fs.js:553:33)
at File.read (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/File.js:180:19)
at File.version (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/File.js:190:25)
at Manifest.hash (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/Manifest.js:55:65)
at manifest.forEach.file (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:47)
at Array.forEach (native)
at CustomTasksPlugin.applyVersioning (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:79:18)
at Compiler.compiler.plugin.stats (/Users/me/LaravelProjects/friendsitting/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:12:22)
at Compiler.applyPlugins (/Users/me/LaravelProjects/friendsitting/node_modules/tapable/lib/Tapable.js:61:14)
at /Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:273:13
at Compiler.emitRecords (/Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:369:37)
at /Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:267:12
at /Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:362:11
at next (/Users/me/LaravelProjects/friendsitting/node_modules/tapable/lib/Tapable.js:154:11)
at Compiler.compiler.plugin (/Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
at Compiler.applyPluginsAsyncSeries1 (/Users/me/LaravelProjects/friendsitting/node_modules/tapable/lib/Tapable.js:158:13)
at Compiler.afterEmit (/Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:359:8)
at Compiler.<anonymous> (/Users/me/LaravelProjects/friendsitting/node_modules/webpack/lib/Compiler.js:354:14)
at /Users/me/LaravelProjects/friendsitting/node_modules/async/dist/async.js:421:16
at iteratorCallback (/Users/me/LaravelProjects/friendsitting/node_modules/async/dist/async.js:998:13)
at /Users/me/LaravelProjects/friendsitting/node_modules/async/dist/async.js:906:16
at /Users/me/LaravelProjects/friendsitting/node_modules/graceful-fs/graceful-fs.js:43:10
at FSReqWrap.oncomplete (fs.js:135:15)
```

Which seems to be an error when opening the fonts file I had the same error before with FontAwesome.otf now it's on eot file. 

Does anyone have the same error ? 
Did something change in the configuration of webpack that could return theses kind of errors ?

Thanks in advance for you answer !

**Comment by DannyFeliz** [comment]
This it seen to be related to my issue #939

**Comment by dib258** [comment]
Thanks that's it
