### ISSUE TITLE
Windows Fail: Wrong Paths

### ISSUE THREAD

**Issue by connerbw** [JeffreyWay/laravel-mix#970]
- Laravel Mix Version: #.#.# (`npm list --depth=0`): laravel-mix@1.0.7
- Node Version (`node -v`):  v6.10.3
- NPM Version (`npm -v`): 5.1.0
- OS:  Windows 10, [Git Bash](https://git-for-windows.github.io/)

### Description:

I'm trying to build assets on Windows like on OSX. It's not working at all.

### Steps To Reproduce:

```
git clone git@github.com:pressbooks/pressbooks.git
cd pressbooks
git checkout assets-on-windows
npm
npm run production
```

**_Expected:_** 
Works like it does on OSX

**_Actual:_** 
+ CSS/JS files incorrectly copied to `/assets/dist/assets/dist`
+ Error:

```
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\myself\Desktop\testing\pressbooks\assets\dist\assets\dist\styles\organize.css'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at File.read (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\File.js:180:19)
    at File.version (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\File.js:190:25)
    at Manifest.hash (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\Manifest.js:55:65)
    at manifest.forEach.file (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:79:47)
    at Array.forEach (native)
    at CustomTasksPlugin.applyVersioning (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:79:18)
    at Compiler.compiler.plugin.stats (C:\Users\myself\Desktop\testing\pressbooks\node_modules\laravel-mix\src\plugins\CustomTasksPlugin.js:12:22)
    at Compiler.applyPlugins (C:\Users\myself\Desktop\testing\pressbooks\node_modules\tapable\lib\Tapable.js:61:14)
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:273:13
    at Compiler.emitRecords (C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:369:37)
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:267:12
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:362:11
    at next (C:\Users\myself\Desktop\testing\pressbooks\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.compiler.plugin (C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Users\myself\Desktop\testing\pressbooks\node_modules\tapable\lib\Tapable.js:158:13)
    at Compiler.afterEmit (C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:359:8)
    at Compiler.<anonymous> (C:\Users\myself\Desktop\testing\pressbooks\node_modules\webpack\lib\Compiler.js:354:14)
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\myself\Desktop\testing\pressbooks\node_modules\async\dist\async.js:998:13)
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\async\dist\async.js:906:16
    at C:\Users\myself\Desktop\testing\pressbooks\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Configs:

webpack.mix.js:
https://github.com/pressbooks/pressbooks/blob/assets-on-windows/webpack.mix.js

package.json:
https://github.com/pressbooks/pressbooks/blob/assets-on-windows/package.json

Can anyone help?

**Comment by connerbw** [comment]
```
        console.log(output.pathFromPublic());
        console.log('/' + Config.publicPath);

        if (! output.pathFromPublic().startsWith('/' + Config.publicPath)) {
            output = new File(path.join(Config.publicPath, output.pathFromPublic()));
        }
```

Outputs:

```
/assets/dist
\assets\dist\scripts\textboxes.js
```

**Comment by connerbw** [comment]
Changes `.scripts()` to `.js()`

**Comment by connerbw** [comment]
I fixed it by changing:

```
mix.setPublicPath('assets/dist')
```

To:

```
let path = require('path');
mix.setPublicPath(path.join('assets', 'dist'))
```

Regards,
