### ISSUE TITLE
npm run dev errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by zcdll** [JeffreyWay/laravel-mix#987]
using npm@5.2.0
using node@v6.11.0
Ubuntu 16.04
PHP 7.1

I download the latest laravel source code from github.com and run `composer install`, it works fine.
Then I run `npm install`, it shows

```BASH
> node-sass@4.5.3 install /home/zcdll/Coder/Projects/jumei/jumei-laravel-wechat/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/linux-x64-48_binding.node": 

ETIMEDOUT

Timed out attemping to establish a remote connection

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```
Then I use export HTTP_PROXY and the terminal told me it installed the node-sass and I run `npm run dev`, I got errors below.

```BASH
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@5.2.0
3 info using node@v6.11.0
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/zcdll/Coder/test/php/laravel-5.4.23/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/zcdll/Coder/test/php/laravel-5.4.23/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin
9 verbose lifecycle @~development: CWD: /home/zcdll/Coder/test/php/laravel-5.4.23
10 silly lifecycle @~development: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~development: Returned: code: 2  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @
15 verbose cwd /home/zcdll/Coder/test/php/laravel-5.4.23
16 verbose Linux 4.4.0-83-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "development"
18 verbose node v6.11.0
19 verbose npm  v5.2.0
20 error code ELIFECYCLE
21 error errno 2
22 error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 2
23 error Failed at the @ development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

I have try many times and search lots of infomations, unfortunately nothing worked.

**Comment by JeffreyWay** [comment]
This is likely related to a bug in npm 5.2, which just came out yesterday. They've fixed it, but haven't made a new release available yet. Until then, you can downgrade to an earlier release.

**Comment by zcdll** [comment]
I downgrade npm to v5.1.0, and re-create a project with the latest laravel on github.com, unfortunately, I got  the same errors.

**Comment by ruchern** [comment]
Downgrade to `5.1.0` nuke your `node_modules` folder and `package-lock.json`

**Comment by zcdll** [comment]
@ruchern  @JeffreyWay  Could you guys tell me the specific versions of Ubuntu(System) , PHP, node, npm, Laravel, laravel-mix that you are using now or you have tested that could run successfully.

Unfortunately, I am in China.You know the internet great wall.

I have spent much time to conquer it and I would like to get it down!

**Comment by ruchern** [comment]
Personally, I am running:

Ubuntu 17.04
PHP 7.1
Node 8.1.4
npm 5.1.0
Laravel-mix 1.2.0

**Comment by zcdll** [comment]
@ruchern @JeffreyWay  I have solved my problem with your suggestions that I delete my `node_modules` folder and `package-lock.json`, then downgrade `npm` to `5.1.0`.
Thanks a lot !

**Comment by ruchern** [comment]
Since it's now working, perhaps you might want to close this issue?

**Comment by ksidht** [comment]
You dont need to downgrade
For 5.2.0+ 
`npx create-react-app my-app`
instead of 
```
npm install -g create-react-app
create-react-app my-app
```
Will Solve issue.
