### ISSUE TITLE
npm run dev, npm rum prod and npm run watch errors on Windows 10 (15063.413)

### ISSUE THREAD

**Issue by rafael-franca** [JeffreyWay/laravel-mix#988]
- Laravel Mix Version: 1.2.0
- Node Version: 6.11.0
- NPM Version: 5.2.0
- OS: Windows 10 (15063.413)

### Description:
I receive this error log file, when execute ```npm run anything```.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rafae\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.2.0
3 info using node@v6.11.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: C:\Users\rafae\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\wamp64\www\blog\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\wamp64\bin\php\php7.0.10;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\wamp64\bin\php;C:\Program Files\PuTTY\;C:\Users\rafae\AppData\Local\Microsoft\WindowsApps;C:\Users\rafae\AppData\Local\atom\bin;C:\Users\rafae\AppData\Roaming\Composer\vendor\bin;C:\Users\rafae\AppData\Roaming\npm
9 verbose lifecycle @~dev: CWD: C:\wamp64\www\blog
10 silly lifecycle @~dev: Args: [ '/d /s /c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 2  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\rafae\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\rafae\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid @
15 verbose cwd C:\wamp64\www\blog
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rafae\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v6.11.0
19 verbose npm  v5.2.0
20 error code ELIFECYCLE
21 error errno 2
22 error @ dev: `npm run development`
22 error Exit status 2
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

### Steps To Reproduce:
1. Create a new project on Laravel;
2. Execute ```composer update```;
3. Execute ```npm install```;
4. Execute ```npm run anything```;

**Comment by rafael-franca** [comment]
I was able to solve it, but I had to install the following packages: ```npm install babel-loader sass-loader vue-loader```.

For some reason, they were deleted, and even by deleting the ```node_modules``` folder, and reinstalling them, they were not installed.

**Comment by JeffreyWay** [comment]
> For some reason, they were deleted, and even by deleting the node_modules folder, and reinstalling them, they were not installed.

It's because of a bug in npm 5.2, which you recently upgraded to. They'll have it fixed soon.
